model:
  context_size: 4096
  max_tokens: 200
  n_threads: 2
  name: SmithGPT 1.0 4GB
  path: models/smithgpt-1.0-4.gguf
security:
  api_key: SMA-dQdZM9NrHjSr2KEJc8mOkgY4NOEzVBoS
server:
  host: 0.0.0.0
  port: 8000
