#!/usr/bin/env node
/* Generate expanded knowledge JSON files for SmithAI (700+ entries). */
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..', 'SmithAI', 'src', 'main', 'resources', 'knowledge');

function write(name, data) {
  const out = path.join(ROOT, name);
  fs.writeFileSync(out, JSON.stringify(data, null, 2), 'utf-8');
  console.log(`Wrote ${data.length} entries to ${out}`);
}

const entry = (id, category, name, description, tags) => ({ id, category, name, description, tags });

const blocks = () => [
  entry("minecraft:stone","block","Stone","A common solid block found underground. Mined fastest with a pickaxe. Drops cobblestone unless mined with Silk Touch.",["block","mining","building"]),
  entry("minecraft:cobblestone","block","Cobblestone","Dropped when mining stone without Silk Touch. Used for tools, furnaces, and building.",["block","mining","building"]),
  entry("minecraft:granite","block","Granite","An igneous rock variant of stone. Can be polished for decorative building.",["block","mining","building","decorative"]),
  entry("minecraft:diorite","block","Diorite","A white stone variant. Can be polished for decorative use.",["block","mining","building","decorative"]),
  entry("minecraft:andesite","block","Andesite","A gray stone variant. Can be polished for decorative building.",["block","mining","building","decorative"]),
  entry("minecraft:tuff","block","Tuff","A light gray rock found near deepslate. Used for decorative building.",["block","mining","building","decorative"]),
  entry("minecraft:calcite","block","Calcite","A white mineral block found in geode layers. Used for decorative building.",["block","mining","building","decorative"]),
  entry("minecraft:deepslate","block","Deepslate","A dark stone variant found deep underground. Harder than stone and used for building.",["block","mining","building","deep"]),
  entry("minecraft:cobbled_deepslate","block","Cobbled Deepslate","Drops from mining deepslate. Used for tools and building.",["block","mining","building"]),
  entry("minecraft:reinforced_deepslate","block","Reinforced Deepslate","Indestructible block found in the deep dark near the warden. Cannot be mined.",["block","indestructible","deep"]),
  entry("minecraft:bedrock","block","Bedrock","An indestructible block found at the bottom of the world and in the End and Nether roofs.",["block","indestructible"]),
  entry("minecraft:dirt","block","Dirt","A common surface block. Can be tilled into farmland with a hoe.",["block","dirt","farming"]),
  entry("minecraft:grass_block","block","Grass Block","Dirt covered in grass. Common in the Overworld surface. Can be silk-touched.",["block","dirt","grass"]),
  entry("minecraft:mycelium","block","Mycelium","Dirt covered in fungus. Found in mushroom fields. Great for growing mushrooms.",["block","dirt","mushroom"]),
  entry("minecraft:podzol","block","Podzol","Dirt covered in pine needles. Found in old-growth taiga.",["block","dirt","taiga","building"]),
  entry("minecraft:coarse_dirt","block","Coarse Dirt","Dirt that cannot be tilled. Crafted from dirt and gravel.",["block","dirt","building"]),
  entry("minecraft:rooted_dirt","block","Rooted Dirt","Dirt with roots under azalea trees. Can be converted to dirt.",["block","dirt","roots"]),
  entry("minecraft:mud","block","Mud","Found in mangrove swamps. Can be packed into mud bricks or combined with wheat into packed mud.",["block","mud","swamp"]),
  entry("minecraft:clay","block","Clay","Found underwater in rivers and lakes. Smelt into bricks or terracotta.",["block","clay","water"]),
  entry("minecraft:terracotta","block","Terracotta","A hardened clay block found in Badlands. Can be dyed into colored variants.",["block","building","decorative"]),
  entry("minecraft:white_terracotta","block","White Terracotta","Dyed terracotta. Used for decorative building.",["block","building","decorative"]),
  entry("minecraft:iron_ore","block","Iron Ore","Iron ore is found underground, usually between Y=-64 and Y=72. Requires a stone pickaxe or better. Smelt it to get iron ingots.",["block","mining","ore","iron"]),
  entry("minecraft:deepslate_iron_ore","block","Deepslate Iron Ore","Iron ore embedded in deepslate. Requires a stone pickaxe or better. Drops iron ore.",["block","mining","ore","iron"]),
  entry("minecraft:gold_ore","block","Gold Ore","Gold ore found around Y=-16 and abundantly in Badlands. Requires an iron pickaxe or better.",["block","mining","ore","gold"]),
  entry("minecraft:deepslate_gold_ore","block","Deepslate Gold Ore","Gold ore embedded in deepslate. Requires an iron pickaxe or better.",["block","mining","ore","gold"]),
  entry("minecraft:diamond_ore","block","Diamond Ore","Diamond ore is found deep underground, most commonly around Y=-59. Requires an iron pickaxe or better.",["block","mining","ore","diamond"]),
  entry("minecraft:deepslate_diamond_ore","block","Deepslate Diamond Ore","Diamond ore embedded in deepslate. Requires an iron pickaxe or better.",["block","mining","ore","diamond"]),
  entry("minecraft:coal_ore","block","Coal Ore","Coal ore is common underground and in mountains. Mined with any pickaxe. Drops coal for torches and fuel.",["block","mining","ore","coal","fuel"]),
  entry("minecraft:deepslate_coal_ore","block","Deepslate Coal Ore","Coal ore embedded in deepslate. Mined with any pickaxe.",["block","mining","ore","coal","fuel"]),
  entry("minecraft:redstone_ore","block","Redstone Ore","Redstone ore is found deep underground. Requires an iron pickaxe or better. Drops redstone dust.",["block","mining","ore","redstone"]),
  entry("minecraft:deepslate_redstone_ore","block","Deepslate Redstone Ore","Redstone ore embedded in deepslate.",["block","mining","ore","redstone"]),
  entry("minecraft:lapis_ore","block","Lapis Lazuli Ore","Lapis ore is found underground. Requires a stone pickaxe or better. Drops lapis lazuli.",["block","mining","ore","lapis"]),
  entry("minecraft:deepslate_lapis_ore","block","Deepslate Lapis Ore","Lapis ore embedded in deepslate.",["block","mining","ore","lapis"]),
  entry("minecraft:copper_ore","block","Copper Ore","Copper ore generates in larger ore blobs underground. Requires a stone pickaxe or better.",["block","mining","ore","copper"]),
  entry("minecraft:deepslate_copper_ore","block","Deepslate Copper Ore","Copper ore embedded in deepslate.",["block","mining","ore","copper"]),
  entry("minecraft:emerald_ore","block","Emerald Ore","Emerald ore is found in mountain biomes. Requires an iron pickaxe or better.",["block","mining","ore","emerald"]),
  entry("minecraft:deepslate_emerald_ore","block","Deepslate Emerald Ore","Emerald ore embedded in deepslate.",["block","mining","ore","emerald"]),
  entry("minecraft:nether_gold_ore","block","Nether Gold Ore","Gold ore found in the Nether. Drops gold nuggets when mined.",["block","nether","mining","ore","gold"]),
  entry("minecraft:nether_quartz_ore","block","Nether Quartz Ore","Quartz ore found in the Nether. Drops nether quartz.",["block","nether","mining","ore","quartz"]),
  entry("minecraft:ancient_debris","block","Ancient Debris","Rare ore found deep in the Nether. Smelted into netherite scrap. Blast-resistant.",["block","nether","mining","ore","netherite"]),
  entry("minecraft:raw_iron_block","block","Block of Raw Iron","A compact block of raw iron. Can be smelted directly.",["block","ore","metal","storage"]),
  entry("minecraft:raw_gold_block","block","Block of Raw Gold","A compact block of raw gold.",["block","ore","metal","storage"]),
  entry("minecraft:raw_copper_block","block","Block of Raw Copper","A compact block of raw copper.",["block","ore","metal","storage"]),
  entry("minecraft:obsidian","block","Obsidian","Created when water touches a lava source. Requires a diamond or netherite pickaxe. Used for nether portals and enchanting tables.",["block","mining","portal","enchanting"]),
  entry("minecraft:crying_obsidian","block","Crying Obsidian","A decorative obsidian variant that emits purple particles. Used to craft respawn anchors.",["block","nether","portal","decorative"]),
  entry("minecraft:glowstone","block","Glowstone","A bright light source found in the Nether. Drops glowstone dust.",["block","light","nether"]),
  entry("minecraft:shroomlight","block","Shroomlight","A light-emitting block found in nether forests.",["block","light","nether"]),
  entry("minecraft:ochre_froglight","block","Ochre Froglight","A warm yellow light block dropped by frogs eating small magma cubes.",["block","light","decorative"]),
  entry("minecraft:verdant_froglight","block","Verdant Froglight","A green light block dropped by frogs eating small magma cubes.",["block","light","decorative"]),
  entry("minecraft:pearlescent_froglight","block","Pearlescent Froglight","A purple light block dropped by frogs eating small magma cubes.",["block","light","decorative"]),
  entry("minecraft:crafting_table","block","Crafting Table","Expands the crafting grid to 3x3. Crafted from 4 wooden planks.",["block","crafting"]),
  entry("minecraft:furnace","block","Furnace","Smelts ores, food, and other items using fuel. Crafted from 8 cobblestone.",["block","smelting","fuel"]),
  entry("minecraft:blast_furnace","block","Blast Furnace","Smelts ores and metal items twice as fast as a furnace.",["block","smelting","ore"]),
  entry("minecraft:smoker","block","Smoker","Cooks food twice as fast as a furnace. Crafted from a furnace and logs.",["block","smelting","food"]),
  entry("minecraft:chest","block","Chest","Stores up to 27 stacks of items. Crafted from 8 wooden planks.",["block","storage"]),
  entry("minecraft:trapped_chest","block","Trapped Chest","A chest that emits a redstone signal when opened.",["block","storage","redstone"]),
  entry("minecraft:ender_chest","block","Ender Chest","A chest whose contents are shared across all ender chests.",["block","storage","end"]),
  entry("minecraft:barrel","block","Barrel","A storage block that can be opened even when blocks are placed on top.",["block","storage"]),
  entry("minecraft:enchanting_table","block","Enchanting Table","Used to enchant tools, weapons, and armor.",["block","enchanting"]),
  entry("minecraft:anvil","block","Anvil","Used to repair, rename, and combine enchanted items.",["block","repair","enchanting"]),
  entry("minecraft:grindstone","block","Grindstone","Used to repair tools or remove enchantments. Returns some experience.",["block","repair","enchanting"]),
  entry("minecraft:stonecutter","block","Stonecutter","Cuts stone blocks into slabs and stairs more efficiently.",["block","building","crafting"]),
  entry("minecraft:loom","block","Loom","Used to apply patterns to banners.",["block","crafting","decorative"]),
  entry("minecraft:smithing_table","block","Smithing Table","Used to upgrade diamond gear to netherite.",["block","crafting","netherite"]),
  entry("minecraft:cartography_table","block","Cartography Table","Used to clone, expand, and lock maps.",["block","crafting","navigation"]),
  entry("minecraft:composter","block","Composter","Converts crops and plants into bone meal.",["block","farming"]),
  entry("minecraft:lectern","block","Lectern","Holds books for multiple players to read. Emits a redstone signal.",["block","redstone","storage"]),
  entry("minecraft:torch","block","Torch","Provides light. Crafted from coal and a stick.",["block","light","torch"]),
  entry("minecraft:soul_torch","block","Soul Torch","A blue torch emitting less light.",["block","light","soul_fire"]),
  entry("minecraft:lantern","block","Lantern","A brighter light source than a torch.",["block","light"]),
  entry("minecraft:soul_lantern","block","Soul Lantern","A blue lantern variant.",["block","light","soul_fire"]),
  entry("minecraft:jack_o_lantern","block","Jack o'Lantern","A carved pumpkin with a torch inside.",["block","light","decorative"]),
  entry("minecraft:sea_lantern","block","Sea Lantern","A bright underwater light source.",["block","light","water"]),
  entry("minecraft:redstone_lamp","block","Redstone Lamp","A lamp that lights up when powered by redstone.",["block","light","redstone"]),
  entry("minecraft:oak_log","block","Oak Log","Wood from oak trees. Can be crafted into planks and sticks.",["block","wood","building"]),
  entry("minecraft:spruce_log","block","Spruce Log","Wood from spruce trees.",["block","wood","building"]),
  entry("minecraft:birch_log","block","Birch Log","Light-colored wood from birch trees.",["block","wood","building"]),
  entry("minecraft:jungle_log","block","Jungle Log","Wood from jungle trees.",["block","wood","building"]),
  entry("minecraft:acacia_log","block","Acacia Log","Wood from acacia trees. Crafted into reddish planks.",["block","wood","building"]),
  entry("minecraft:dark_oak_log","block","Dark Oak Log","Wood from dark oak trees.",["block","wood","building"]),
  entry("minecraft:mangrove_log","block","Mangrove Log","Wood from mangrove trees.",["block","wood","building"]),
  entry("minecraft:cherry_log","block","Cherry Log","Pink-tinted wood from cherry trees.",["block","wood","building","decorative"]),
  entry("minecraft:crimson_stem","block","Crimson Stem","The wood of crimson fungi in the Nether. Not flammable.",["block","wood","nether","building"]),
  entry("minecraft:warped_stem","block","Warped Stem","The wood of warped fungi in the Nether. Not flammable.",["block","wood","nether","building"]),
  entry("minecraft:oak_planks","block","Oak Planks","Basic wooden planks. Used for crafting, sticks, and building.",["block","wood","building"]),
  entry("minecraft:glass","block","Glass","Transparent block made by smelting sand.",["block","glass","building"]),
  entry("minecraft:glass_pane","block","Glass Pane","Thin glass that connects to adjacent panes.",["block","glass","building"]),
  entry("minecraft:white_stained_glass","block","White Stained Glass","Colored glass.",["block","glass","building","decorative"]),
  entry("minecraft:sand","block","Sand","A gravity-affected block found in deserts and beaches. Smelt into glass.",["block","sand","glass"]),
  entry("minecraft:red_sand","block","Red Sand","A red variant of sand found in Badlands biomes.",["block","sand","badlands"]),
  entry("minecraft:suspicious_sand","block","Suspicious Sand","Sand containing buried treasure.",["block","sand","treasure"]),
  entry("minecraft:suspicious_gravel","block","Suspicious Gravel","Gravel containing buried treasure.",["block","gravel","treasure"]),
  entry("minecraft:gravel","block","Gravel","A gravity-affected block. Drops flint occasionally.",["block","gravel","flint"]),
  entry("minecraft:snow","block","Snow","A thin layer of snow on the ground.",["block","cold"]),
  entry("minecraft:snow_block","block","Snow Block","A full block of snow.",["block","cold","building"]),
  entry("minecraft:ice","block","Ice","Slippery block that melts in light.",["block","cold","water"]),
  entry("minecraft:packed_ice","block","Packed Ice","Solid ice block that does not melt.",["block","cold","building"]),
  entry("minecraft:blue_ice","block","Blue Ice","Very dense ice for fast boat travel.",["block","cold","building"]),
  entry("minecraft:netherrack","block","Netherrack","The main stone of the Nether. Burns indefinitely when lit.",["block","nether","building"]),
  entry("minecraft:soul_sand","block","Soul Sand","Slows movement. Used for nether wart farms and soul fire.",["block","nether","soul_fire"]),
  entry("minecraft:soul_soil","block","Soul Soil","Found in soul sand valleys. Used to create soul fire.",["block","nether"]),
  entry("minecraft:blackstone","block","Blackstone","A dark stone found in Bastion Remnants. Can substitute stone in recipes.",["block","nether","building"]),
  entry("minecraft:gilded_blackstone","block","Gilded Blackstone","Blackstone that may drop gold nuggets when mined.",["block","nether","ore","gold"]),
  entry("minecraft:basalt","block","Basalt","A dark pillar-like block found in the Nether.",["block","nether","building"]),
  entry("minecraft:smooth_basalt","block","Smooth Basalt","Polished basalt.",["block","nether","building"]),
  entry("minecraft:polished_blackstone","block","Polished Blackstone","The polished form of blackstone.",["block","nether","building","decorative"]),
  entry("minecraft:end_stone","block","End Stone","The main block of the End islands.",["block","end","building"]),
  entry("minecraft:end_stone_bricks","block","End Stone Bricks","A decorative variant of end stone.",["block","end","building","decorative"]),
  entry("minecraft:purpur_block","block","Purpur Block","A decorative block from End cities.",["block","end","building","decorative"]),
  entry("minecraft:purpur_pillar","block","Purpur Pillar","A pillar variant of purpur.",["block","end","building","decorative"]),
  entry("minecraft:prismarine","block","Prismarine","A sea-themed block found in ocean monuments.",["block","water","ocean"]),
  entry("minecraft:prismarine_bricks","block","Prismarine Bricks","A brick variant of prismarine.",["block","water","ocean","building"]),
  entry("minecraft:dark_prismarine","block","Dark Prismarine","A dark variant of prismarine.",["block","water","ocean","building"]),
  entry("minecraft:sponge","block","Sponge","Absorbs water in a 7-block radius.",["block","water","sponge"]),
  entry("minecraft:wet_sponge","block","Wet Sponge","A waterlogged sponge. Dry in a furnace.",["block","water","sponge"]),
  entry("minecraft:melon","block","Melon","Grows from melon seeds.",["block","farming","food"]),
  entry("minecraft:pumpkin","block","Pumpkin","Grows from pumpkin seeds.",["block","farming","decorative"]),
  entry("minecraft:carved_pumpkin","block","Carved Pumpkin","A pumpkin with a face.",["block","decorative"]),
  entry("minecraft:hay_bale","block","Hay Bale","A compact block of wheat.",["block","farming","fuel","storage"]),
  entry("minecraft:dried_kelp_block","block","Dried Kelp Block","A fuel block.",["block","fuel"]),
  entry("minecraft:honey_block","block","Honey Block","A sticky block that slows movement.",["block","redstone","sticky"]),
  entry("minecraft:honeycomb_block","block","Honeycomb Block","A decorative block crafted from honeycombs.",["block","building","decorative"]),
  entry("minecraft:beehive","block","Beehive","A home for bees.",["block","farming"]),
  entry("minecraft:bee_nest","block","Bee Nest","A naturally generated bee home.",["block","farming"]),
  entry("minecraft:cactus","block","Cactus","A desert plant that damages on contact.",["block","desert","plant"]),
  entry("minecraft:sugar_cane","block","Sugar Cane","Grows near water.",["block","farming","plant"]),
  entry("minecraft:bamboo","block","Bamboo","Fast-growing plant.",["block","farming","plant"]),
  entry("minecraft:vine","block","Vines","Climbable vines found in jungles and swamps.",["block","plant"]),
  entry("minecraft:twisting_vines","block","Twisting Vines","Climbable vines in warped forests.",["block","nether","plant"]),
  entry("minecraft:weeping_vines","block","Weeping Vines","Vines from crimson forests.",["block","nether","plant"]),
  entry("minecraft:sculk","block","Sculk","A block that spreads by consuming experience.",["block","deep","redstone"]),
  entry("minecraft:sculk_catalyst","block","Sculk Catalyst","A sculk block that spreads when a mob dies nearby.",["block","deep","redstone"]),
  entry("minecraft:sculk_shrieker","block","Sculk Shrieker","Summons the warden when triggered.",["block","deep","redstone"]),
  entry("minecraft:sculk_sensor","block","Sculk Sensor","A redstone component that detects vibrations.",["block","deep","redstone"]),
  entry("minecraft:calibrated_sculk_sensor","block","Calibrated Sculk Sensor","A sculk sensor that filters specific vibration frequencies.",["block","deep","redstone"]),
  entry("minecraft:white_wool","block","White Wool","Dropped from sheep or crafted from string.",["block","wool","bed"]),
  entry("minecraft:bookshelf","block","Bookshelf","Bookshelves around an enchanting table improve enchantment levels.",["block","enchanting","building"]),
];

const mobs = () => [
  entry("minecraft:zombie","mob","Zombie","A hostile mob that spawns in dark areas. Burns in sunlight. Drops rotten flesh.",["mob","hostile","overworld"]),
  entry("minecraft:zombie_villager","mob","Zombie Villager","A villager turned into a zombie. Can be cured with a golden apple and weakness potion.",["mob","hostile","overworld","village"]),
  entry("minecraft:drowned","mob","Drowned","Underwater zombie that can spawn with tridents.",["mob","hostile","water"]),
  entry("minecraft:husk","mob","Husk","Desert zombie variant. Does not burn in sunlight.",["mob","hostile","desert"]),
  entry("minecraft:skeleton","mob","Skeleton","Shoots arrows. Burns in sunlight. Drops bones and arrows.",["mob","hostile","overworld","ranged"]),
  entry("minecraft:stray","mob","Stray","Skeleton variant in cold biomes. Shoots arrows of Slowness.",["mob","hostile","cold","ranged"]),
  entry("minecraft:wither_skeleton","mob","Wither Skeleton","Spawns in Nether fortresses. Inflicts Wither. Drops coal, bones, and rarely skulls.",["mob","hostile","nether"]),
  entry("minecraft:creeper","mob","Creeper","Approaches and explodes. Drops gunpowder.",["mob","hostile","overworld","explosive"]),
  entry("minecraft:charged_creeper","mob","Charged Creeper","A creeper struck by lightning. Larger explosion, drops mob heads.",["mob","hostile","overworld","explosive","rare"]),
  entry("minecraft:spider","mob","Spider","Hostile at night, neutral in daylight. Climbs walls.",["mob","hostile","overworld"]),
  entry("minecraft:cave_spider","mob","Cave Spider","Smaller venomous spider in mineshafts.",["mob","hostile","overworld","poison"]),
  entry("minecraft:enderman","mob","Enderman","Tall mob that teleports and picks up blocks. Aggressive if looked at.",["mob","hostile","overworld","end"]),
  entry("minecraft:endermite","mob","Endermite","Small hostile that spawns rarely when using ender pearls.",["mob","hostile"]),
  entry("minecraft:shulker","mob","Shulker","Shell-like mob in End cities. Fires levitation projectiles.",["mob","hostile","end"]),
  entry("minecraft:witch","mob","Witch","Throws splash potions. Spawns in swamps and raids.",["mob","hostile","overworld","ranged"]),
  entry("minecraft:slime","mob","Slime","Spawns in swamps and slime chunks. Splits when killed.",["mob","hostile","overworld"]),
  entry("minecraft:magma_cube","mob","Magma Cube","Nether slime variant. Drops magma cream.",["mob","hostile","nether"]),
  entry("minecraft:phantom","mob","Phantom","Flying mob that attacks players who haven't slept.",["mob","hostile","overworld","flying"]),
  entry("minecraft:blaze","mob","Blaze","Found in Nether fortresses. Shoots fireballs. Drops blaze rods.",["mob","hostile","nether","blaze"]),
  entry("minecraft:ghast","mob","Ghast","Flying Nether mob that shoots explosive fireballs.",["mob","hostile","nether","ranged"]),
  entry("minecraft:hoglin","mob","Hoglin","Hostile boar-like mob in the Nether.",["mob","hostile","nether"]),
  entry("minecraft:zoglin","mob","Zoglin","A zombified Hoglin.",["mob","hostile","nether"]),
  entry("minecraft:piglin","mob","Piglin","Neutral if wearing gold armor. Barters gold ingots.",["mob","neutral","nether"]),
  entry("minecraft:piglin_brute","mob","Piglin Brute","Stronger hostile Piglin in Bastion Remnants.",["mob","hostile","nether"]),
  entry("minecraft:ender_dragon","mob","Ender Dragon","The final boss. Defeat by destroying crystals then attacking.",["mob","boss","end","dragon"]),
  entry("minecraft:wither","mob","Wither","A boss spawned with soul sand and skulls. Drops a nether star.",["mob","boss","nether"]),
  entry("minecraft:warden","mob","Warden","Powerful mob spawned by sculk. Blind but senses vibrations.",["mob","boss","deep_dark"]),
  entry("minecraft:iron_golem","mob","Iron Golem","Neutral mob that protects villages.",["mob","neutral","village","golem"]),
  entry("minecraft:snow_golem","mob","Snow Golem","Passive mob built from snow. Throws snowballs.",["mob","passive","golem"]),
  entry("minecraft:villager","mob","Villager","Passive mob that trades items.",["mob","passive","village","trading"]),
  entry("minecraft:wandering_trader","mob","Wandering Trader","Spawns randomly offering rare trades.",["mob","passive","trading"]),
  entry("minecraft:cow","mob","Cow","Passive mob that drops beef and leather. Can be milked.",["mob","passive","food","farm"]),
  entry("minecraft:pig","mob","Pig","Passive mob that drops porkchops.",["mob","passive","food","farm"]),
  entry("minecraft:sheep","mob","Sheep","Passive mob that drops wool and mutton.",["mob","passive","wool","farm"]),
  entry("minecraft:chicken","mob","Chicken","Passive mob that drops feathers and raw chicken. Lays eggs.",["mob","passive","food","farm"]),
  entry("minecraft:rabbit","mob","Rabbit","Small passive mob.",["mob","passive","food"]),
  entry("minecraft:mooshroom","mob","Mooshroom","Cow variant on mushroom islands.",["mob","passive","food","mushroom"]),
  entry("minecraft:horse","mob","Horse","Can be tamed and ridden.",["mob","passive","transport"]),
  entry("minecraft:donkey","mob","Donkey","Can be tamed and equipped with a chest.",["mob","passive","transport","storage"]),
  entry("minecraft:mule","mob","Mule","Born from horse and donkey. Can carry a chest.",["mob","passive","transport","storage"]),
  entry("minecraft:skeleton_horse","mob","Skeleton Horse","A rideable undead horse.",["mob","passive","transport"]),
  entry("minecraft:zombie_horse","mob","Zombie Horse","A rare undead horse. Cannot be tamed in survival.",["mob","passive","transport","rare"]),
  entry("minecraft:llama","mob","Llama","Carries chests and forms caravans.",["mob","passive","transport","storage"]),
  entry("minecraft:trader_llama","mob","Trader Llama","Llamas that follow wandering traders.",["mob","passive","transport"]),
  entry("minecraft:wolf","mob","Wolf","Neutral mob tamed with bones.",["mob","neutral","pet","combat"]),
  entry("minecraft:cat","mob","Cat","Tamed with raw fish. Scares creepers.",["mob","passive","pet"]),
  entry("minecraft:parrot","mob","Parrot","Passive flying mob that mimics sounds.",["mob","passive","pet","flying"]),
  entry("minecraft:fox","mob","Fox","Nocturnal mob that picks up items.",["mob","passive"]),
  entry("minecraft:bee","mob","Bee","Pollinates crops and produces honey.",["mob","passive","flying","farm"]),
  entry("minecraft:bat","mob","Bat","Flying passive mob in caves.",["mob","passive","flying","cave"]),
  entry("minecraft:squid","mob","Squid","Passive water mob that drops ink sacs.",["mob","passive","water"]),
  entry("minecraft:glow_squid","mob","Glow Squid","Passive glowing water mob.",["mob","passive","water"]),
  entry("minecraft:dolphin","mob","Dolphin","Neutral water mob that boosts swimming.",["mob","neutral","water"]),
  entry("minecraft:turtle","mob","Turtle","Passive beach mob that lays eggs.",["mob","passive","water","beach"]),
  entry("minecraft:polar_bear","mob","Polar Bear","Neutral mob in snowy biomes.",["mob","neutral","cold"]),
  entry("minecraft:panda","mob","Panda","Neutral mob in bamboo jungles.",["mob","neutral","jungle"]),
  entry("minecraft:ocelot","mob","Ocelot","Passive jungle mob. Creepers avoid them.",["mob","passive","jungle"]),
  entry("minecraft:axolotl","mob","Axolotl","Passive water mob that plays dead.",["mob","passive","water"]),
  entry("minecraft:frog","mob","Frog","Passive mob found in swamps. Eats small slimes.",["mob","passive","swamp"]),
  entry("minecraft:tadpole","mob","Tadpole","Baby frog. Grows into a frog.",["mob","passive","water"]),
  entry("minecraft:allay","mob","Allay","Flying mob that collects items for players.",["mob","passive","flying"]),
  entry("minecraft:goat","mob","Goat","Neutral mountain mob that rams players.",["mob","neutral","cold"]),
  entry("minecraft:ravager","mob","Ravager","Large hostile mob in raids.",["mob","hostile","raid"]),
  entry("minecraft:evoker","mob","Evoker","Hostile illager that summons vexes.",["mob","hostile","illager","raid"]),
  entry("minecraft:vindicator","mob","Vindicator","Hostile illager with an axe.",["mob","hostile","illager","raid"]),
  entry("minecraft:pillager","mob","Pillager","Hostile illager with a crossbow.",["mob","hostile","illager","raid"]),
  entry("minecraft:vex","mob","Vex","Small hostile flying mob. Passes through blocks.",["mob","hostile","illager","flying"]),
  entry("minecraft:illusioner","mob","Illusioner","Hostile illager that creates illusions.",["mob","hostile","illager","ranged","rare"]),
];

const items = () => [
  entry("minecraft:wooden_pickaxe","item","Wooden Pickaxe","Can mine stone and coal ore.",["item","tool","pickaxe","wood"]),
  entry("minecraft:stone_pickaxe","item","Stone Pickaxe","Can mine iron ore and lapis.",["item","tool","pickaxe","stone"]),
  entry("minecraft:iron_pickaxe","item","Iron Pickaxe","Can mine diamond ore, redstone, and gold.",["item","tool","pickaxe","iron"]),
  entry("minecraft:diamond_pickaxe","item","Diamond Pickaxe","Fast, durable pickaxe. Can mine obsidian.",["item","tool","pickaxe","diamond"]),
  entry("minecraft:netherite_pickaxe","item","Netherite Pickaxe","The strongest pickaxe.",["item","tool","pickaxe","netherite"]),
  entry("minecraft:wooden_axe","item","Wooden Axe","Chops wood faster.",["item","tool","axe","wood"]),
  entry("minecraft:stone_axe","item","Stone Axe","Basic axe.",["item","tool","axe","stone"]),
  entry("minecraft:iron_axe","item","Iron Axe","Durable iron axe.",["item","tool","axe","iron"]),
  entry("minecraft:diamond_axe","item","Diamond Axe","Very fast axe.",["item","tool","axe","diamond"]),
  entry("minecraft:netherite_axe","item","Netherite Axe","The strongest axe.",["item","tool","axe","netherite"]),
  entry("minecraft:wooden_shovel","item","Wooden Shovel","Basic shovel.",["item","tool","shovel","wood"]),
  entry("minecraft:stone_shovel","item","Stone Shovel","Better shovel.",["item","tool","shovel","stone"]),
  entry("minecraft:iron_shovel","item","Iron Shovel","Durable shovel.",["item","tool","shovel","iron"]),
  entry("minecraft:diamond_shovel","item","Diamond Shovel","Very fast shovel.",["item","tool","shovel","diamond"]),
  entry("minecraft:netherite_shovel","item","Netherite Shovel","The strongest shovel.",["item","tool","shovel","netherite"]),
  entry("minecraft:wooden_hoe","item","Wooden Hoe","Tills dirt into farmland.",["item","tool","hoe","wood"]),
  entry("minecraft:stone_hoe","item","Stone Hoe","Tills dirt into farmland.",["item","tool","hoe","stone"]),
  entry("minecraft:iron_hoe","item","Iron Hoe","Tills dirt into farmland.",["item","tool","hoe","iron"]),
  entry("minecraft:diamond_hoe","item","Diamond Hoe","Fastest hoe.",["item","tool","hoe","diamond"]),
  entry("minecraft:netherite_hoe","item","Netherite Hoe","The strongest hoe.",["item","tool","hoe","netherite"]),
  entry("minecraft:wooden_sword","item","Wooden Sword","Lowest tier sword.",["item","weapon","sword","wood"]),
  entry("minecraft:stone_sword","item","Stone Sword","Basic sword.",["item","weapon","sword","stone"]),
  entry("minecraft:iron_sword","item","Iron Sword","Durable sword.",["item","weapon","sword","iron"]),
  entry("minecraft:diamond_sword","item","Diamond Sword","Fast, durable sword.",["item","weapon","sword","diamond"]),
  entry("minecraft:netherite_sword","item","Netherite Sword","The strongest sword.",["item","weapon","sword","netherite"]),
  entry("minecraft:bow","item","Bow","Ranged weapon.",["item","weapon","ranged"]),
  entry("minecraft:crossbow","item","Crossbow","Ranged weapon loaded with arrows or fireworks.",["item","weapon","ranged"]),
  entry("minecraft:arrow","item","Arrow","Ammo for bows and crossbows.",["item","weapon","ranged","ammo"]),
  entry("minecraft:spectral_arrow","item","Spectral Arrow","Arrow that gives the Glowing effect.",["item","weapon","ranged","ammo"]),
  entry("minecraft:tipped_arrow","item","Tipped Arrow","Arrow tipped with a potion effect.",["item","weapon","ranged","ammo","potion"]),
  entry("minecraft:trident","item","Trident","Melee and ranged weapon.",["item","weapon","water"]),
  entry("minecraft:shield","item","Shield","Blocks incoming attacks.",["item","weapon","defense"]),
  entry("minecraft:turtle_helmet","item","Turtle Shell","Helmet giving water breathing.",["item","armor","water"]),
  entry("minecraft:leather_helmet","item","Leather Helmet","Basic helmet.",["item","armor","leather"]),
  entry("minecraft:leather_chestplate","item","Leather Chestplate","Basic chestplate.",["item","armor","leather"]),
  entry("minecraft:leather_leggings","item","Leather Leggings","Basic leggings.",["item","armor","leather"]),
  entry("minecraft:leather_boots","item","Leather Boots","Basic boots.",["item","armor","leather"]),
  entry("minecraft:chainmail_helmet","item","Chainmail Helmet","Cannot be crafted.",["item","armor","chain"]),
  entry("minecraft:chainmail_chestplate","item","Chainmail Chestplate","Cannot be crafted.",["item","armor","chain"]),
  entry("minecraft:chainmail_leggings","item","Chainmail Leggings","Cannot be crafted.",["item","armor","chain"]),
  entry("minecraft:chainmail_boots","item","Chainmail Boots","Cannot be crafted.",["item","armor","chain"]),
  entry("minecraft:iron_helmet","item","Iron Helmet","Iron helmet.",["item","armor","iron"]),
  entry("minecraft:iron_chestplate","item","Iron Chestplate","Iron chestplate.",["item","armor","iron"]),
  entry("minecraft:iron_leggings","item","Iron Leggings","Iron leggings.",["item","armor","iron"]),
  entry("minecraft:iron_boots","item","Iron Boots","Iron boots.",["item","armor","iron"]),
  entry("minecraft:diamond_helmet","item","Diamond Helmet","Diamond helmet.",["item","armor","diamond"]),
  entry("minecraft:diamond_chestplate","item","Diamond Chestplate","Diamond chestplate.",["item","armor","diamond"]),
  entry("minecraft:diamond_leggings","item","Diamond Leggings","Diamond leggings.",["item","armor","diamond"]),
  entry("minecraft:diamond_boots","item","Diamond Boots","Diamond boots.",["item","armor","diamond"]),
  entry("minecraft:netherite_helmet","item","Netherite Helmet","Best helmet.",["item","armor","netherite"]),
  entry("minecraft:netherite_chestplate","item","Netherite Chestplate","Best chestplate.",["item","armor","netherite"]),
  entry("minecraft:netherite_leggings","item","Netherite Leggings","Best leggings.",["item","armor","netherite"]),
  entry("minecraft:netherite_boots","item","Netherite Boots","Best boots.",["item","armor","netherite"]),
  entry("minecraft:elytra","item","Elytra","Wings for gliding. Found in End ships.",["item","armor","end","flying"]),
  entry("minecraft:stick","item","Stick","Basic crafting material.",["item","material"]),
  entry("minecraft:iron_ingot","item","Iron Ingot","Metal for tools, armor, and recipes.",["item","material","iron"]),
  entry("minecraft:gold_ingot","item","Gold Ingot","Metal for powered rails, golden apples, and armor.",["item","material","gold"]),
  entry("minecraft:copper_ingot","item","Copper Ingot","Metal for lightning rods and telescopes.",["item","material","copper"]),
  entry("minecraft:netherite_ingot","item","Netherite Ingot","Best material.",["item","material","netherite"]),
  entry("minecraft:netherite_scrap","item","Netherite Scrap","Smelted from ancient debris.",["item","material","netherite"]),
  entry("minecraft:diamond","item","Diamond","Rare gem for best tools and armor.",["item","material","diamond"]),
  entry("minecraft:emerald","item","Emerald","Currency for villager trading.",["item","material","currency"]),
  entry("minecraft:quartz","item","Nether Quartz","Mined from nether quartz ore.",["item","material","nether"]),
  entry("minecraft:amethyst_shard","item","Amethyst Shard","Mined from amethyst clusters.",["item","material"]),
  entry("minecraft:redstone","item","Redstone Dust","Used for circuits and mechanisms.",["item","material","redstone","circuit"]),
  entry("minecraft:lapis_lazuli","item","Lapis Lazuli","Used for enchanting and blue dye.",["item","material","dye","enchanting"]),
  entry("minecraft:coal","item","Coal","Fuel and light source.",["item","fuel","material"]),
  entry("minecraft:charcoal","item","Charcoal","Fuel made by smelting wood.",["item","fuel","material"]),
  entry("minecraft:flint","item","Flint","Used for flint and steel and arrows.",["item","material"]),
  entry("minecraft:flint_and_steel","item","Flint and Steel","Ignites fire and nether portals.",["item","tool","fire"]),
  entry("minecraft:torch","item","Torch","Provides light.",["item","light"]),
  entry("minecraft:soul_torch","item","Soul Torch","Blue torch.",["item","light","soul_fire"]),
  entry("minecraft:bed","item","Bed","Sets spawn point and skips night.",["item","bed","spawn"]),
  entry("minecraft:respawn_anchor","item","Respawn Anchor","Sets respawn in the Nether.",["item","bed","nether","spawn"]),
  entry("minecraft:bucket","item","Bucket","Holds water, lava, milk, or powder snow.",["item","tool","container"]),
  entry("minecraft:water_bucket","item","Water Bucket","Bucket of water.",["item","tool","water"]),
  entry("minecraft:lava_bucket","item","Lava Bucket","Bucket of lava.",["item","tool","lava","fuel"]),
  entry("minecraft:milk_bucket","item","Milk Bucket","Clears potion effects.",["item","tool","food"]),
  entry("minecraft:powder_snow_bucket","item","Powder Snow Bucket","Bucket of powder snow.",["item","tool","cold"]),
  entry("minecraft:shears","item","Shears","Shears sheep and mines leaves.",["item","tool"]),
  entry("minecraft:compass","item","Compass","Points to world spawn.",["item","tool","navigation"]),
  entry("minecraft:recovery_compass","item","Recovery Compass","Points to last death location.",["item","tool","navigation"]),
  entry("minecraft:clock","item","Clock","Shows the time of day.",["item","tool"]),
  entry("minecraft:spyglass","item","Spyglass","Zooms in on distant objects.",["item","tool"]),
  entry("minecraft:map","item","Map","Shows explored area.",["item","tool","navigation"]),
  entry("minecraft:book","item","Book","Used for bookshelves and enchanted books.",["item","material"]),
  entry("minecraft:writable_book","item","Book and Quill","A writable book.",["item","material"]),
  entry("minecraft:written_book","item","Written Book","A signed book.",["item","material"]),
  entry("minecraft:paper","item","Paper","Made from sugar cane.",["item","material"]),
  entry("minecraft:leather","item","Leather","Dropped from cows and horses.",["item","material"]),
  entry("minecraft:feather","item","Feather","Dropped from chickens.",["item","material"]),
  entry("minecraft:string","item","String","Dropped from spiders.",["item","material"]),
  entry("minecraft:gunpowder","item","Gunpowder","Dropped from creepers and ghasts.",["item","material","explosive"]),
  entry("minecraft:bone","item","Bone","Dropped from skeletons.",["item","material"]),
  entry("minecraft:bone_meal","item","Bone Meal","Speeds up crop growth.",["item","material","farming","dye"]),
  entry("minecraft:ender_pearl","item","Ender Pearl","Dropped from Endermen. Used to teleport or craft Eyes of Ender.",["item","material","end","teleport"]),
  entry("minecraft:eye_of_ender","item","Eye of Ender","Crafted from ender pearl and blaze powder.",["item","material","end","navigation"]),
  entry("minecraft:blaze_rod","item","Blaze Rod","Dropped from Blazes. Used for brewing.",["item","material","nether","brewing"]),
  entry("minecraft:blaze_powder","item","Blaze Powder","Made from blaze rods.",["item","material","nether","brewing"]),
  entry("minecraft:ghast_tear","item","Ghast Tear","Dropped from Ghasts. Used for regeneration potions.",["item","material","nether","brewing"]),
  entry("minecraft:nether_wart","item","Nether Wart","Grown on soul sand. Base for most potions.",["item","material","nether","brewing"]),
  entry("minecraft:sugar","item","Sugar","Made from sugar cane.",["item","material","food","brewing"]),
  entry("minecraft:glistering_melon_slice","item","Glistering Melon Slice","Melon slice and gold nugget.",["item","material","brewing"]),
  entry("minecraft:golden_carrot","item","Golden Carrot","Carrot surrounded by gold nuggets.",["item","material","brewing","food"]),
  entry("minecraft:fermented_spider_eye","item","Fermented Spider Eye","Creates negative potions.",["item","material","brewing"]),
  entry("minecraft:magma_cream","item","Magma Cream","For fire resistance potions.",["item","material","nether","brewing"]),
  entry("minecraft:phantom_membrane","item","Phantom Membrane","For slow falling potions.",["item","material","brewing"]),
  entry("minecraft:potion","item","Potion","A brewable item with various effects.",["item","potion","brewing"]),
  entry("minecraft:splash_potion","item","Splash Potion","A potion that splashes.",["item","potion","brewing"]),
  entry("minecraft:lingering_potion","item","Lingering Potion","Leaves a lingering cloud.",["item","potion","brewing"]),
  entry("minecraft:glass_bottle","item","Glass Bottle","Holds potions.",["item","tool","brewing"]),
  entry("minecraft:brewing_stand","item","Brewing Stand","Brews potions.",["item","tool","brewing"]),
  entry("minecraft:cauldron","item","Cauldron","Holds water, potions, or dyed water.",["item","tool","brewing"]),
  entry("minecraft:sugar_cane","item","Sugar Cane","Grows near water.",["item","material","farming"]),
  entry("minecraft:wheat","item","Wheat","Grown on farmland.",["item","food","farming"]),
  entry("minecraft:bread","item","Bread","Crafted from wheat.",["item","food"]),
  entry("minecraft:carrot","item","Carrot","Grown on farmland.",["item","food","farming"]),
  entry("minecraft:potato","item","Potato","Grown on farmland.",["item","food","farming"]),
  entry("minecraft:baked_potato","item","Baked Potato","Potato baked in a furnace.",["item","food"]),
  entry("minecraft:beetroot","item","Beetroot","Grown on farmland.",["item","food","farming"]),
  entry("minecraft:beetroot_soup","item","Beetroot Soup","Beets and bowl.",["item","food"]),
  entry("minecraft:melon_slice","item","Melon Slice","Food from melons.",["item","food"]),
  entry("minecraft:pumpkin","item","Pumpkin","Grown from seeds.",["item","food","farming"]),
  entry("minecraft:apple","item","Apple","Dropped from oak leaves.",["item","food"]),
  entry("minecraft:golden_apple","item","Golden Apple","Grants absorption and regeneration.",["item","food","combat"]),
  entry("minecraft:enchanted_golden_apple","item","Enchanted Golden Apple","Rare golden apple.",["item","food","combat","rare"]),
  entry("minecraft:raw_beef","item","Raw Beef","Dropped from cows.",["item","food"]),
  entry("minecraft:cooked_beef","item","Steak","One of the best food sources.",["item","food"]),
  entry("minecraft:raw_porkchop","item","Raw Porkchop","From pigs and hoglins.",["item","food"]),
  entry("minecraft:cooked_porkchop","item","Cooked Porkchop","Cooked pork.",["item","food"]),
  entry("minecraft:chicken","item","Raw Chicken","From chickens. May cause hunger when raw.",["item","food"]),
  entry("minecraft:cooked_chicken","item","Cooked Chicken","Cooked chicken.",["item","food"]),
  entry("minecraft:raw_mutton","item","Raw Mutton","From sheep.",["item","food"]),
  entry("minecraft:cooked_mutton","item","Cooked Mutton","Cooked mutton.",["item","food"]),
  entry("minecraft:raw_rabbit","item","Raw Rabbit","From rabbits.",["item","food"]),
  entry("minecraft:cooked_rabbit","item","Cooked Rabbit","Cooked rabbit.",["item","food"]),
  entry("minecraft:rabbit_stew","item","Rabbit Stew","Rabbit, carrot, potato, mushrooms in a bowl.",["item","food"]),
  entry("minecraft:rotten_flesh","item","Rotten Flesh","From zombies. May cause hunger.",["item","food"]),
  entry("minecraft:spider_eye","item","Spider Eye","From spiders. For poison potions.",["item","material","brewing"]),
  entry("minecraft:poisonous_potato","item","Poisonous Potato","Rare potato drop. Poisons when eaten.",["item","food"]),
  entry("minecraft:cookie","item","Cookie","Wheat and cocoa beans.",["item","food"]),
  entry("minecraft:cake","item","Cake","Wheat, sugar, eggs, and milk.",["item","food"]),
  entry("minecraft:pumpkin_pie","item","Pumpkin Pie","Pumpkin, sugar, and egg.",["item","food"]),
  entry("minecraft:mushroom_stew","item","Mushroom Stew","Red and brown mushroom in a bowl.",["item","food"]),
  entry("minecraft:suspicious_stew","item","Suspicious Stew","Brewed from flowers. Random effects.",["item","food"]),
  entry("minecraft:cod","item","Raw Cod","Caught in water.",["item","food","water"]),
  entry("minecraft:salmon","item","Raw Salmon","Caught in cold water.",["item","food","water"]),
  entry("minecraft:tropical_fish","item","Tropical Fish","Colorful fish.",["item","food","water"]),
  entry("minecraft:pufferfish","item","Pufferfish","For water breathing potions. Poisonous to eat.",["item","food","water","brewing"]),
  entry("minecraft:cooked_cod","item","Cooked Cod","Cooked cod.",["item","food"]),
  entry("minecraft:cooked_salmon","item","Cooked Salmon","Cooked salmon.",["item","food"]),
  entry("minecraft:dried_kelp","item","Dried Kelp","Easy early-game food.",["item","food"]),
  entry("minecraft:honey_bottle","item","Honey Bottle","Cures poison.",["item","food"]),
  entry("minecraft:experience_bottle","item","Bottle o' Enchanting","Releases experience orbs.",["item","enchanting"]),
  entry("minecraft:ink_sac","item","Ink Sac","Black dye. From squid.",["item","dye","material"]),
  entry("minecraft:glow_ink_sac","item","Glow Ink Sac","Glow item frame maker.",["item","dye","material"]),
  entry("minecraft:cocoa_beans","item","Cocoa Beans","Brown dye. Grows on jungle logs.",["item","dye","farming"]),
  entry("minecraft:slime_ball","item","Slime Ball","From slimes. For sticky pistons and leads.",["item","material"]),
  entry("minecraft:honeycomb","item","Honeycomb","From bee nests. For candles.",["item","material"]),
  entry("minecraft:nautilus_shell","item","Nautilus Shell","From fishing or drowned.",["item","material","water"]),
  entry("minecraft:heart_of_the_sea","item","Heart of the Sea","Rare treasure.",["item","material","water","rare"]),
  entry("minecraft:conduit","item","Conduit","Underwater beacon.",["item","tool","water"]),
  entry("minecraft:name_tag","item","Name Tag","Names a mob.",["item","tool"]),
  entry("minecraft:saddle","item","Saddle","Rides mounts.",["item","tool","transport"]),
  entry("minecraft:lead","item","Lead","Leads and ties mobs.",["item","tool"]),
  entry("minecraft:fishing_rod","item","Fishing Rod","Catches fish and treasure.",["item","tool"]),
  entry("minecraft:carrot_on_a_stick","item","Carrot on a Stick","Controls saddled pigs.",["item","tool","transport"]),
  entry("minecraft:warped_fungus_on_a_stick","item","Warped Fungus on a Stick","Controls saddled striders.",["item","tool","transport","nether"]),
];

const recipes = () => [
  { id:"recipe:crafting_table",category:"recipe",name:"Crafting Table",description:"Place 4 wooden planks in a 2x2 square in the inventory crafting grid. Expands the grid to 3x3.",tags:["recipe","crafting"] },
  { id:"recipe:stick",category:"recipe",name:"Stick",description:"Place 2 wooden planks vertically in the crafting grid. Used for tools and torches.",tags:["recipe","crafting"] },
  { id:"recipe:torch",category:"recipe",name:"Torch",description:"Place coal above a stick in the crafting grid. Provides light.",tags:["recipe","crafting","light"] },
  { id:"recipe:wooden_pickaxe",category:"recipe",name:"Wooden Pickaxe",description:"3 planks across the top row and 2 sticks vertically in the middle column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:stone_pickaxe",category:"recipe",name:"Stone Pickaxe",description:"3 cobblestone across the top row and 2 sticks vertically in the middle column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:iron_pickaxe",category:"recipe",name:"Iron Pickaxe",description:"3 iron ingots across the top row and 2 sticks vertically in the middle column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:diamond_pickaxe",category:"recipe",name:"Diamond Pickaxe",description:"3 diamonds across the top row and 2 sticks vertically in the middle column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:wooden_axe",category:"recipe",name:"Wooden Axe",description:"3 planks in corners. 2 sticks in the right column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:stone_axe",category:"recipe",name:"Stone Axe",description:"3 cobblestone in corners. 2 sticks in the right column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:iron_axe",category:"recipe",name:"Iron Axe",description:"3 iron ingots in corners. 2 sticks in the right column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:wooden_sword",category:"recipe",name:"Wooden Sword",description:"2 planks vertically and 1 stick below.",tags:["recipe","crafting","weapon"] },
  { id:"recipe:stone_sword",category:"recipe",name:"Stone Sword",description:"2 cobblestone vertically and 1 stick below.",tags:["recipe","crafting","weapon"] },
  { id:"recipe:iron_sword",category:"recipe",name:"Iron Sword",description:"2 iron ingots vertically and 1 stick below.",tags:["recipe","crafting","weapon"] },
  { id:"recipe:diamond_sword",category:"recipe",name:"Diamond Sword",description:"2 diamonds vertically and 1 stick below.",tags:["recipe","crafting","weapon"] },
  { id:"recipe:wooden_shovel",category:"recipe",name:"Wooden Shovel",description:"1 plank above 2 sticks.",tags:["recipe","crafting","tool"] },
  { id:"recipe:stone_shovel",category:"recipe",name:"Stone Shovel",description:"1 cobblestone above 2 sticks.",tags:["recipe","crafting","tool"] },
  { id:"recipe:iron_shovel",category:"recipe",name:"Iron Shovel",description:"1 iron ingot above 2 sticks.",tags:["recipe","crafting","tool"] },
  { id:"recipe:diamond_shovel",category:"recipe",name:"Diamond Shovel",description:"1 diamond above 2 sticks.",tags:["recipe","crafting","tool"] },
  { id:"recipe:wooden_hoe",category:"recipe",name:"Wooden Hoe",description:"2 planks top-left and top-middle, 2 sticks in right column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:stone_hoe",category:"recipe",name:"Stone Hoe",description:"2 cobblestone top-left and top-middle, 2 sticks in right column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:iron_hoe",category:"recipe",name:"Iron Hoe",description:"2 iron ingots top-left and top-middle, 2 sticks in right column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:diamond_hoe",category:"recipe",name:"Diamond Hoe",description:"2 diamonds top-left and top-middle, 2 sticks in right column.",tags:["recipe","crafting","tool"] },
  { id:"recipe:bucket",category:"recipe",name:"Bucket",description:"3 iron ingots in a V shape.",tags:["recipe","crafting"] },
  { id:"recipe:furnace",category:"recipe",name:"Furnace",description:"8 cobblestone around the edge, center empty.",tags:["recipe","crafting","smelting"] },
  { id:"recipe:blast_furnace",category:"recipe",name:"Blast Furnace",description:"Furnace surrounded by 5 iron ingots and 3 smooth stone below.",tags:["recipe","crafting","smelting"] },
  { id:"recipe:smoker",category:"recipe",name:"Smoker",description:"Furnace surrounded by 4 logs.",tags:["recipe","crafting","smelting","food"] },
  { id:"recipe:chest",category:"recipe",name:"Chest",description:"8 wooden planks around the edge, center empty.",tags:["recipe","crafting","storage"] },
  { id:"recipe:bed",category:"recipe",name:"Bed",description:"3 wool across top row and 3 planks across middle row.",tags:["recipe","crafting","bed"] },
  { id:"recipe:shield",category:"recipe",name:"Shield",description:"6 wood planks in Y shape plus 1 iron ingot top-middle.",tags:["recipe","crafting","defense"] },
  { id:"recipe:bow",category:"recipe",name:"Bow",description:"3 sticks and 3 string in a U shape.",tags:["recipe","crafting","weapon"] },
  { id:"recipe:crossbow",category:"recipe",name:"Crossbow",description:"3 sticks, 2 string, 1 iron ingot, 1 tripwire hook.",tags:["recipe","crafting","weapon"] },
  { id:"recipe:arrow",category:"recipe",name:"Arrow",description:"Flint on top, stick in middle, feather on bottom.",tags:["recipe","crafting","ammo"] },
  { id:"recipe:paper",category:"recipe",name:"Paper",description:"3 sugar canes horizontally.",tags:["recipe","crafting"] },
  { id:"recipe:book",category:"recipe",name:"Book",description:"3 paper and 1 leather.",tags:["recipe","crafting"] },
  { id:"recipe:bookshelf",category:"recipe",name:"Bookshelf",description:"3 books in middle row, 6 wood planks around them.",tags:["recipe","crafting","enchanting"] },
  { id:"recipe:enchanting_table",category:"recipe",name:"Enchanting Table",description:"4 obsidian on bottom, 2 diamonds on sides, 1 book on top.",tags:["recipe","crafting","enchanting"] },
  { id:"recipe:anvil",category:"recipe",name:"Anvil",description:"3 iron blocks top row, 1 iron ingot center, 3 iron ingots bottom row.",tags:["recipe","crafting","repair"] },
  { id:"recipe:grindstone",category:"recipe",name:"Grindstone",description:"2 sticks, 1 stone slab, 2 planks.",tags:["recipe","crafting","repair"] },
  { id:"recipe:smithing_table",category:"recipe",name:"Smithing Table",description:"2 iron ingots above 4 planks.",tags:["recipe","crafting","netherite"] },
  { id:"recipe:stonecutter",category:"recipe",name:"Stonecutter",description:"3 stone and 1 iron ingot.",tags:["recipe","crafting","building"] },
  { id:"recipe:composter",category:"recipe",name:"Composter",description:"7 fence posts in a U shape.",tags:["recipe","crafting","farming"] },
  { id:"recipe:loom",category:"recipe",name:"Loom",description:"2 string and 2 planks.",tags:["recipe","crafting","decorative"] },
  { id:"recipe:cartography_table",category:"recipe",name:"Cartography Table",description:"2 paper above 4 planks.",tags:["recipe","crafting","navigation"] },
  { id:"recipe:iron_helmet",category:"recipe",name:"Iron Helmet",description:"5 iron ingots in an upside-down U.",tags:["recipe","crafting","armor"] },
  { id:"recipe:iron_chestplate",category:"recipe",name:"Iron Chestplate",description:"8 iron ingots filling all but top-middle.",tags:["recipe","crafting","armor"] },
  { id:"recipe:iron_leggings",category:"recipe",name:"Iron Leggings",description:"7 iron ingots in a U shape.",tags:["recipe","crafting","armor"] },
  { id:"recipe:iron_boots",category:"recipe",name:"Iron Boots",description:"4 iron ingots in a U shape.",tags:["recipe","crafting","armor"] },
  { id:"recipe:compass",category:"recipe",name:"Compass",description:"4 iron ingots around redstone.",tags:["recipe","crafting","navigation"] },
  { id:"recipe:clock",category:"recipe",name:"Clock",description:"4 gold ingots around redstone.",tags:["recipe","crafting"] },
  { id:"recipe:flint_and_steel",category:"recipe",name:"Flint and Steel",description:"Flint and iron ingot diagonally.",tags:["recipe","crafting","fire"] },
  { id:"recipe:glass_bottle",category:"recipe",name:"Glass Bottle",description:"3 glass blocks in a V shape.",tags:["recipe","crafting","brewing"] },
  { id:"recipe:brewing_stand",category:"recipe",name:"Brewing Stand",description:"3 cobblestone across bottom, 1 blaze rod in center.",tags:["recipe","crafting","brewing"] },
  { id:"recipe:cauldron",category:"recipe",name:"Cauldron",description:"7 iron ingots in a U shape.",tags:["recipe","crafting"] },
  { id:"recipe:hopper",category:"recipe",name:"Hopper",description:"5 iron ingots and 1 chest in a V shape.",tags:["recipe","crafting","redstone"] },
  { id:"recipe:dispenser",category:"recipe",name:"Dispenser",description:"7 cobblestone, 1 bow, 1 redstone.",tags:["recipe","crafting","redstone"] },
  { id:"recipe:dropper",category:"recipe",name:"Dropper",description:"7 cobblestone and 1 redstone.",tags:["recipe","crafting","redstone"] },
  { id:"recipe:piston",category:"recipe",name:"Piston",description:"3 planks, 4 cobblestone, 1 iron ingot, 1 redstone.",tags:["recipe","crafting","redstone"] },
  { id:"recipe:sticky_piston",category:"recipe",name:"Sticky Piston",description:"1 piston and 1 slime ball.",tags:["recipe","crafting","redstone"] },
  { id:"recipe:redstone_torch",category:"recipe",name:"Redstone Torch",description:"1 redstone above 1 stick.",tags:["recipe","crafting","redstone"] },
  { id:"recipe:repeater",category:"recipe",name:"Redstone Repeater",description:"3 stone, 2 redstone torches, 1 redstone.",tags:["recipe","crafting","redstone"] },
  { id:"recipe:comparator",category:"recipe",name:"Redstone Comparator",description:"3 stone, 3 redstone torches, 1 nether quartz.",tags:["recipe","crafting","redstone"] },
  { id:"recipe:observer",category:"recipe",name:"Observer",description:"6 cobblestone, 2 redstone, 1 nether quartz.",tags:["recipe","crafting","redstone"] },
  { id:"recipe:note_block",category:"recipe",name:"Note Block",description:"8 wood planks around 1 redstone.",tags:["recipe","crafting"] },
  { id:"recipe:jukebox",category:"recipe",name:"Jukebox",description:"8 wood planks around 1 diamond.",tags:["recipe","crafting"] },
  { id:"recipe:tnt",category:"recipe",name:"TNT",description:"5 gunpowder in X and 4 sand around them.",tags:["recipe","crafting","explosive"] },
  { id:"recipe:fire_charge",category:"recipe",name:"Fire Charge",description:"1 coal, 1 gunpowder, 1 blaze powder.",tags:["recipe","crafting","fire"] },
  { id:"recipe:lantern",category:"recipe",name:"Lantern",description:"8 iron nuggets around 1 torch.",tags:["recipe","crafting","light"] },
  { id:"recipe:soul_lantern",category:"recipe",name:"Soul Lantern",description:"8 iron nuggets around 1 soul torch.",tags:["recipe","crafting","light"] },
  { id:"recipe:chain",category:"recipe",name:"Chain",description:"1 iron ingot above 1 iron nugget above 1 iron ingot.",tags:["recipe","crafting","building"] },
  { id:"recipe:bread",category:"recipe",name:"Bread",description:"3 wheat horizontally.",tags:["recipe","crafting","food"] },
  { id:"recipe:bowl",category:"recipe",name:"Bowl",description:"3 planks in a V shape.",tags:["recipe","crafting"] },
  { id:"recipe:spyglass",category:"recipe",name:"Spyglass",description:"1 amethyst shard above 2 copper ingots.",tags:["recipe","crafting","tool"] },
  { id:"recipe:lead",category:"recipe",name:"Lead",description:"4 string and 1 slime ball.",tags:["recipe","crafting"] },
  { id:"recipe:iron_door",category:"recipe",name:"Iron Door",description:"6 iron ingots in two vertical columns.",tags:["recipe","crafting"] },
  { id:"recipe:wooden_door",category:"recipe",name:"Wooden Door",description:"6 planks in two vertical columns.",tags:["recipe","crafting"] },
  { id:"recipe:trapdoor",category:"recipe",name:"Trapdoor",description:"6 planks in two rows of three.",tags:["recipe","crafting"] },
  { id:"recipe:fence",category:"recipe",name:"Fence",description:"4 planks and 2 sticks in alternating columns.",tags:["recipe","crafting"] },
  { id:"recipe:gate",category:"recipe",name:"Fence Gate",description:"2 sticks and 4 planks in a gate shape.",tags:["recipe","crafting"] },
  { id:"recipe:ladder",category:"recipe",name:"Ladder",description:"7 sticks in an H shape.",tags:["recipe","crafting"] },
  { id:"recipe:sign",category:"recipe",name:"Sign",description:"6 planks across top two rows and 1 stick in bottom-middle.",tags:["recipe","crafting"] },
  { id:"recipe:boat",category:"recipe",name:"Boat",description:"5 planks in a U shape.",tags:["recipe","crafting","transport"] },
  { id:"recipe:fishing_rod",category:"recipe",name:"Fishing Rod",description:"3 sticks and 2 string diagonally.",tags:["recipe","crafting","tool"] },
  { id:"recipe:shears",category:"recipe",name:"Shears",description:"2 iron ingots diagonally.",tags:["recipe","crafting","tool"] },
  { id:"recipe:firework_rocket",category:"recipe",name:"Firework Rocket",description:"1 paper and 1 gunpowder. Add stars for effects.",tags:["recipe","crafting"] },
  { id:"recipe:recovery_compass",category:"recipe",name:"Recovery Compass",description:"8 echo shards around a compass.",tags:["recipe","crafting","navigation"] },
];

const biomes = () => [
  { id:"minecraft:plains",category:"biome",name:"Plains",description:"Flat grasslands with scattered trees and villages.",tags:["biome"] },
  { id:"minecraft:forest",category:"biome",name:"Forest",description:"Overworld biome with many oak and birch trees.",tags:["biome"] },
  { id:"minecraft:dark_forest",category:"biome",name:"Dark Forest",description:"Dense forest with dark oak trees. Woodland mansions spawn here.",tags:["biome"] },
  { id:"minecraft:birch_forest",category:"biome",name:"Birch Forest",description:"Forest dominated by birch trees.",tags:["biome"] },
  { id:"minecraft:flower_forest",category:"biome",name:"Flower Forest",description:"Forest with many flowers and fewer trees.",tags:["biome"] },
  { id:"minecraft:taiga",category:"biome",name:"Taiga",description:"Cold forest with spruce trees, foxes, and wolves.",tags:["biome"] },
  { id:"minecraft:snowy_taiga",category:"biome",name:"Snowy Taiga",description:"Cold taiga covered in snow.",tags:["biome"] },
  { id:"minecraft:old_growth_pine_taiga",category:"biome",name:"Old Growth Pine Taiga",description:"Taiga with giant spruce trees and podzol.",tags:["biome"] },
  { id:"minecraft:old_growth_spruce_taiga",category:"biome",name:"Old Growth Spruce Taiga",description:"Taiga with giant spruce trees.",tags:["biome"] },
  { id:"minecraft:jungle",category:"biome",name:"Jungle",description:"Dense tropical biome with tall trees, vines, and temples.",tags:["biome"] },
  { id:"minecraft:bamboo_jungle",category:"biome",name:"Bamboo Jungle",description:"Jungle variant filled with bamboo and pandas.",tags:["biome"] },
  { id:"minecraft:sparse_jungle",category:"biome",name:"Sparse Jungle",description:"Sparse jungle variant.",tags:["biome"] },
  { id:"minecraft:swamp",category:"biome",name:"Swamp",description:"Wet biome with shallow water, oak trees, and witch huts.",tags:["biome"] },
  { id:"minecraft:mangrove_swamp",category:"biome",name:"Mangrove Swamp",description:"Swamp with mangrove trees, mud, and frogs.",tags:["biome"] },
  { id:"minecraft:desert",category:"biome",name:"Desert",description:"Dry biome with sand, cacti, and desert pyramids.",tags:["biome"] },
  { id:"minecraft:savanna",category:"biome",name:"Savanna",description:"Warm grassland with acacia trees and villages.",tags:["biome"] },
  { id:"minecraft:windswept_hills",category:"biome",name:"Windswept Hills",description:"Hilly terrain with extreme height variation.",tags:["biome"] },
  { id:"minecraft:windswept_gravelly_hills",category:"biome",name:"Windswept Gravelly Hills",description:"Hills covered in gravel.",tags:["biome"] },
  { id:"minecraft:windswept_forest",category:"biome",name:"Windswept Forest",description:"Forested hilly terrain.",tags:["biome"] },
  { id:"minecraft:windswept_savanna",category:"biome",name:"Windswept Savanna",description:"Savanna with extreme terrain and floating islands.",tags:["biome"] },
  { id:"minecraft:badlands",category:"biome",name:"Badlands",description:"Dry biome with terracotta and gold ore.",tags:["biome"] },
  { id:"minecraft:wooded_badlands",category:"biome",name:"Wooded Badlands",description:"Badlands with patches of oak trees.",tags:["biome"] },
  { id:"minecraft:eroded_badlands",category:"biome",name:"Eroded Badlands",description:"Badlands with eroded tall pillars.",tags:["biome"] },
  { id:"minecraft:meadow",category:"biome",name:"Meadow",description:"High-altitude grassy plain with flowers and rabbits.",tags:["biome"] },
  { id:"minecraft:cherry_grove",category:"biome",name:"Cherry Grove",description:"Mountain biome with cherry trees and pink petals.",tags:["biome","decorative"] },
  { id:"minecraft:grove",category:"biome",name:"Grove",description:"Snowy forest on mountain slopes.",tags:["biome"] },
  { id:"minecraft:snowy_slopes",category:"biome",name:"Snowy Slopes",description:"Cold mountain slopes with goats.",tags:["biome"] },
  { id:"minecraft:jagged_peaks",category:"biome",name:"Jagged Peaks",description:"High mountain peaks of stone and snow.",tags:["biome"] },
  { id:"minecraft:frozen_peaks",category:"biome",name:"Frozen Peaks",description:"High mountain peaks covered in ice.",tags:["biome"] },
  { id:"minecraft:stony_peaks",category:"biome",name:"Stony Peaks",description:"High mountain peaks of stone and calcite.",tags:["biome"] },
  { id:"minecraft:beach",category:"biome",name:"Beach",description:"Sandy area between oceans and land.",tags:["biome"] },
  { id:"minecraft:snowy_beach",category:"biome",name:"Snowy Beach",description:"Cold beach covered in snow.",tags:["biome"] },
  { id:"minecraft:stony_shore",category:"biome",name:"Stony Shore",description:"Rocky shore without sand.",tags:["biome"] },
  { id:"minecraft:river",category:"biome",name:"River",description:"Long stretches of water through the Overworld.",tags:["biome"] },
  { id:"minecraft:frozen_river",category:"biome",name:"Frozen River",description:"River covered in ice.",tags:["biome"] },
  { id:"minecraft:ocean",category:"biome",name:"Ocean",description:"Large saltwater biome with fish, kelp, and shipwrecks.",tags:["biome"] },
  { id:"minecraft:deep_ocean",category:"biome",name:"Deep Ocean",description:"Deeper ocean variant with ocean monuments.",tags:["biome"] },
  { id:"minecraft:warm_ocean",category:"biome",name:"Warm Ocean",description:"Ocean with coral reefs and tropical fish.",tags:["biome"] },
  { id:"minecraft:lukewarm_ocean",category:"biome",name:"Lukewarm Ocean",description:"Ocean between warm and cold.",tags:["biome"] },
  { id:"minecraft:cold_ocean",category:"biome",name:"Cold Ocean",description:"Cold ocean with cod.",tags:["biome"] },
  { id:"minecraft:frozen_ocean",category:"biome",name:"Frozen Ocean",description:"Ocean with icebergs and polar bears.",tags:["biome"] },
  { id:"minecraft:deep_lukewarm_ocean",category:"biome",name:"Deep Lukewarm Ocean",description:"Deep variant of lukewarm ocean.",tags:["biome"] },
  { id:"minecraft:deep_cold_ocean",category:"biome",name:"Deep Cold Ocean",description:"Deep variant of cold ocean.",tags:["biome"] },
  { id:"minecraft:deep_frozen_ocean",category:"biome",name:"Deep Frozen Ocean",description:"Deep variant of frozen ocean.",tags:["biome"] },
  { id:"minecraft:mushroom_fields",category:"biome",name:"Mushroom Fields",description:"Rare biome with mooshrooms. No hostile mobs.",tags:["biome"] },
  { id:"minecraft:dripstone_caves",category:"biome",name:"Dripstone Caves",description:"Underground biome with pointed dripstone.",tags:["biome"] },
  { id:"minecraft:lush_caves",category:"biome",name:"Lush Caves",description:"Underground biome with moss, azalea, and glow berries.",tags:["biome"] },
  { id:"minecraft:deep_dark",category:"biome",name:"Deep Dark",description:"Deep cave biome with sculk and the warden.",tags:["biome"] },
  { id:"minecraft:nether_wastes",category:"biome",name:"Nether Wastes",description:"Main Nether biome with netherrack, lava, and ghasts.",tags:["biome"] },
  { id:"minecraft:soul_sand_valley",category:"biome",name:"Soul Sand Valley",description:"Nether biome with soul sand and skeletons.",tags:["biome"] },
  { id:"minecraft:crimson_forest",category:"biome",name:"Crimson Forest",description:"Nether forest with hoglins and piglins.",tags:["biome"] },
  { id:"minecraft:warped_forest",category:"biome",name:"Warped Forest",description:"Nether forest with endermen.",tags:["biome"] },
  { id:"minecraft:basalt_deltas",category:"biome",name:"Basalt Deltas",description:"Nether biome with basalt and magma cubes.",tags:["biome"] },
  { id:"minecraft:the_end",category:"biome",name:"The End",description:"Dimension of floating islands and the Ender Dragon.",tags:["biome"] },
  { id:"minecraft:end_highlands",category:"biome",name:"End Highlands",description:"Outer End islands with chorus plants and end cities.",tags:["biome"] },
  { id:"minecraft:end_midlands",category:"biome",name:"End Midlands",description:"Transition area between central End and outer islands.",tags:["biome"] },
  { id:"minecraft:end_barrens",category:"biome",name:"End Barrens",description:"Empty outer End areas.",tags:["biome"] },
  { id:"minecraft:small_end_islands",category:"biome",name:"Small End Islands",description:"Small outer islands past the void.",tags:["biome"] },
];

const strategy = () => [
  { id:"strategy:mining",category:"strategy",name:"Mining",description:"Dig down carefully with torches and food. Avoid digging straight down.",tags:["strategy"] },
  { id:"strategy:strip_mining",category:"strategy",name:"Strip Mining",description:"Mine long tunnels at Y=-59 for diamonds. Torches every 10 blocks. Watch for lava.",tags:["strategy"] },
  { id:"strategy:caving",category:"strategy",name:"Caving",description:"Explore natural caves for exposed ores. Bring torches, food, and armor.",tags:["strategy"] },
  { id:"strategy:nether_exploration",category:"strategy",name:"Nether Exploration",description:"Wear gold armor around piglins. Bring fire resistance. Build paths over lava.",tags:["strategy"] },
  { id:"strategy:nether_fortress_route",category:"strategy",name:"Nether Fortress Route",description:"Follow the x-axis. Fortresses generate perpendicular to x-axis.",tags:["strategy","nether"] },
  { id:"strategy:nether_safe_travel",category:"strategy",name:"Nether Safe Travel",description:"Build tunnels with slabs to prevent spawns. Use warped fungi for striders.",tags:["strategy","nether"] },
  { id:"strategy:end_fight",category:"strategy",name:"Ender Dragon Fight",description:"Destroy crystals with arrows or pillars. Attack the dragon when it perches.",tags:["strategy"] },
  { id:"strategy:end_city_raiding",category:"strategy",name:"End City Raiding",description:"Bridge to outer islands. Find the ship for elytra. Watch for shulkers.",tags:["strategy","end"] },
  { id:"strategy:wither_fight",category:"strategy",name:"Wither Fight",description:"Fight underground in a confined space. Use smite enchantment.",tags:["strategy"] },
  { id:"strategy:warden_avoid",category:"strategy",name:"Warden Avoidance",description:"Move slowly in the deep dark. Wool blocks vibrations. Distract with snowballs.",tags:["strategy"] },
  { id:"strategy:villager_trading",category:"strategy",name:"Villager Trading",description:"Protect villagers. Give job blocks. Cure zombie villagers for discounts.",tags:["strategy"] },
  { id:"strategy:villager_breedering",category:"strategy",name:"Villager Breeder",description:"Build with beds, workstations, and food. Villagers with beds breed.",tags:["strategy","village"] },
  { id:"strategy:villager_zombie_cure",category:"strategy",name:"Zombie Villager Cure",description:"Splash weakness, feed golden apple. Wait 2-5 min for discounted trades.",tags:["strategy","village"] },
  { id:"strategy:farming",category:"strategy",name:"Farming",description:"Plant on hydrated farmland. Use bonemeal. Keep light level high.",tags:["strategy"] },
  { id:"strategy:automated_farm",category:"strategy",name:"Automated Farm",description:"Use water to collect crops. Observer + piston for automatic harvesting.",tags:["strategy","farming"] },
  { id:"strategy:animal_farming",category:"strategy",name:"Animal Farming",description:"Breed animals with their food. Keep in pens with water.",tags:["strategy"] },
  { id:"strategy:honey_farming",category:"strategy",name:"Honey Farming",description:"Use shears for honeycomb, bottles for honey. Campfire under hive pacifies bees.",tags:["strategy","farming"] },
  { id:"strategy:defense",category:"strategy",name:"Base Defense",description:"Light the area. Build walls. Use iron golems and traps.",tags:["strategy"] },
  { id:"strategy:mob_grinder",category:"strategy",name:"Mob Grinder",description:"Build a dark tower with water channels. Mobs fall to killing chamber.",tags:["strategy","combat"] },
  { id:"strategy:raids",category:"strategy",name:"Raid Defense",description:"Ring a bell to reveal raiders. Walls and ranged attacks. Heal between waves.",tags:["strategy"] },
  { id:"strategy:exploration",category:"strategy",name:"Exploration",description:"Bring food, torches, a bed, and a compass. Mark your path.",tags:["strategy"] },
  { id:"strategy:combat",category:"strategy",name:"Combat Basics",description:"Equip weapon and armor. Strafe. Retreat when low on health.",tags:["strategy"] },
  { id:"strategy:enchanting",category:"strategy",name:"Enchanting",description:"Bookshelves around the table. Anvil to combine enchanted books.",tags:["strategy"] },
  { id:"strategy:brewing",category:"strategy",name:"Brewing",description:"Brewing stand. Nether wart is the base ingredient.",tags:["strategy"] },
  { id:"strategy:potion_brewing",category:"strategy",name:"Potion Brewing Guide",description:"Nether wart + water bottle = awkward potion. Add effect ingredient. Redstone for duration, glowstone for potency. Gunpowder for splash.",tags:["strategy","brewing"] },
  { id:"strategy:smelting",category:"strategy",name:"Smelting",description:"Use furnaces for everything, blast furnaces for ores, smokers for food.",tags:["strategy"] },
  { id:"strategy:redstone",category:"strategy",name:"Redstone Basics",description:"Power with redstone dust, torches, repeaters. Observers detect changes.",tags:["strategy"] },
  { id:"strategy:redstone_clock",category:"strategy",name:"Redstone Clock",description:"Repeater loop or observer loop for a repeating signal.",tags:["strategy","redstone"] },
  { id:"strategy:redstone_item_sorter",category:"strategy",name:"Item Sorter",description:"Hoppers and comparators sort items by type into different chests.",tags:["strategy","redstone"] },
  { id:"strategy:building",category:"strategy",name:"Building",description:"Plan foundations and storage. Use scaffolding. Light interiors.",tags:["strategy"] },
  { id:"strategy:automation",category:"strategy",name:"Automation",description:"Hoppers, droppers, dispensers, and observers automate farms and sorting.",tags:["strategy"] },
  { id:"strategy:speedrun",category:"strategy",name:"Speedrun",description:"Focus on wood, tools, iron, flint and steel, beds, and eyes of ender.",tags:["strategy"] },
  { id:"strategy:speedrun_route",category:"strategy",name:"Speedrun Route",description:"Get wood -> stone pick -> iron pick -> portal -> fortress -> bed kills blazes -> pearls from bartering -> eyes -> stronghold -> end.",tags:["strategy","speedrun"] },
  { id:"strategy:resource_management",category:"strategy",name:"Resource Management",description:"Labeled chests for storage. Backup tools. Shulker boxes for travel.",tags:["strategy"] },
  { id:"strategy:preparation",category:"strategy",name:"Preparation",description:"Before a big task, gather food, tools, armor, blocks, potions, and set spawn.",tags:["strategy"] },
  { id:"strategy:recovery",category:"strategy",name:"Recovery",description:"After death, retrieve items before re-engaging threats.",tags:["strategy"] },
  { id:"strategy:multiplayer",category:"strategy",name:"Multiplayer",description:"Coordinate roles, share resources, establish safe zones.",tags:["strategy"] },
  { id:"strategy:starter_guide",category:"strategy",name:"First Day Guide",description:"Punch tree -> craft wood pick -> mine 19 stone -> stone tools -> furnace -> shelter before night.",tags:["strategy","early"] },
  { id:"strategy:early_iron",category:"strategy",name:"Getting Iron Early",description:"Find a cave or dig to Y=16. Iron generates between Y=-64 and Y=72.",tags:["strategy","mining"] },
  { id:"strategy:emergency_kits",category:"strategy",name:"Emergency Kit",description:"Carry backup tools, food, blocks, water bucket, and bed in ender chest.",tags:["strategy","preparation"] },
  { id:"strategy:bartering",category:"strategy",name:"Piglin Bartering",description:"Drop gold ingots near piglins. They give pearls, obsidian, fire resistance. Wear gold armor.",tags:["strategy","nether"] },
  { id:"strategy:bridging",category:"strategy",name:"Safe Bridging",description:"Walk backward while placing. Use scaffolding. Sneak at edges.",tags:["strategy","building"] },
  { id:"strategy:water_elevator",category:"strategy",name:"Water Elevator",description:"Kelp makes bubble columns. Soul sand pushes up, magma pushes down.",tags:["strategy","building"] },
  { id:"strategy:tree_farm",category:"strategy",name:"Tree Farming",description:"Plant saplings with 4+ blocks above. Oak needs less space.",tags:["strategy","farming"] },
  { id:"strategy:beacon_usage",category:"strategy",name:"Beacon Pyramid",description:"Build a pyramid of mineral blocks. Full 4-layer = 164 blocks. Gives Haste, Speed, etc.",tags:["strategy"] },
  { id:"strategy:safe_mining",category:"strategy",name:"Safe Mining",description:"Never dig straight down. Light up caves. Torches on left wall to find way back.",tags:["strategy","mining"] },
  { id:"strategy:raid_farm",category:"strategy",name:"Raid Farm",description:"Killer chamber with pillager spawner. Obtain totems and emeralds from waves.",tags:["strategy","combat"] },
  { id:"strategy:shulker_box_usage",category:"strategy",name:"Shulker Box Storage",description:"Portable storage. Keeps items when broken. Color-code for organization.",tags:["strategy","end","storage"] },
  { id:"strategy:explosive_mining",category:"strategy",name:"Explosive Mining",description:"Use beds in the Nether for ancient debris. TNT also works underground.",tags:["strategy","mining","nether"] },
  { id:"strategy:crop_automation",category:"strategy",name:"Crop Automation",description:"Observers detect growth. Pistons harvest. Waterlogged blocks replace water.",tags:["strategy","farming","redstone"] },
];

write("blocks.json", blocks());
write("mobs.json", mobs());
write("items.json", items());
write("recipes.json", recipes());
write("biomes.json", biomes());
write("strategy.json", strategy());
