#!/usr/bin/env python3
"""Generate expanded knowledge JSON files for SmithAI (700+ entries)."""
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "SmithAI" / "src" / "main" / "resources" / "knowledge"

def write(name, data):
    path = ROOT / name
    os.makedirs(path.parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"Wrote {len(data)} entries to {path}")

def entry(id, category, name, desc, tags):
    return {"id": id, "category": category, "name": name, "description": desc, "tags": tags}

def blocks():
    E = lambda id, name, desc, tags: entry(id, "block", name, desc, tags)
    return [
        E("minecraft:stone","Stone","A common solid block found underground. Mined fastest with a pickaxe. Drops cobblestone unless mined with Silk Touch.","block mining building".split()),
        E("minecraft:cobblestone","Cobblestone","Dropped when mining stone without Silk Touch. Used for tools, furnaces, and building.","block mining building".split()),
        E("minecraft:granite","Granite","An igneous rock variant of stone. Can be polished for decorative building.","block mining building decorative".split()),
        E("minecraft:diorite","Diorite","A white stone variant. Can be polished for decorative use.","block mining building decorative".split()),
        E("minecraft:andesite","Andesite","A gray stone variant. Can be polished for decorative building.","block mining building decorative".split()),
        E("minecraft:tuff","Tuff","A light gray rock found near deepslate. Used for decorative building.","block mining building decorative".split()),
        E("minecraft:calcite","Calcite","A white mineral block found in geode layers. Used for decorative building.","block mining building decorative".split()),
        E("minecraft:deepslate","Deepslate","A dark stone variant found deep underground. Harder than stone and used for building.","block mining building deep".split()),
        E("minecraft:cobbled_deepslate","Cobbled Deepslate","Drops from mining deepslate. Used for tools and building.","block mining building".split()),
        E("minecraft:reinforced_deepslate","Reinforced Deepslate","Indestructible block found in the deep dark near the warden. Cannot be mined.","block indestructible deep".split()),
        E("minecraft:bedrock","Bedrock","An indestructible block found at the bottom of the world and in the End and Nether roofs.","block indestructible".split()),
        E("minecraft:dirt","Dirt","A common surface block. Can be tilled into farmland with a hoe.","block dirt farming".split()),
        E("minecraft:grass_block","Grass Block","Dirt covered in grass. Common in the Overworld surface. Can be silk-touched.","block dirt grass".split()),
        E("minecraft:mycelium","Mycelium","Dirt covered in fungus. Found in mushroom fields. Great for growing mushrooms.","block dirt mushroom".split()),
        E("minecraft:podzol","Podzol","Dirt covered in pine needles. Found in old-growth taiga.","block dirt taiga building".split()),
        E("minecraft:coarse_dirt","Coarse Dirt","Dirt that cannot be tilled. Crafted from dirt and gravel.","block dirt building".split()),
        E("minecraft:rooted_dirt","Rooted Dirt","Dirt with roots under azalea trees. Can be converted to dirt.","block dirt roots".split()),
        E("minecraft:mud","Mud","Found in mangrove swamps. Can be packed into mud bricks or combined with wheat into packed mud.","block mud swamp".split()),
        E("minecraft:clay","Clay","Found underwater in rivers and lakes. Smelt into bricks or terracotta.","block clay water".split()),
        E("minecraft:terracotta","Terracotta","A hardened clay block found in Badlands. Can be dyed into colored variants.","block building decorative".split()),
        E("minecraft:white_terracotta","White Terracotta","Dyed terracotta. Used for decorative building.","block building decorative".split()),
        E("minecraft:iron_ore","Iron Ore","Iron ore is found underground, usually between Y=-64 and Y=72. Requires a stone pickaxe or better. Smelt it to get iron ingots.","block mining ore iron".split()),
        E("minecraft:deepslate_iron_ore","Deepslate Iron Ore","Iron ore embedded in deepslate. Requires a stone pickaxe or better. Drops iron ore.","block mining ore iron".split()),
        E("minecraft:gold_ore","Gold Ore","Gold ore found around Y=-16 and abundantly in Badlands. Requires an iron pickaxe or better.","block mining ore gold".split()),
        E("minecraft:deepslate_gold_ore","Deepslate Gold Ore","Gold ore embedded in deepslate. Requires an iron pickaxe or better.","block mining ore gold".split()),
        E("minecraft:diamond_ore","Diamond Ore","Diamond ore is found deep underground, most commonly around Y=-59. Requires an iron pickaxe or better.","block mining ore diamond".split()),
        E("minecraft:deepslate_diamond_ore","Deepslate Diamond Ore","Diamond ore embedded in deepslate. Requires an iron pickaxe or better.","block mining ore diamond".split()),
        E("minecraft:coal_ore","Coal Ore","Coal ore is common underground and in mountains. Mined with any pickaxe. Drops coal for torches and fuel.","block mining ore coal fuel".split()),
        E("minecraft:deepslate_coal_ore","Deepslate Coal Ore","Coal ore embedded in deepslate. Mined with any pickaxe.","block mining ore coal fuel".split()),
        E("minecraft:redstone_ore","Redstone Ore","Redstone ore is found deep underground. Requires an iron pickaxe or better. Drops redstone dust.","block mining ore redstone".split()),
        E("minecraft:deepslate_redstone_ore","Deepslate Redstone Ore","Redstone ore embedded in deepslate.","block mining ore redstone".split()),
        E("minecraft:lapis_ore","Lapis Lazuli Ore","Lapis ore is found underground. Requires a stone pickaxe or better. Drops lapis lazuli.","block mining ore lapis".split()),
        E("minecraft:deepslate_lapis_ore","Deepslate Lapis Ore","Lapis ore embedded in deepslate.","block mining ore lapis".split()),
        E("minecraft:copper_ore","Copper Ore","Copper ore generates in larger ore blobs underground. Requires a stone pickaxe or better.","block mining ore copper".split()),
        E("minecraft:deepslate_copper_ore","Deepslate Copper Ore","Copper ore embedded in deepslate.","block mining ore copper".split()),
        E("minecraft:emerald_ore","Emerald Ore","Emerald ore is found in mountain biomes. Requires an iron pickaxe or better.","block mining ore emerald".split()),
        E("minecraft:deepslate_emerald_ore","Deepslate Emerald Ore","Emerald ore embedded in deepslate.","block mining ore emerald".split()),
        E("minecraft:nether_gold_ore","Nether Gold Ore","Gold ore found in the Nether. Drops gold nuggets when mined.","block nether mining ore gold".split()),
        E("minecraft:nether_quartz_ore","Nether Quartz Ore","Quartz ore found in the Nether. Drops nether quartz.","block nether mining ore quartz".split()),
        E("minecraft:ancient_debris","Ancient Debris","Rare ore found deep in the Nether. Smelted into netherite scrap. Blast-resistant.","block nether mining ore netherite".split()),
        E("minecraft:raw_iron_block","Block of Raw Iron","A compact block of raw iron. Can be smelted directly.","block ore metal storage".split()),
        E("minecraft:raw_gold_block","Block of Raw Gold","A compact block of raw gold.","block ore metal storage".split()),
        E("minecraft:raw_copper_block","Block of Raw Copper","A compact block of raw copper.","block ore metal storage".split()),
        E("minecraft:obsidian","Obsidian","Created when water touches a lava source. Requires a diamond or netherite pickaxe. Used for nether portals and enchanting tables.","block mining portal enchanting".split()),
        E("minecraft:crying_obsidian","Crying Obsidian","A decorative obsidian variant that emits purple particles. Used to craft respawn anchors.","block nether portal decorative".split()),
        E("minecraft:glowstone","Glowstone","A bright light source found in the Nether. Drops glowstone dust.","block light nether".split()),
        E("minecraft:shroomlight","Shroomlight","A light-emitting block found in nether forests.","block light nether".split()),
        E("minecraft:ochre_froglight","Ochre Froglight","A warm yellow light block dropped by frogs eating small magma cubes.","block light decorative".split()),
        E("minecraft:verdant_froglight","Verdant Froglight","A green light block dropped by frogs eating small magma cubes.","block light decorative".split()),
        E("minecraft:pearlescent_froglight","Pearlescent Froglight","A purple light block dropped by frogs eating small magma cubes.","block light decorative".split()),
        E("minecraft:crafting_table","Crafting Table","Expands the crafting grid to 3x3. Crafted from 4 wooden planks.","block crafting".split()),
        E("minecraft:furnace","Furnace","Smelts ores, food, and other items using fuel. Crafted from 8 cobblestone.","block smelting fuel".split()),
        E("minecraft:blast_furnace","Blast Furnace","Smelts ores and metal items twice as fast as a furnace.","block smelting ore".split()),
        E("minecraft:smoker","Smoker","Cooks food twice as fast as a furnace. Crafted from a furnace and logs.","block smelting food".split()),
        E("minecraft:chest","Chest","Stores up to 27 stacks of items. Crafted from 8 wooden planks.","block storage".split()),
        E("minecraft:trapped_chest","Trapped Chest","A chest that emits a redstone signal when opened.","block storage redstone".split()),
        E("minecraft:ender_chest","Ender Chest","A chest whose contents are shared across all ender chests. Crafted from obsidian and an eye of ender.","block storage end".split()),
        E("minecraft:barrel","Barrel","A storage block that can be opened even when blocks are placed on top.","block storage".split()),
        E("minecraft:enchanting_table","Enchanting Table","Used to enchant tools, weapons, and armor. Requires obsidian, diamonds, and a book.","block enchanting".split()),
        E("minecraft:anvil","Anvil","Used to repair, rename, and combine enchanted items.","block repair enchanting".split()),
        E("minecraft:grindstone","Grindstone","Used to repair tools or remove enchantments. Returns some experience.","block repair enchanting".split()),
        E("minecraft:stonecutter","Stonecutter","Cuts stone blocks into slabs and stairs more efficiently than crafting.","block building crafting".split()),
        E("minecraft:loom","Loom","Used to apply patterns to banners.","block crafting decorative".split()),
        E("minecraft:smithing_table","Smithing Table","Used to upgrade diamond gear to netherite with netherite ingots.","block crafting netherite".split()),
        E("minecraft:cartography_table","Cartography Table","Used to clone, expand, and lock maps.","block crafting navigation".split()),
        E("minecraft:composter","Composter","Converts crops and plants into bone meal.","block farming".split()),
        E("minecraft:lectern","Lectern","Holds books for multiple players to read. Emits a redstone signal.","block redstone storage".split()),
        E("minecraft:torch","Torch","Provides light and melts snow nearby. Crafted from coal and a stick.","block light torch".split()),
        E("minecraft:soul_torch","Soul Torch","A blue torch that emits less light. Crafted from a torch and soul soil or soul sand.","block light soul_fire".split()),
        E("minecraft:lantern","Lantern","A brighter light source than a torch. Crafted from iron nuggets and a torch.","block light".split()),
        E("minecraft:soul_lantern","Soul Lantern","A blue lantern variant. Crafted from a lantern and soul soil or soul sand.","block light soul_fire".split()),
        E("minecraft:jack_o_lantern","Jack o'Lantern","A carved pumpkin with a torch inside. Emits light.","block light decorative".split()),
        E("minecraft:sea_lantern","Sea Lantern","A bright underwater light source found in ocean monuments.","block light water".split()),
        E("minecraft:redstone_lamp","Redstone Lamp","A lamp that lights up when powered by redstone.","block light redstone".split()),
        E("minecraft:oak_log","Oak Log","Wood from oak trees. Can be crafted into planks and sticks.","block wood building".split()),
        E("minecraft:spruce_log","Spruce Log","Wood from spruce trees. Crafted into dark-colored planks.","block wood building".split()),
        E("minecraft:birch_log","Birch Log","Light-colored wood from birch trees.","block wood building".split()),
        E("minecraft:jungle_log","Jungle Log","Wood from jungle trees.","block wood building".split()),
        E("minecraft:acacia_log","Acacia Log","Wood from acacia trees. Crafted into reddish planks.","block wood building".split()),
        E("minecraft:dark_oak_log","Dark Oak Log","Wood from dark oak trees. Crafted into dark planks.","block wood building".split()),
        E("minecraft:mangrove_log","Mangrove Log","Wood from mangrove trees found in mangrove swamps.","block wood building".split()),
        E("minecraft:cherry_log","Cherry Log","Pink-tinted wood from cherry trees. Crafted into pink planks.","block wood building decorative".split()),
        E("minecraft:crimson_stem","Crimson Stem","The wood of crimson fungi in the Nether. Not flammable.","block wood nether building".split()),
        E("minecraft:warped_stem","Warped Stem","The wood of warped fungi in the Nether. Not flammable.","block wood nether building".split()),
        E("minecraft:oak_planks","Oak Planks","Basic wooden planks. Used for crafting, sticks, and building.","block wood building".split()),
        E("minecraft:glass","Glass","Transparent block made by smelting sand. Used for windows and bottles.","block glass building".split()),
        E("minecraft:glass_pane","Glass Pane","Thin glass that connects to adjacent panes.","block glass building".split()),
        E("minecraft:white_stained_glass","White Stained Glass","Colored glass.","block glass building decorative".split()),
        E("minecraft:sand","Sand","A gravity-affected block found in deserts and beaches. Smelt into glass.","block sand glass".split()),
        E("minecraft:red_sand","Red Sand","A red variant of sand found in Badlands biomes.","block sand badlands".split()),
        E("minecraft:suspicious_sand","Suspicious Sand","Sand containing buried treasure. Found in desert temples and wells.","block sand treasure".split()),
        E("minecraft:suspicious_gravel","Suspicious Gravel","Gravel containing buried treasure. Found in cold ocean ruins.","block gravel treasure".split()),
        E("minecraft:gravel","Gravel","A gravity-affected block found underground and on beaches. Drops flint occasionally.","block gravel flint".split()),
        E("minecraft:snow","Snow","A thin layer of snow on the ground.","block cold".split()),
        E("minecraft:snow_block","Snow Block","A full block of snow. Crafted from snowballs.","block cold building".split()),
        E("minecraft:ice","Ice","Slippery block that melts in light. Turns water source blocks into ice.","block cold water".split()),
        E("minecraft:packed_ice","Packed Ice","Solid ice block that does not melt. Slippery for fast travel.","block cold building".split()),
        E("minecraft:blue_ice","Blue Ice","Very dense ice. Useful for fast boats in water.","block cold building".split()),
        E("minecraft:netherrack","Netherrack","The main stone of the Nether. Burns indefinitely when lit.","block nether building".split()),
        E("minecraft:soul_sand","Soul Sand","Slows movement. Used for nether wart farms and soul fire.","block nether soul_fire".split()),
        E("minecraft:soul_soil","Soul Soil","Found in soul sand valleys. Used to create soul fire.","block nether".split()),
        E("minecraft:blackstone","Blackstone","A dark stone found in Bastion Remnants. Can substitute stone in recipes.","block nether building".split()),
        E("minecraft:gilded_blackstone","Gilded Blackstone","Blackstone that may drop gold nuggets when mined. Found in Bastions.","block nether ore gold".split()),
        E("minecraft:basalt","Basalt","A dark pillar-like block found in the Nether. Can be polished.","block nether building".split()),
        E("minecraft:smooth_basalt","Smooth Basalt","Polished basalt.","block nether building".split()),
        E("minecraft:polished_blackstone","Polished Blackstone","The polished form of blackstone.","block nether building decorative".split()),
        E("minecraft:end_stone","End Stone","The main block of the End islands.","block end building".split()),
        E("minecraft:end_stone_bricks","End Stone Bricks","A decorative variant of end stone.","block end building decorative".split()),
        E("minecraft:purpur_block","Purpur Block","A decorative block from End cities. Crafted from popped chorus fruit.","block end building decorative".split()),
        E("minecraft:purpur_pillar","Purpur Pillar","A pillar variant of purpur.","block end building decorative".split()),
        E("minecraft:prismarine","Prismarine","A sea-themed block found in ocean monuments.","block water ocean".split()),
        E("minecraft:prismarine_bricks","Prismarine Bricks","A brick variant of prismarine.","block water ocean building".split()),
        E("minecraft:dark_prismarine","Dark Prismarine","A dark variant of prismarine.","block water ocean building".split()),
        E("minecraft:sea_lantern","Sea Lantern","Bright light block from ocean monuments.","block light water".split()),
        E("minecraft:sponge","Sponge","Absorbs water in a 7-block radius. Can be dried in a furnace.","block water sponge".split()),
        E("minecraft:wet_sponge","Wet Sponge","A waterlogged sponge. Dry in a furnace.","block water sponge".split()),
        E("minecraft:melon","Melon","Grows from melon seeds. Drops melon slices.","block farming food".split()),
        E("minecraft:pumpkin","Pumpkin","Grows from pumpkin seeds. Used for decoration and golems.","block farming decorative".split()),
        E("minecraft:carved_pumpkin","Carved Pumpkin","A pumpkin with a face carved in. Used for golems and wearing as a helmet.","block decorative".split()),
        E("minecraft:hay_bale","Hay Bale","A compact block of wheat. Can be fed to horses and used as fuel.","block farming fuel storage".split()),
        E("minecraft:dried_kelp_block","Dried Kelp Block","A fuel block smelted from dried kelp.","block fuel".split()),
        E("minecraft:honey_block","Honey Block","A sticky block that slows movement. Entities slide off surfaces.","block redstone sticky".split()),
        E("minecraft:honeycomb_block","Honeycomb Block","A decorative block crafted from honeycombs.","block building decorative".split()),
        E("minecraft:beehive","Beehive","A home for bees. Can be harvested for honey and honeycomb.","block farming".split()),
        E("minecraft:bee_nest","Bee Nest","A naturally generated bee home in flower forests and meadows.","block farming".split()),
        E("minecraft:cactus","Cactus","A desert plant that damages entities on contact.","block desert plant".split()),
        E("minecraft:sugar_cane","Sugar Cane","Grows near water. Used for sugar and paper.","block farming plant".split()),
        E("minecraft:bamboo","Bamboo","Fast-growing plant found in jungles. Used for scaffolding and fuel.","block farming plant".split()),
        E("minecraft:vine","Vines","Climbable vines found in jungles and swamps.","block plant".split()),
        E("minecraft:twisting_vines","Twisting Vines","Climbable vines found in warped forests.","block nether plant".split()),
        E("minecraft:weeping_vines","Weeping Vines","Vines growing downward from crimson forests.","block nether plant".split()),
        E("minecraft:sculk","Sculk","A block that spreads by consuming experience. Found in the deep dark.","block deep redstone".split()),
        E("minecraft:sculk_catalyst","Sculk Catalyst","A sculk block that spreads sculk when a mob dies nearby.","block deep redstone".split()),
        E("minecraft:sculk_shrieker","Sculk Shrieker","A sculk block that shrieks when triggered. Summons the warden.","block deep redstone".split()),
        E("minecraft:sculk_sensor","Sculk Sensor","A redstone component that detects vibrations.","block deep redstone".split()),
        E("minecraft:calibrated_sculk_sensor","Calibrated Sculk Sensor","A sculk sensor that can filter specific vibration frequencies.","block deep redstone".split()),
        E("minecraft:white_wool","White Wool","Dropped from sheep or crafted from string. Used for beds and decoration.","block wool bed".split()),
        E("minecraft:bookshelf","Bookshelf","Bookshelves around an enchanting table improve enchantment levels.","block enchanting building".split()),
    ]

def mobs():
    E = lambda id, name, desc, tags: entry(id, "mob", name, desc, tags)
    return [
        E("minecraft:zombie","Zombie","A hostile mob that spawns in dark areas. Burns in sunlight and drops rotten flesh.","mob hostile overworld".split()),
        E("minecraft:zombie_villager","Zombie Villager","A villager turned into a zombie. Can be cured with a golden apple and weakness potion.","mob hostile overworld village".split()),
        E("minecraft:drowned","Drowned","Underwater zombie that can spawn with tridents. Drops copper and rotten flesh.","mob hostile water".split()),
        E("minecraft:husk","Husk","Desert zombie variant. Does not burn in sunlight.","mob hostile desert".split()),
        E("minecraft:skeleton","Skeleton","Shoots arrows and burns in sunlight. Drops bones and arrows.","mob hostile overworld ranged".split()),
        E("minecraft:stray","Stray","Skeleton variant found in cold biomes. Shoots arrows of Slowness.","mob hostile cold ranged".split()),
        E("minecraft:wither_skeleton","Wither Skeleton","Spawns in Nether fortresses. Inflicts Wither. Drops coal, bones, and rarely skulls.","mob hostile nether".split()),
        E("minecraft:creeper","Creeper","Silently approaches and explodes. Drops gunpowder.","mob hostile overworld explosive".split()),
        E("minecraft:charged_creeper","Charged Creeper","A creeper struck by lightning. Its explosion has larger radius and drops mob heads.","mob hostile overworld explosive rare".split()),
        E("minecraft:spider","Spider","Hostile at night, neutral in daylight. Climbs walls. Drops string and spider eyes.","mob hostile overworld".split()),
        E("minecraft:cave_spider","Cave Spider","Smaller venomous spider found in mineshafts.","mob hostile overworld poison".split()),
        E("minecraft:enderman","Enderman","Tall mob that teleports and picks up blocks. Aggressive if looked at. Drops ender pearls.","mob hostile overworld end".split()),
        E("minecraft:endermite","Endermite","Small hostile mob that spawns rarely when using ender pearls.","mob hostile".split()),
        E("minecraft:shulker","Shulker","Shell-like mob found in End cities. Fires homing projectiles that inflict levitation.","mob hostile end".split()),
        E("minecraft:witch","Witch","Throws splash potions. Spawns in swamps and raids.","mob hostile overworld ranged".split()),
        E("minecraft:slime","Slime","Spawns in swamps and slime chunks. Splits when killed. Drops slime balls.","mob hostile overworld".split()),
        E("minecraft:magma_cube","Magma Cube","Nether slime variant. Splits when killed. Drops magma cream.","mob hostile nether".split()),
        E("minecraft:phantom","Phantom","Flying mob that attacks players who haven't slept. Drops phantom membrane.","mob hostile overworld flying".split()),
        E("minecraft:blaze","Blaze","Found in Nether fortresses. Shoots fireballs. Drops blaze rods.","mob hostile nether blaze".split()),
        E("minecraft:ghast","Ghast","Flying Nether mob that shoots explosive fireballs. Drops ghast tears and gunpowder.","mob hostile nether ranged".split()),
        E("minecraft:hoglin","Hoglin","Hostile boar-like mob in the Nether. Drops porkchops and leather.","mob hostile nether".split()),
        E("minecraft:zoglin","Zoglin","A zombified Hoglin. Hostile to most mobs and players.","mob hostile nether".split()),
        E("minecraft:piglin","Piglin","Neutral if wearing gold armor. Hostile if attacked. Barters gold ingots.","mob neutral nether".split()),
        E("minecraft:piglin_brute","Piglin Brute","Stronger hostile Piglin variant in Bastion Remnants. Always hostile.","mob hostile nether".split()),
        E("minecraft:ender_dragon","Ender Dragon","The final boss. Lives in the End. Defeat by destroying crystals then attacking.","mob boss end dragon".split()),
        E("minecraft:wither","Wither","A boss spawned with soul sand and skulls. Drops a nether star.","mob boss nether".split()),
        E("minecraft:warden","Warden","Powerful mob spawned by sculk shriekers. Blind but senses vibrations. Avoid if possible.","mob boss deep_dark".split()),
        E("minecraft:iron_golem","Iron Golem","Neutral mob that protects villages. Built from iron blocks and a carved pumpkin.","mob neutral village golem".split()),
        E("minecraft:snow_golem","Snow Golem","Passive mob built from snow blocks and a carved pumpkin. Throws snowballs at hostile mobs.","mob passive golem".split()),
        E("minecraft:villager","Villager","Passive mob that trades items. Lives in villages. Profession changes with job blocks.","mob passive village trading".split()),
        E("minecraft:wandering_trader","Wandering Trader","A villager that spawns randomly and offers rare trades.","mob passive trading".split()),
        E("minecraft:cow","Cow","Passive mob that drops beef and leather. Can be milked with a bucket.","mob passive food farm".split()),
        E("minecraft:pig","Pig","Passive mob that drops porkchops. Can be ridden with a saddle and carrot on a stick.","mob passive food farm".split()),
        E("minecraft:sheep","Sheep","Passive mob that drops wool and mutton. Can be sheared.","mob passive wool farm".split()),
        E("minecraft:chicken","Chicken","Passive mob that drops feathers and raw chicken. Lays eggs.","mob passive food farm".split()),
        E("minecraft:rabbit","Rabbit","Small passive mob that drops rabbit hide, meat, and feet.","mob passive food".split()),
        E("minecraft:mooshroom","Mooshroom","Cow variant on mushroom islands. Milked for stew or milk.","mob passive food mushroom".split()),
        E("minecraft:horse","Horse","Passive mob that can be tamed and ridden.","mob passive transport".split()),
        E("minecraft:donkey","Donkey","Can be tamed, ridden, and equipped with a chest for storage.","mob passive transport storage".split()),
        E("minecraft:mule","Mule","Born from a horse and donkey. Can carry a chest and be ridden.","mob passive transport storage".split()),
        E("minecraft:skeleton_horse","Skeleton Horse","A rideable undead horse. Can be tamed.","mob passive transport".split()),
        E("minecraft:zombie_horse","Zombie Horse","A rare undead horse. Cannot be tamed in survival.","mob passive transport rare".split()),
        E("minecraft:llama","Llama","Passive mob that carries chests and forms caravans.","mob passive transport storage".split()),
        E("minecraft:trader_llama","Trader Llama","Llamas that follow wandering traders.","mob passive transport".split()),
        E("minecraft:wolf","Wolf","Neutral mob that can be tamed with bones.","mob neutral pet combat".split()),
        E("minecraft:cat","Cat","Passive mob tamed with raw fish. Scares creepers and phantoms.","mob passive pet".split()),
        E("minecraft:parrot","Parrot","Passive flying mob that can be tamed and mimics mob sounds.","mob passive pet flying".split()),
        E("minecraft:fox","Fox","Nocturnal passive mob that picks up items. Bred with sweet berries.","mob passive".split()),
        E("minecraft:bee","Bee","Flying passive mob that pollinates crops and produces honey.","mob passive flying farm".split()),
        E("minecraft:bat","Bat","Flying passive mob that spawns in caves. No useful drops.","mob passive flying cave".split()),
        E("minecraft:squid","Squid","Passive water mob that drops ink sacs.","mob passive water".split()),
        E("minecraft:glow_squid","Glow Squid","Passive glowing water mob that drops glow ink sacs.","mob passive water".split()),
        E("minecraft:dolphin","Dolphin","Neutral water mob that boosts swimming and leads to treasure.","mob neutral water".split()),
        E("minecraft:turtle","Turtle","Passive beach mob that lays eggs on sand.","mob passive water beach".split()),
        E("minecraft:polar_bear","Polar Bear","Neutral mob in snowy biomes.","mob neutral cold".split()),
        E("minecraft:panda","Panda","Neutral mob in bamboo jungles. Various personalities.","mob neutral jungle".split()),
        E("minecraft:ocelot","Ocelot","Passive jungle mob. Creepers avoid them even untamed.","mob passive jungle".split()),
        E("minecraft:axolotl","Axolotl","Passive water mob that plays dead. Gives players regeneration when fighting aquatic mobs.","mob passive water".split()),
        E("minecraft:frog","Frog","Passive mob found in swamps. Eats small slimes and magma cubes.","mob passive swamp".split()),
        E("minecraft:tadpole","Tadpole","Baby frog. Grows into a frog. Can be carried in a bucket.","mob passive water".split()),
        E("minecraft:allay","Allay","Flying passive mob that collects items for players. Found near pillager outposts.","mob passive flying".split()),
        E("minecraft:goat","Goat","Neutral mountain mob that rams players.","mob neutral cold".split()),
        E("minecraft:ravager","Ravager","Large hostile mob in raids. Breaks blocks and deals heavy damage.","mob hostile raid".split()),
        E("minecraft:evoker","Evoker","Hostile illager that summons vexes and fangs.","mob hostile illager raid".split()),
        E("minecraft:vindicator","Vindicator","Hostile illager armed with an axe.","mob hostile illager raid".split()),
        E("minecraft:pillager","Pillager","Hostile illager that shoots crossbows.","mob hostile illager raid".split()),
        E("minecraft:vex","Vex","Small hostile flying mob summoned by evokers. Passes through blocks.","mob hostile illager flying".split()),
        E("minecraft:illusioner","Illusioner","Hostile illager that creates illusions and shoots blindness arrows. Has no natural spawn.","mob hostile illager ranged rare".split()),
    ]

def items():
    E = lambda id, name, desc, tags: entry(id, "item", name, desc, tags)
    return [
        E("minecraft:wooden_pickaxe","Wooden Pickaxe","Can mine stone and coal ore. Crafted from 3 planks and 2 sticks.","item tool pickaxe wood".split()),
        E("minecraft:stone_pickaxe","Stone Pickaxe","Can mine iron ore and lapis. Crafted from 3 cobblestone and 2 sticks.","item tool pickaxe stone".split()),
        E("minecraft:iron_pickaxe","Iron Pickaxe","Can mine diamond ore, redstone, and gold. Crafted from 3 iron ingots and 2 sticks.","item tool pickaxe iron".split()),
        E("minecraft:diamond_pickaxe","Diamond Pickaxe","Fast, durable pickaxe. Can mine obsidian. Crafted from 3 diamonds and 2 sticks.","item tool pickaxe diamond".split()),
        E("minecraft:netherite_pickaxe","Netherite Pickaxe","The strongest pickaxe. Upgrade diamond pickaxe with netherite ingot.","item tool pickaxe netherite".split()),
        E("minecraft:wooden_axe","Wooden Axe","Chops wood faster. Crafted from 3 planks and 2 sticks.","item tool axe wood".split()),
        E("minecraft:stone_axe","Stone Axe","Basic axe. Crafted from 3 cobblestone and 2 sticks.","item tool axe stone".split()),
        E("minecraft:iron_axe","Iron Axe","Durable iron axe. Crafted from 3 iron ingots and 2 sticks.","item tool axe iron".split()),
        E("minecraft:diamond_axe","Diamond Axe","Very fast axe. Crafted from 3 diamonds and 2 sticks.","item tool axe diamond".split()),
        E("minecraft:netherite_axe","Netherite Axe","The strongest axe. Upgrade diamond axe with netherite ingot.","item tool axe netherite".split()),
        E("minecraft:wooden_shovel","Wooden Shovel","Basic shovel for dirt and sand.","item tool shovel wood".split()),
        E("minecraft:stone_shovel","Stone Shovel","Better shovel.","item tool shovel stone".split()),
        E("minecraft:iron_shovel","Iron Shovel","Durable shovel.","item tool shovel iron".split()),
        E("minecraft:diamond_shovel","Diamond Shovel","Very fast shovel.","item tool shovel diamond".split()),
        E("minecraft:netherite_shovel","Netherite Shovel","The strongest shovel.","item tool shovel netherite".split()),
        E("minecraft:wooden_hoe","Wooden Hoe","Tills dirt into farmland.","item tool hoe wood".split()),
        E("minecraft:stone_hoe","Stone Hoe","Tills dirt into farmland.","item tool hoe stone".split()),
        E("minecraft:iron_hoe","Iron Hoe","Tills dirt into farmland.","item tool hoe iron".split()),
        E("minecraft:diamond_hoe","Diamond Hoe","Fastest hoe. Can be used as a weapon.","item tool hoe diamond".split()),
        E("minecraft:netherite_hoe","Netherite Hoe","The strongest hoe.","item tool hoe netherite".split()),
        E("minecraft:wooden_sword","Wooden Sword","Lowest tier sword. Crafted from 2 planks and 1 stick.","item weapon sword wood".split()),
        E("minecraft:stone_sword","Stone Sword","Basic sword. Crafted from 2 cobblestone and 1 stick.","item weapon sword stone".split()),
        E("minecraft:iron_sword","Iron Sword","Durable sword. Crafted from 2 iron ingots and 1 stick.","item weapon sword iron".split()),
        E("minecraft:diamond_sword","Diamond Sword","Fast, durable sword. Crafted from 2 diamonds and 1 stick.","item weapon sword diamond".split()),
        E("minecraft:netherite_sword","Netherite Sword","The strongest sword. Upgrade diamond sword with netherite ingot.","item weapon sword netherite".split()),
        E("minecraft:bow","Bow","Ranged weapon that shoots arrows.","item weapon ranged".split()),
        E("minecraft:crossbow","Crossbow","Ranged weapon loaded with arrows or fireworks.","item weapon ranged".split()),
        E("minecraft:arrow","Arrow","Ammo for bows and crossbows.","item weapon ranged ammo".split()),
        E("minecraft:spectral_arrow","Spectral Arrow","Arrow that gives the target the Glowing effect.","item weapon ranged ammo".split()),
        E("minecraft:tipped_arrow","Tipped Arrow","Arrow tipped with a potion effect.","item weapon ranged ammo potion".split()),
        E("minecraft:trident","Trident","A melee and ranged weapon thrown at enemies. Found from drowned.","item weapon water".split()),
        E("minecraft:shield","Shield","Blocks incoming attacks.","item weapon defense".split()),
        E("minecraft:turtle_helmet","Turtle Shell","Helmet that gives water breathing when worn. Crafted from scutes.","item armor water".split()),
        E("minecraft:leather_helmet","Leather Helmet","Basic armor.","item armor leather".split()),
        E("minecraft:leather_chestplate","Leather Chestplate","Basic chest armor.","item armor leather".split()),
        E("minecraft:leather_leggings","Leather Leggings","Basic leg armor.","item armor leather".split()),
        E("minecraft:leather_boots","Leather Boots","Basic foot armor.","item armor leather".split()),
        E("minecraft:chainmail_helmet","Chainmail Helmet","Chain armor helmet. Cannot be crafted.","item armor chain".split()),
        E("minecraft:chainmail_chestplate","Chainmail Chestplate","Chain chestplate.","item armor chain".split()),
        E("minecraft:chainmail_leggings","Chainmail Leggings","Chain leggings.","item armor chain".split()),
        E("minecraft:chainmail_boots","Chainmail Boots","Chain boots.","item armor chain".split()),
        E("minecraft:iron_helmet","Iron Helmet","Iron helmet.","item armor iron".split()),
        E("minecraft:iron_chestplate","Iron Chestplate","Iron chestplate.","item armor iron".split()),
        E("minecraft:iron_leggings","Iron Leggings","Iron leggings.","item armor iron".split()),
        E("minecraft:iron_boots","Iron Boots","Iron boots.","item armor iron".split()),
        E("minecraft:diamond_helmet","Diamond Helmet","Diamond helmet.","item armor diamond".split()),
        E("minecraft:diamond_chestplate","Diamond Chestplate","Diamond chestplate.","item armor diamond".split()),
        E("minecraft:diamond_leggings","Diamond Leggings","Diamond leggings.","item armor diamond".split()),
        E("minecraft:diamond_boots","Diamond Boots","Diamond boots.","item armor diamond".split()),
        E("minecraft:netherite_helmet","Netherite Helmet","Netherite helmet. Best helmet.","item armor netherite".split()),
        E("minecraft:netherite_chestplate","Netherite Chestplate","Netherite chestplate.","item armor netherite".split()),
        E("minecraft:netherite_leggings","Netherite Leggings","Netherite leggings.","item armor netherite".split()),
        E("minecraft:netherite_boots","Netherite Boots","Netherite boots.","item armor netherite".split()),
        E("minecraft:elytra","Elytra","Wings that allow gliding. Found in End ships.","item armor end flying".split()),
        E("minecraft:stick","Stick","Basic crafting material. Crafted from two planks.","item material".split()),
        E("minecraft:iron_ingot","Iron Ingot","Metal for tools, armor, and recipes. Smelted from iron ore.","item material iron".split()),
        E("minecraft:gold_ingot","Gold Ingot","Metal for powered rails, golden apples, and armor.","item material gold".split()),
        E("minecraft:copper_ingot","Copper Ingot","Metal for lightning rods, telescopes, and blocks.","item material copper".split()),
        E("minecraft:netherite_ingot","Netherite Ingot","Best material. Crafted from netherite scraps and gold.","item material netherite".split()),
        E("minecraft:netherite_scrap","Netherite Scrap","Smelted from ancient debris. Used for netherite ingots.","item material netherite".split()),
        E("minecraft:diamond","Diamond","Rare gem for best tools and armor.","item material diamond".split()),
        E("minecraft:emerald","Emerald","Currency for villager trading.","item material currency".split()),
        E("minecraft:quartz","Nether Quartz","Mined from nether quartz ore. Used for redstone comparators and decoration.","item material nether".split()),
        E("minecraft:amethyst_shard","Amethyst Shard","Mined from amethyst clusters. Used for telescopes and tinted glass.","item material".split()),
        E("minecraft:redstone","Redstone Dust","Used for circuits and powered mechanisms.","item material redstone circuit".split()),
        E("minecraft:lapis_lazuli","Lapis Lazuli","Used for enchanting and blue dye.","item material dye enchanting".split()),
        E("minecraft:coal","Coal","Fuel and light source.","item fuel material".split()),
        E("minecraft:charcoal","Charcoal","Fuel made by smelting wood.","item fuel material".split()),
        E("minecraft:flint","Flint","Used for flint and steel and arrows. Dropped from gravel.","item material".split()),
        E("minecraft:flint_and_steel","Flint and Steel","Ignites fire, TNT, and nether portals.","item tool fire".split()),
        E("minecraft:torch","Torch","Provides light.","item light".split()),
        E("minecraft:soul_torch","Soul Torch","Blue torch.","item light soul_fire".split()),
        E("minecraft:bed","Bed","Sets spawn point and skips night.","item bed spawn".split()),
        E("minecraft:respawn_anchor","Respawn Anchor","Sets respawn point in the Nether. Needs glowstone to charge.","item bed nether spawn".split()),
        E("minecraft:bucket","Bucket","Holds water, lava, milk, or powder snow.","item tool container".split()),
        E("minecraft:water_bucket","Water Bucket","Bucket of water. Used to transport water and make obsidian.","item tool water".split()),
        E("minecraft:lava_bucket","Lava Bucket","Bucket of lava. Used as furnace fuel and to make obsidian.","item tool lava fuel".split()),
        E("minecraft:milk_bucket","Milk Bucket","Bucket of milk. Clears potion effects.","item tool food".split()),
        E("minecraft:powder_snow_bucket","Powder Snow Bucket","Bucket of powder snow.","item tool cold".split()),
        E("minecraft:shears","Shears","Used to shear sheep and mine leaves.","item tool".split()),
        E("minecraft:compass","Compass","Points to world spawn.","item tool navigation".split()),
        E("minecraft:recovery_compass","Recovery Compass","Points to your last death location.","item tool navigation".split()),
        E("minecraft:clock","Clock","Shows the time of day.","item tool".split()),
        E("minecraft:spyglass","Spyglass","Zooms in on distant objects. Crafted from copper and amethyst.","item tool".split()),
        E("minecraft:map","Map","Shows explored area.","item tool navigation".split()),
        E("minecraft:book","Book","Used for bookshelves and enchanted books.","item material".split()),
        E("minecraft:writable_book","Book and Quill","A writable book.","item material".split()),
        E("minecraft:written_book","Written Book","A signed book.","item material".split()),
        E("minecraft:paper","Paper","Made from sugar cane.","item material".split()),
        E("minecraft:leather","Leather","Dropped from cows and horses.","item material".split()),
        E("minecraft:feather","Feather","Dropped from chickens.","item material".split()),
        E("minecraft:string","String","Dropped from spiders.","item material".split()),
        E("minecraft:gunpowder","Gunpowder","Dropped from creepers and ghasts.","item material explosive".split()),
        E("minecraft:bone","Bone","Dropped from skeletons.","item material".split()),
        E("minecraft:bone_meal","Bone Meal","Speeds up crop growth and creates white dye.","item material farming dye".split()),
        E("minecraft:ender_pearl","Ender Pearl","Dropped from Endermen. Used to teleport or craft Eyes of Ender.","item material end teleport".split()),
        E("minecraft:eye_of_ender","Eye of Ender","Crafted from ender pearl and blaze powder. Thrown to locate strongholds.","item material end navigation".split()),
        E("minecraft:blaze_rod","Blaze Rod","Dropped from Blazes. Used for brewing and eyes of ender.","item material nether brewing".split()),
        E("minecraft:blaze_powder","Blaze Powder","Made from blaze rods. Used for brewing and eyes of ender.","item material nether brewing".split()),
        E("minecraft:ghast_tear","Ghast Tear","Dropped from Ghasts. Used for regeneration potions.","item material nether brewing".split()),
        E("minecraft:nether_wart","Nether Wart","Grown on soul sand. Base ingredient for most potions.","item material nether brewing".split()),
        E("minecraft:sugar","Sugar","Made from sugar cane. Used for potions and cake.","item material food brewing".split()),
        E("minecraft:glistering_melon_slice","Glistering Melon Slice","Melon slice and gold nugget. Used for healing potions.","item material brewing".split()),
        E("minecraft:golden_carrot","Golden Carrot","Carrot surrounded by gold nuggets. Used for night vision potions.","item material brewing food".split()),
        E("minecraft:fermented_spider_eye","Fermented Spider Eye","Spider eye, sugar, and brown mushroom. Used to create negative potions.","item material brewing".split()),
        E("minecraft:magma_cream","Magma Cream","From magma cubes or slime ball + blaze powder. Used for fire resistance potions.","item material nether brewing".split()),
        E("minecraft:phantom_membrane","Phantom Membrane","Dropped from phantoms. Used for slow falling potions.","item material brewing".split()),
        E("minecraft:potion","Potion","A brewable item with various effects.","item potion brewing".split()),
        E("minecraft:splash_potion","Splash Potion","A potion that splashes on impact.","item potion brewing".split()),
        E("minecraft:lingering_potion","Lingering Potion","A potion that leaves a lingering cloud.","item potion brewing".split()),
        E("minecraft:glass_bottle","Glass Bottle","Holds potions.","item tool brewing".split()),
        E("minecraft:brewing_stand","Brewing Stand","Used to brew potions.","item tool brewing".split()),
        E("minecraft:cauldron","Cauldron","Holds water, potions, or dyed water.","item tool brewing".split()),
        E("minecraft:sugar_cane","Sugar Cane","Grows near water. Used for sugar and paper.","item material farming".split()),
        E("minecraft:wheat","Wheat","Grown on farmland. Used for bread and breeding.","item food farming".split()),
        E("minecraft:bread","Bread","Crafted from wheat.","item food".split()),
        E("minecraft:carrot","Carrot","Grown on farmland.","item food farming".split()),
        E("minecraft:potato","Potato","Grown on farmland.","item food farming".split()),
        E("minecraft:baked_potato","Baked Potato","Potato baked in a furnace.","item food".split()),
        E("minecraft:beetroot","Beetroot","Grown on farmland.","item food farming".split()),
        E("minecraft:beetroot_soup","Beetroot Soup","Crafted from beets and a bowl.","item food".split()),
        E("minecraft:melon_slice","Melon Slice","Food from melons.","item food".split()),
        E("minecraft:pumpkin","Pumpkin","Grown from seeds. Used for decoration and golems.","item food farming".split()),
        E("minecraft:apple","Apple","Dropped from oak leaves.","item food".split()),
        E("minecraft:golden_apple","Golden Apple","Grants absorption and regeneration.","item food combat".split()),
        E("minecraft:enchanted_golden_apple","Enchanted Golden Apple","Rare golden apple. Found in chests.","item food combat rare".split()),
        E("minecraft:raw_beef","Raw Beef","Dropped from cows. Cook into steak.","item food".split()),
        E("minecraft:cooked_beef","Steak","Cooked beef. One of the best food sources.","item food".split()),
        E("minecraft:raw_porkchop","Raw Porkchop","From pigs and hoglins.","item food".split()),
        E("minecraft:cooked_porkchop","Cooked Porkchop","Cooked pork.","item food".split()),
        E("minecraft:chicken","Raw Chicken","From chickens. May cause hunger when raw.","item food".split()),
        E("minecraft:cooked_chicken","Cooked Chicken","Cooked chicken.","item food".split()),
        E("minecraft:raw_mutton","Raw Mutton","From sheep.","item food".split()),
        E("minecraft:cooked_mutton","Cooked Mutton","Cooked mutton.","item food".split()),
        E("minecraft:raw_rabbit","Raw Rabbit","From rabbits.","item food".split()),
        E("minecraft:cooked_rabbit","Cooked Rabbit","Cooked rabbit.","item food".split()),
        E("minecraft:rabbit_stew","Rabbit Stew","Cooked rabbit, carrot, potato, and mushrooms in a bowl.","item food".split()),
        E("minecraft:rotten_flesh","Rotten Flesh","From zombies. May cause hunger.","item food".split()),
        E("minecraft:spider_eye","Spider Eye","From spiders. Used for poison potions.","item material brewing".split()),
        E("minecraft:poisonous_potato","Poisonous Potato","Rare potato drop. Poisons when eaten.","item food".split()),
        E("minecraft:cookie","Cookie","Wheat and cocoa beans.","item food".split()),
        E("minecraft:cake","Cake","Wheat, sugar, eggs, and milk. Place and eat.","item food".split()),
        E("minecraft:pumpkin_pie","Pumpkin Pie","Pumpkin, sugar, and egg.","item food".split()),
        E("minecraft:mushroom_stew","Mushroom Stew","Red and brown mushroom in a bowl.","item food".split()),
        E("minecraft:suspicious_stew","Suspicious Stew","Stew brewed from flowers. Gives random effects.","item food".split()),
        E("minecraft:cod","Raw Cod","Caught in water. Cook for better food.","item food water".split()),
        E("minecraft:salmon","Raw Salmon","Caught in cold water.","item food water".split()),
        E("minecraft:tropical_fish","Tropical Fish","Colorful fish. No crafting use.","item food water".split()),
        E("minecraft:pufferfish","Pufferfish","Used for water breathing potions. Poisonous to eat.","item food water brewing".split()),
        E("minecraft:cooked_cod","Cooked Cod","Cooked cod.","item food".split()),
        E("minecraft:cooked_salmon","Cooked Salmon","Cooked salmon.","item food".split()),
        E("minecraft:dried_kelp","Dried Kelp","Easy early-game food.","item food".split()),
        E("minecraft:honey_bottle","Honey Bottle","Drinkable honey. Cures poison.","item food".split()),
        E("minecraft:experience_bottle","Bottle o' Enchanting","Splashes to release experience orbs.","item enchanting".split()),
        E("minecraft:ink_sac","Ink Sac","Black dye. From squid.","item dye material".split()),
        E("minecraft:glow_ink_sac","Glow Ink Sac","Glow item frame maker. From glow squid.","item dye material".split()),
        E("minecraft:cocoa_beans","Cocoa Beans","Brown dye. Grows on jungle logs.","item dye farming".split()),
        E("minecraft:lapis_lazuli","Lapis Lazuli","Blue dye.","item dye enchanting".split()),
        E("minecraft:bone_meal","Bone Meal","White dye.","item dye farming".split()),
        E("minecraft:slime_ball","Slime Ball","From slimes. Used for sticky pistons and leads.","item material".split()),
        E("minecraft:honeycomb","Honeycomb","From bee nests. Used for candles and waxed copper.","item material".split()),
        E("minecraft:nautilus_shell","Nautilus Shell","From fishing or drowned. Used for conduits.","item material water".split()),
        E("minecraft:heart_of_the_sea","Heart of the Sea","Rare treasure. Used for conduits.","item material water rare".split()),
        E("minecraft:conduit","Conduit","Underwater beacon giving water breathing and haste.","item tool water".split()),
        E("minecraft:name_tag","Name Tag","Names a mob. Found in chests or from fishing.","item tool".split()),
        E("minecraft:saddle","Saddle","Rides pigs, horses, or striders. Found in chests.","item tool transport".split()),
        E("minecraft:lead","Lead","Leads and ties mobs.","item tool".split()),
        E("minecraft:fishing_rod","Fishing Rod","Casts a line for fish and treasure.","item tool".split()),
        E("minecraft:carrot_on_a_stick","Carrot on a Stick","Controls saddled pigs.","item tool transport".split()),
        E("minecraft:warped_fungus_on_a_stick","Warped Fungus on a Stick","Controls saddled striders.","item tool transport nether".split()),
    ]

def recipes():
    return [
        {"id": "recipe:crafting_table", "category": "recipe", "name": "Crafting Table", "description": "Place 4 wooden planks in a 2x2 square in the inventory crafting grid. Expands the grid to 3x3.","tags":"recipe crafting".split()},
        {"id": "recipe:stick", "category": "recipe", "name": "Stick", "description": "Place 2 wooden planks vertically in the crafting grid. Used for tools and torches.","tags":"recipe crafting".split()},
        {"id": "recipe:torch", "category": "recipe", "name": "Torch", "description": "Place coal above a stick in the crafting grid. Provides light.","tags":"recipe crafting light".split()},
        {"id": "recipe:wooden_pickaxe", "category": "recipe", "name": "Wooden Pickaxe", "description": "3 planks across the top row and 2 sticks vertically in the middle column of a crafting table.","tags":"recipe crafting tool".split()},
        {"id": "recipe:stone_pickaxe", "category": "recipe", "name": "Stone Pickaxe", "description": "3 cobblestone across the top row and 2 sticks vertically in the middle column.","tags":"recipe crafting tool".split()},
        {"id": "recipe:iron_pickaxe", "category": "recipe", "name": "Iron Pickaxe", "description": "3 iron ingots across the top row and 2 sticks vertically in the middle column.","tags":"recipe crafting tool".split()},
        {"id": "recipe:diamond_pickaxe", "category": "recipe", "name": "Diamond Pickaxe", "description": "3 diamonds across the top row and 2 sticks vertically in the middle column.","tags":"recipe crafting tool".split()},
        {"id": "recipe:wooden_axe", "category": "recipe", "name": "Wooden Axe", "description": "3 planks in top-left, top-middle, and middle-left, plus 2 sticks vertically in middle-right.","tags":"recipe crafting tool".split()},
        {"id": "recipe:stone_axe", "category": "recipe", "name": "Stone Axe", "description": "3 cobblestone in the corners. 2 sticks in the right column.","tags":"recipe crafting tool".split()},
        {"id": "recipe:iron_axe", "category": "recipe", "name": "Iron Axe", "description": "3 iron ingots in the corners. 2 sticks in the right column.","tags":"recipe crafting tool".split()},
        {"id": "recipe:wooden_sword", "category": "recipe", "name": "Wooden Sword", "description": "2 planks in top-middle and middle-middle, plus 1 stick in the bottom-middle.","tags":"recipe crafting weapon".split()},
        {"id": "recipe:stone_sword", "category": "recipe", "name": "Stone Sword", "description": "2 cobblestone in top-middle and middle-middle, plus 1 stick in the bottom-middle.","tags":"recipe crafting weapon".split()},
        {"id": "recipe:iron_sword", "category": "recipe", "name": "Iron Sword", "description": "2 iron ingots in top-middle and middle-middle, plus 1 stick in the bottom-middle.","tags":"recipe crafting weapon".split()},
        {"id": "recipe:diamond_sword", "category": "recipe", "name": "Diamond Sword", "description": "2 diamonds in top-middle and middle-middle, plus 1 stick in the bottom-middle.","tags":"recipe crafting weapon".split()},
        {"id": "recipe:wooden_shovel", "category": "recipe", "name": "Wooden Shovel", "description": "1 plank above 2 sticks.","tags":"recipe crafting tool".split()},
        {"id": "recipe:stone_shovel", "category": "recipe", "name": "Stone Shovel", "description": "1 cobblestone above 2 sticks.","tags":"recipe crafting tool".split()},
        {"id": "recipe:iron_shovel", "category": "recipe", "name": "Iron Shovel", "description": "1 iron ingot above 2 sticks.","tags":"recipe crafting tool".split()},
        {"id": "recipe:diamond_shovel", "category": "recipe", "name": "Diamond Shovel", "description": "1 diamond above 2 sticks.","tags":"recipe crafting tool".split()},
        {"id": "recipe:wooden_hoe", "category": "recipe", "name": "Wooden Hoe", "description": "2 planks top-left and top-middle, 2 sticks right column.","tags":"recipe crafting tool".split()},
        {"id": "recipe:stone_hoe", "category": "recipe", "name": "Stone Hoe", "description": "2 cobblestone top-left and top-middle, 2 sticks right column.","tags":"recipe crafting tool".split()},
        {"id": "recipe:iron_hoe", "category": "recipe", "name": "Iron Hoe", "description": "2 iron ingots top-left and top-middle, 2 sticks right column.","tags":"recipe crafting tool".split()},
        {"id": "recipe:diamond_hoe", "category": "recipe", "name": "Diamond Hoe", "description": "2 diamonds top-left and top-middle, 2 sticks right column.","tags":"recipe crafting tool".split()},
        {"id": "recipe:bucket", "category": "recipe", "name": "Bucket", "description": "3 iron ingots in a V shape.","tags":"recipe crafting".split()},
        {"id": "recipe:furnace", "category": "recipe", "name": "Furnace", "description": "8 cobblestone around the edge, center empty.","tags":"recipe crafting smelting".split()},
        {"id": "recipe:blast_furnace", "category": "recipe", "name": "Blast Furnace", "description": "Furnace surrounded by 5 iron ingots and 3 smooth stone below.","tags":"recipe crafting smelting".split()},
        {"id": "recipe:smoker", "category": "recipe", "name": "Smoker", "description": "Furnace surrounded by 4 logs.","tags":"recipe crafting smelting food".split()},
        {"id": "recipe:chest", "category": "recipe", "name": "Chest", "description": "8 wooden planks around the edge, center empty.","tags":"recipe crafting storage".split()},
        {"id": "recipe:bed", "category": "recipe", "name": "Bed", "description": "3 wool across the top row and 3 wooden planks across the middle row.","tags":"recipe crafting bed".split()},
        {"id": "recipe:shield", "category": "recipe", "name": "Shield", "description": "6 wood planks in a Y shape plus an iron ingot in the top-middle.","tags":"recipe crafting defense".split()},
        {"id": "recipe:bow", "category": "recipe", "name": "Bow", "description": "3 sticks and 3 string in a U shape with string on the right.","tags":"recipe crafting weapon".split()},
        {"id": "recipe:crossbow", "category": "recipe", "name": "Crossbow", "description": "3 sticks, 2 string, 1 iron ingot, 1 tripwire hook.","tags":"recipe crafting weapon".split()},
        {"id": "recipe:arrow", "category": "recipe", "name": "Arrow", "description": "Flint on top, stick in middle, feather on bottom.","tags":"recipe crafting ammo".split()},
        {"id": "recipe:paper", "category": "recipe", "name": "Paper", "description": "3 sugar canes horizontally.","tags":"recipe crafting".split()},
        {"id": "recipe:book", "category": "recipe", "name": "Book", "description": "3 paper and 1 leather.","tags":"recipe crafting".split()},
        {"id": "recipe:bookshelf", "category": "recipe", "name": "Bookshelf", "description": "3 books in middle row, 6 wood planks around them.","tags":"recipe crafting enchanting".split()},
        {"id": "recipe:enchanting_table", "category": "recipe", "name": "Enchanting Table", "description": "4 obsidian on bottom, 2 diamonds on sides, 1 book on top.","tags":"recipe crafting enchanting".split()},
        {"id": "recipe:anvil", "category": "recipe", "name": "Anvil", "description": "3 iron blocks across top row, 1 iron ingot in center, 3 iron ingots across bottom.","tags":"recipe crafting repair".split()},
        {"id": "recipe:grindstone", "category": "recipe", "name": "Grindstone", "description": "2 sticks, 1 stone slab, 2 planks.","tags":"recipe crafting repair".split()},
        {"id": "recipe:smithing_table", "category": "recipe", "name": "Smithing Table", "description": "2 iron ingots above 4 planks.","tags":"recipe crafting netherite".split()},
        {"id": "recipe:stonecutter", "category": "recipe", "name": "Stonecutter", "description": "3 stone and 1 iron ingot.","tags":"recipe crafting building".split()},
        {"id": "recipe:composter", "category": "recipe", "name": "Composter", "description": "7 fence posts in a U shape.","tags":"recipe crafting farming".split()},
        {"id": "recipe:loom", "category": "recipe", "name": "Loom", "description": "2 string and 2 planks.","tags":"recipe crafting decorative".split()},
        {"id": "recipe:cartography_table", "category": "recipe", "name": "Cartography Table", "description": "2 paper above 4 planks.","tags":"recipe crafting navigation".split()},
        {"id": "recipe:iron_helmet", "category": "recipe", "name": "Iron Helmet", "description": "5 iron ingots in an upside-down U.","tags":"recipe crafting armor".split()},
        {"id": "recipe:iron_chestplate", "category": "recipe", "name": "Iron Chestplate", "description": "8 iron ingots in a square, leaving top-middle empty.","tags":"recipe crafting armor".split()},
        {"id": "recipe:iron_leggings", "category": "recipe", "name": "Iron Leggings", "description": "7 iron ingots in a U shape.","tags":"recipe crafting armor".split()},
        {"id": "recipe:iron_boots", "category": "recipe", "name": "Iron Boots", "description": "4 iron ingots in a U shape.","tags":"recipe crafting armor".split()},
        {"id": "recipe:compass", "category": "recipe", "name": "Compass", "description": "4 iron ingots around redstone in the center.","tags":"recipe crafting navigation".split()},
        {"id": "recipe:clock", "category": "recipe", "name": "Clock", "description": "4 gold ingots around redstone in the center.","tags":"recipe crafting".split()},
        {"id": "recipe:recovery_compass", "category": "recipe", "name": "Recovery Compass", "description": "8 echo shards around a compass.","tags":"recipe crafting navigation".split()},
        {"id": "recipe:flint_and_steel", "category": "recipe", "name": "Flint and Steel", "description": "Flint and iron ingot diagonally.","tags":"recipe crafting fire".split()},
        {"id": "recipe:glass_bottle", "category": "recipe", "name": "Glass Bottle", "description": "3 glass blocks in a V shape.","tags":"recipe crafting brewing".split()},
        {"id": "recipe:brewing_stand", "category": "recipe", "name": "Brewing Stand", "description": "3 cobblestone across bottom and 1 blaze rod in center.","tags":"recipe crafting brewing".split()},
        {"id": "recipe:cauldron", "category": "recipe", "name": "Cauldron", "description": "7 iron ingots in a U shape.","tags":"recipe crafting".split()},
        {"id": "recipe:hopper", "category": "recipe", "name": "Hopper", "description": "5 iron ingots and 1 chest in a V shape.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:dispenser", "category": "recipe", "name": "Dispenser", "description": "7 cobblestone, 1 bow, 1 redstone.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:dropper", "category": "recipe", "name": "Dropper", "description": "7 cobblestone and 1 redstone.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:piston", "category": "recipe", "name": "Piston", "description": "3 planks, 4 cobblestone, 1 iron ingot, 1 redstone.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:sticky_piston", "category": "recipe", "name": "Sticky Piston", "description": "1 piston and 1 slime ball.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:redstone_torch", "category": "recipe", "name": "Redstone Torch", "description": "1 redstone above 1 stick.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:repeater", "category": "recipe", "name": "Redstone Repeater", "description": "3 stone, 2 redstone torches, 1 redstone.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:comparator", "category": "recipe", "name": "Redstone Comparator", "description": "3 stone, 3 redstone torches, 1 nether quartz.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:daylight_detector", "category": "recipe", "name": "Daylight Detector", "description": "3 glass, 3 nether quartz, 3 wood slabs.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:observer", "category": "recipe", "name": "Observer", "description": "6 cobblestone, 2 redstone, 1 nether quartz.","tags":"recipe crafting redstone".split()},
        {"id": "recipe:note_block", "category": "recipe", "name": "Note Block", "description": "8 wood planks around 1 redstone.","tags":"recipe crafting".split()},
        {"id": "recipe:jukebox", "category": "recipe", "name": "Jukebox", "description": "8 wood planks around 1 diamond.","tags":"recipe crafting".split()},
        {"id": "recipe:tnt", "category": "recipe", "name": "TNT", "description": "5 gunpowder in an X and 4 sand around them.","tags":"recipe crafting explosive".split()},
        {"id": "recipe:fire_charge", "category": "recipe", "name": "Fire Charge", "description": "1 coal, 1 gunpowder, 1 blaze powder.","tags":"recipe crafting fire".split()},
        {"id": "recipe:lead", "category": "recipe", "name": "Lead", "description": "4 string and 1 slime ball.","tags":"recipe crafting".split()},
        {"id": "recipe:lantern", "category": "recipe", "name": "Lantern", "description": "8 iron nuggets around 1 torch.","tags":"recipe crafting light".split()},
        {"id": "recipe:soul_lantern", "category": "recipe", "name": "Soul Lantern", "description": "8 iron nuggets around 1 soul torch.","tags":"recipe crafting light".split()},
        {"id": "recipe:chain", "category": "recipe", "name": "Chain", "description": "1 iron ingot above 1 iron nugget above 1 iron ingot.","tags":"recipe crafting building".split()},
        {"id": "recipe:bread", "category": "recipe", "name": "Bread", "description": "3 wheat horizontally.","tags":"recipe crafting food".split()},
        {"id": "recipe:bowl", "category": "recipe", "name": "Bowl", "description": "3 planks in a V shape.","tags":"recipe crafting".split()},
        {"id": "recipe:spyglass", "category": "recipe", "name": "Spyglass", "description": "1 amethyst shard above 2 copper ingots.","tags":"recipe crafting tool".split()},
        {"id": "recipe:firework_rocket", "category": "recipe", "name": "Firework Rocket", "description": "1 paper and 1 gunpowder. Add stars for effects.","tags":"recipe crafting".split()},
        {"id": "recipe:iron_door", "category": "recipe", "name": "Iron Door", "description": "6 iron ingots in two vertical columns.","tags":"recipe crafting".split()},
        {"id": "recipe:wooden_door", "category": "recipe", "name": "Wooden Door", "description": "6 wood planks in two vertical columns.","tags":"recipe crafting".split()},
        {"id": "recipe:trapdoor", "category": "recipe", "name": "Trapdoor", "description": "6 wood planks in two rows of three.","tags":"recipe crafting".split()},
        {"id": "recipe:fence", "category": "recipe", "name": "Fence", "description": "4 planks and 2 sticks in alternating columns.","tags":"recipe crafting".split()},
        {"id": "recipe:gate", "category": "recipe", "name": "Fence Gate", "description": "2 sticks and 4 planks in a gate shape.","tags":"recipe crafting".split()},
        {"id": "recipe:ladder", "category": "recipe", "name": "Ladder", "description": "7 sticks in an H shape.","tags":"recipe crafting".split()},
        {"id": "recipe:sign", "category": "recipe", "name": "Sign", "description": "6 planks across top two rows and 1 stick in bottom-middle.","tags":"recipe crafting".split()},
        {"id": "recipe:boat", "category": "recipe", "name": "Boat", "description": "5 planks in a U shape.","tags":"recipe crafting transport".split()},
        {"id": "recipe:fishing_rod", "category": "recipe", "name": "Fishing Rod", "description": "3 sticks and 2 string diagonally.","tags":"recipe crafting tool".split()},
        {"id": "recipe:shears", "category": "recipe", "name": "Shears", "description": "2 iron ingots diagonally.","tags":"recipe crafting tool".split()},
    ]

def biomes():
    return [
        {"id":"minecraft:plains","category":"biome","name":"Plains","description":"Flat grasslands with scattered trees and villages. Good for building and farming.","tags":"biome".split()},
        {"id":"minecraft:forest","category":"biome","name":"Forest","description":"Overworld biome with many oak and birch trees.","tags":"biome".split()},
        {"id":"minecraft:dark_forest","category":"biome","name":"Dark Forest","description":"Dense forest with dark oak trees. Woodland mansions can spawn here.","tags":"biome".split()},
        {"id":"minecraft:birch_forest","category":"biome","name":"Birch Forest","description":"Forest dominated by birch trees.","tags":"biome".split()},
        {"id":"minecraft:flower_forest","category":"biome","name":"Flower Forest","description":"Forest with many flowers and fewer trees.","tags":"biome".split()},
        {"id":"minecraft:taiga","category":"biome","name":"Taiga","description":"Cold forest with spruce trees, foxes, and wolves.","tags":"biome".split()},
        {"id":"minecraft:snowy_taiga","category":"biome","name":"Snowy Taiga","description":"Cold taiga covered in snow.","tags":"biome".split()},
        {"id":"minecraft:old_growth_pine_taiga","category":"biome","name":"Old Growth Pine Taiga","description":"Taiga with giant spruce trees and podzol ground.","tags":"biome".split()},
        {"id":"minecraft:old_growth_spruce_taiga","category":"biome","name":"Old Growth Spruce Taiga","description":"Taiga with giant spruce trees.","tags":"biome".split()},
        {"id":"minecraft:jungle","category":"biome","name":"Jungle","description":"Dense tropical biome with tall trees, vines, and temples.","tags":"biome".split()},
        {"id":"minecraft:bamboo_jungle","category":"biome","name":"Bamboo Jungle","description":"Jungle variant filled with bamboo and pandas.","tags":"biome".split()},
        {"id":"minecraft:sparse_jungle","category":"biome","name":"Sparse Jungle","description":"Sparse jungle variant.","tags":"biome".split()},
        {"id":"minecraft:swamp","category":"biome","name":"Swamp","description":"Wet biome with shallow water, oak trees, and witch huts.","tags":"biome".split()},
        {"id":"minecraft:mangrove_swamp","category":"biome","name":"Mangrove Swamp","description":"Swamp with mangrove trees, mud, and frogs.","tags":"biome".split()},
        {"id":"minecraft:desert","category":"biome","name":"Desert","description":"Dry biome with sand, cacti, and desert pyramids.","tags":"biome".split()},
        {"id":"minecraft:savanna","category":"biome","name":"Savanna","description":"Warm grassland with acacia trees and villages.","tags":"biome".split()},
        {"id":"minecraft:windswept_hills","category":"biome","name":"Windswept Hills","description":"Hilly terrain with extreme height variation.","tags":"biome".split()},
        {"id":"minecraft:windswept_gravelly_hills","category":"biome","name":"Windswept Gravelly Hills","description":"Hills covered in gravel.","tags":"biome".split()},
        {"id":"minecraft:windswept_forest","category":"biome","name":"Windswept Forest","description":"Forested hilly terrain.","tags":"biome".split()},
        {"id":"minecraft:windswept_savanna","category":"biome","name":"Windswept Savanna","description":"Savanna with extreme terrain and floating islands.","tags":"biome".split()},
        {"id":"minecraft:badlands","category":"biome","name":"Badlands","description":"Dry biome with terracotta and gold ore. Mineshafts spawn on the surface.","tags":"biome".split()},
        {"id":"minecraft:wooded_badlands","category":"biome","name":"Wooded Badlands","description":"Badlands with patches of oak trees.","tags":"biome".split()},
        {"id":"minecraft:eroded_badlands","category":"biome","name":"Eroded Badlands","description":"Badlands with eroded tall pillars.","tags":"biome".split()},
        {"id":"minecraft:meadow","category":"biome","name":"Meadow","description":"High-altitude grassy plain with flowers and rabbits.","tags":"biome".split()},
        {"id":"minecraft:cherry_grove","category":"biome","name":"Cherry Grove","description":"Mountain biome with cherry trees and pink petals.","tags":"biome decorative".split()},
        {"id":"minecraft:grove","category":"biome","name":"Grove","description":"Snowy forest found on mountain slopes.","tags":"biome".split()},
        {"id":"minecraft:snowy_slopes","category":"biome","name":"Snowy Slopes","description":"Cold mountain slopes with rabbits and goats.","tags":"biome".split()},
        {"id":"minecraft:jagged_peaks","category":"biome","name":"Jagged Peaks","description":"High mountain peaks of stone and snow.","tags":"biome".split()},
        {"id":"minecraft:frozen_peaks","category":"biome","name":"Frozen Peaks","description":"High mountain peaks covered in ice and snow.","tags":"biome".split()},
        {"id":"minecraft:stony_peaks","category":"biome","name":"Stony Peaks","description":"High mountain peaks made of stone and calcite.","tags":"biome".split()},
        {"id":"minecraft:beach","category":"biome","name":"Beach","description":"Sandy area between oceans and land.","tags":"biome".split()},
        {"id":"minecraft:snowy_beach","category":"biome","name":"Snowy Beach","description":"Cold beach covered in snow.","tags":"biome".split()},
        {"id":"minecraft:stony_shore","category":"biome","name":"Stony Shore","description":"Rocky shore without sand.","tags":"biome".split()},
        {"id":"minecraft:river","category":"biome","name":"River","description":"Long stretches of water through the Overworld.","tags":"biome".split()},
        {"id":"minecraft:frozen_river","category":"biome","name":"Frozen River","description":"River covered in ice.","tags":"biome".split()},
        {"id":"minecraft:ocean","category":"biome","name":"Ocean","description":"Large saltwater biome with fish, kelp, and shipwrecks.","tags":"biome".split()},
        {"id":"minecraft:deep_ocean","category":"biome","name":"Deep Ocean","description":"Deeper ocean variant with ocean monuments.","tags":"biome".split()},
        {"id":"minecraft:warm_ocean","category":"biome","name":"Warm Ocean","description":"Ocean with coral reefs and tropical fish.","tags":"biome".split()},
        {"id":"minecraft:lukewarm_ocean","category":"biome","name":"Lukewarm Ocean","description":"Ocean between warm and cold.","tags":"biome".split()},
        {"id":"minecraft:cold_ocean","category":"biome","name":"Cold Ocean","description":"Cold ocean with cod.","tags":"biome".split()},
        {"id":"minecraft:frozen_ocean","category":"biome","name":"Frozen Ocean","description":"Ocean with icebergs and polar bears.","tags":"biome".split()},
        {"id":"minecraft:deep_lukewarm_ocean","category":"biome","name":"Deep Lukewarm Ocean","description":"Deep variant of lukewarm ocean.","tags":"biome".split()},
        {"id":"minecraft:deep_cold_ocean","category":"biome","name":"Deep Cold Ocean","description":"Deep variant of cold ocean.","tags":"biome".split()},
        {"id":"minecraft:deep_frozen_ocean","category":"biome","name":"Deep Frozen Ocean","description":"Deep variant of frozen ocean.","tags":"biome".split()},
        {"id":"minecraft:mushroom_fields","category":"biome","name":"Mushroom Fields","description":"Rare biome with mooshrooms and giant mushrooms. No hostile mobs spawn.","tags":"biome".split()},
        {"id":"minecraft:dripstone_caves","category":"biome","name":"Dripstone Caves","description":"Underground cave biome with pointed dripstone.","tags":"biome".split()},
        {"id":"minecraft:lush_caves","category":"biome","name":"Lush Caves","description":"Underground biome with moss, azalea, and glow berries.","tags":"biome".split()},
        {"id":"minecraft:deep_dark","category":"biome","name":"Deep Dark","description":"Deep cave biome with sculk and the warden.","tags":"biome".split()},
        {"id":"minecraft:nether_wastes","category":"biome","name":"Nether Wastes","description":"The main Nether biome with netherrack, lava, and ghasts.","tags":"biome".split()},
        {"id":"minecraft:soul_sand_valley","category":"biome","name":"Soul Sand Valley","description":"Nether biome with soul sand, soul soil, and skeletons/ghasts.","tags":"biome".split()},
        {"id":"minecraft:crimson_forest","category":"biome","name":"Crimson Forest","description":"Nether forest with crimson trees, hoglins, and piglins.","tags":"biome".split()},
        {"id":"minecraft:warped_forest","category":"biome","name":"Warped Forest","description":"Nether forest with warped trees and endermen.","tags":"biome".split()},
        {"id":"minecraft:basalt_deltas","category":"biome","name":"Basalt Deltas","description":"Nether biome with basalt pillars, magma cubes, and ghasts.","tags":"biome".split()},
        {"id":"minecraft:the_end","category":"biome","name":"The End","description":"Dimension of floating islands and the Ender Dragon.","tags":"biome".split()},
        {"id":"minecraft:end_highlands","category":"biome","name":"End Highlands","description":"Outer End islands with chorus plants and end cities.","tags":"biome".split()},
        {"id":"minecraft:end_midlands","category":"biome","name":"End Midlands","description":"Transition area between central End and outer islands.","tags":"biome".split()},
        {"id":"minecraft:end_barrens","category":"biome","name":"End Barrens","description":"Empty outer End areas with few features.","tags":"biome".split()},
        {"id":"minecraft:small_end_islands","category":"biome","name":"Small End Islands","description":"Small outer islands past the void.","tags":"biome".split()},
    ]

def strategy():
    return [
        {"id":"strategy:mining","category":"strategy","name":"Mining","description":"Dig down carefully with torches, tools, and food. Avoid digging straight down. Use strip mining at diamond levels.","tags":"strategy".split()},
        {"id":"strategy:strip_mining","category":"strategy","name":"Strip Mining","description":"Mine long tunnels at Y=-59 to find diamonds. Place torches every 10 blocks and watch for lava.","tags":"strategy".split()},
        {"id":"strategy:caving","category":"strategy","name":"Caving","description":"Explore natural caves for exposed ores. Bring plenty of torches, food, and armor.","tags":"strategy".split()},
        {"id":"strategy:nether_exploration","category":"strategy","name":"Nether Exploration","description":"Wear gold armor around piglins. Bring fire resistance potions. Build safe paths over lava.","tags":"strategy".split()},
        {"id":"strategy:nether_fortress_route","category":"strategy","name":"Nether Fortress Route","description":"Follow a single direction in the Nether. Fortresses generate perpendicular to the x-axis.","tags":"strategy nether".split()},
        {"id":"strategy:nether_safe_travel","category":"strategy","name":"Nether Safe Travel","description":"Build tunnels with slabs to prevent mob spawning. Use warped fungi to control striders.","tags":"strategy nether".split()},
        {"id":"strategy:end_fight","category":"strategy","name":"Ender Dragon Fight","description":"Destroy end crystals with arrows or blocks. Attack the dragon when it perches. Bring slow falling potions.","tags":"strategy".split()},
        {"id":"strategy:end_city_raiding","category":"strategy","name":"End City Raiding","description":"Bridge to outer islands. Find the ship for elytra. Watch for shulkers on the walls.","tags":"strategy end".split()},
        {"id":"strategy:wither_fight","category":"strategy","name":"Wither Fight","description":"Fight underground in a confined space. Use smite enchantment and healing potions.","tags":"strategy".split()},
        {"id":"strategy:warden_avoid","category":"strategy","name":"Warden Avoidance","description":"Move slowly in the deep dark. Wool blocks vibrations. Use snowballs to distract.","tags":"strategy".split()},
        {"id":"strategy:villager_trading","category":"strategy","name":"Villager Trading","description":"Protect villagers with walls and beds. Give job blocks. Cure zombie villagers for trading discounts.","tags":"strategy".split()},
        {"id":"strategy:villager_breedering","category":"strategy","name":"Villager Breeder","description":"Build a breeder with beds, workstations, and food (bread/carrots). Villagers with beds breed.","tags":"strategy village".split()},
        {"id":"strategy:villager_zombie_cure","category":"strategy","name":"Zombie Villager Cure","description":"Splash a zombie villager with weakness, then feed a golden apple. Wait 2-5 minutes. Discounted trades!","tags":"strategy village".split()},
        {"id":"strategy:farming","category":"strategy","name":"Farming","description":"Plant crops on hydrated farmland. Use bonemeal to speed growth. Keep light level high.","tags":"strategy".split()},
        {"id":"strategy:automated_farm","category":"strategy","name":"Automated Farm","description":"Use water to collect crops. Use observer + piston for automatic harvesting.","tags":"strategy farming".split()},
        {"id":"strategy:animal_farming","category":"strategy","name":"Animal Farming","description":"Breed animals with their preferred food. Keep them in pens with water.","tags":"strategy".split()},
        {"id":"strategy:honey_farming","category":"strategy","name":"Honey Farming","description":"Use shears for honeycomb and bottles for honey. Place a campfire under the hive to pacify bees.","tags":"strategy farming".split()},
        {"id":"strategy:defense","category":"strategy","name":"Base Defense","description":"Light the area, build walls, use iron golems, and place traps for hostile mobs.","tags":"strategy".split()},
        {"id":"strategy:mob_grinder","category":"strategy","name":"Mob Grinder","description":"Build a dark tower with water channels. Mobs drop to a killing chamber. Collect drops with hoppers.","tags":"strategy combat".split()},
        {"id":"strategy:raids","category":"strategy","name":"Raid Defense","description":"Ring a bell to reveal raiders. Use walls and ranged attacks. Heal between waves.","tags":"strategy".split()},
        {"id":"strategy:exploration","category":"strategy","name":"Exploration","description":"Bring food, torches, a bed, and a compass. Mark your path to avoid getting lost.","tags":"strategy".split()},
        {"id":"strategy:combat","category":"strategy","name":"Combat Basics","description":"Equip the right weapon and armor. Strafe to avoid attacks. Retreat when low on health.","tags":"strategy".split()},
        {"id":"strategy:enchanting","category":"strategy","name":"Enchanting","description":"Build bookshelves around the enchanting table. Use an anvil to combine enchanted books.","tags":"strategy".split()},
        {"id":"strategy:brewing","category":"strategy","name":"Brewing","description":"Build a brewing stand. Nether wart is the base ingredient for most potions.","tags":"strategy".split()},
        {"id":"strategy:potion_brewing","category":"strategy","name":"Potion Brewing Guide","description":"Nether wart + water bottle = awkward potion. Add effect ingredient. Add redstone for duration or glowstone for potency. Use gunpowder for splash.","tags":"strategy brewing".split()},
        {"id":"strategy:smelting","category":"strategy","name":"Smelting","description":"Use furnaces for everything, blast furnaces for ores, smokers for food.","tags":"strategy".split()},
        {"id":"strategy:redstone","category":"strategy","name":"Redstone Basics","description":"Power with redstone dust, torches, and repeaters. Observers detect block changes.","tags":"strategy".split()},
        {"id":"strategy:redstone_clock","category":"strategy","name":"Redstone Clock","description":"Use a repeater loop or observer loop for a repeating redstone signal.","tags":"strategy redstone".split()},
        {"id":"strategy:redstone_item_sorter","category":"strategy","name":"Item Sorter","description":"Use hoppers and comparators to sort items by type into different chests.","tags":"strategy redstone".split()},
        {"id":"strategy:building","category":"strategy","name":"Building","description":"Plan foundations and storage first. Use scaffolding. Light interiors properly.","tags":"strategy".split()},
        {"id":"strategy:automation","category":"strategy","name":"Automation","description":"Use hoppers, droppers, dispensers, and observers to automate farms and sorting.","tags":"strategy".split()},
        {"id":"strategy:speedrun","category":"strategy","name":"Speedrun","description":"Focus on wood, tools, iron, flint and steel, beds, and eyes of ender. Minimize detours.","tags":"strategy".split()},
        {"id":"strategy:speedrun_route","category":"strategy","name":"Speedrun Route Details","description":"Get wood → stone pick → iron pick → portal (use bucket for obsidian) → find fortress → bed in nether (kills blazes) → pearls from bartering → eyes → stronghold → end.","tags":"strategy speedrun".split()},
        {"id":"strategy:resource_management","category":"strategy","name":"Resource Management","description":"Store items in labeled chests. Keep backups of important tools. Use shulker boxes for travel.","tags":"strategy".split()},
        {"id":"strategy:preparation","category":"strategy","name":"Preparation","description":"Before a big task, gather food, tools, armor, blocks, potions, and set a spawn point.","tags":"strategy".split()},
        {"id":"strategy:recovery","category":"strategy","name":"Recovery","description":"After death, prioritize item retrieval before re-engaging threats.","tags":"strategy".split()},
        {"id":"strategy:multiplayer","category":"strategy","name":"Multiplayer","description":"Coordinate roles, share resources, and establish safe zones.","tags":"strategy".split()},
        {"id":"strategy:starter_guide","category":"strategy","name":"First Day Guide","description":"Punch tree (4-6 logs) → craft wooden pick → mine 19 stone → craft stone pick/sword/furnace → shelter before night → go mining safely.","tags":"strategy early".split()},
        {"id":"strategy:early_iron","category":"strategy","name":"Getting Iron Early","description":"Find a cave or dig down to Y=16. Iron generates most commonly between Y=-64 and Y=72.","tags":"strategy mining".split()},
        {"id":"strategy:emergency_kits","category":"strategy","name":"Emergency Kit","description":"Carry a backup set of tools, food, blocks, a water bucket, and a bed in your ender chest.","tags":"strategy preparation".split()},
        {"id":"strategy:bartering","category":"strategy","name":"Piglin Bartering","description":"Drop gold ingots near piglins. They may drop ender pearls, obsidian, fire resistance potions, or other useful items. Wear gold armor to avoid aggression.","tags":"strategy nether".split()},
        {"id":"strategy:bridging","category":"strategy","name":"Safe Bridging","description":"Walk backward while placing blocks. Use scaffolding for long bridges. Sneak at edges.","tags":"strategy building".split()},
        {"id":"strategy:water_elevator","category":"strategy","name":"Water Elevator","description":"Use kelp to make bubble columns. Soul sand pushes upward, magma pushes downward.","tags":"strategy building".split()},
        {"id":"strategy:tree_farm","category":"strategy","name":"Tree Farming","description":"Plant saplings with 4+ blocks of space above. Oak need less, jungle trees need more space.","tags":"strategy farming".split()},
        {"id":"strategy:beacon_usage","category":"strategy","name":"Beacon Pyramid","description":"Build a pyramid of mineral blocks (iron/gold/diamond/emerald). A full 4-layer pyramid costs 164 blocks. Beacons give Haste, Speed, Jump Boost, Resistance, Strength, or Regeneration.","tags":"strategy".split()},
        {"id":"strategy:safe_mining","category":"strategy","name":"Safe Mining","description":"Never dig straight down. Light up caves to prevent mob spawns. Place torches on the left wall so you can find your way back.","tags":"strategy mining".split()},
        {"id":"strategy:raid_farm","category":"strategy","name":"Raid Farm","description":"Create a killer chamber with a pillager spawner. Obtain totems of undying, emeralds, and crossbows from raid waves.","tags":"strategy combat".split()},
        {"id":"strategy:shulker_box_usage","category":"strategy","name":"Shulker Box Storage","description":"Shulker boxes are portable storage. They keep items when broken. Color-code them for inventory organization.","tags":"strategy end storage".split()},
        {"id":"strategy:explosive_mining","category":"strategy","name":"Explosive Mining","description":"Use beds in the Nether for ancient debris. Beds explode in the Nether/End. TNT works too.","tags":"strategy mining nether".split()},
        {"id":"strategy:crop_automation","category":"strategy","name":"Crop Automation","description":"Use observers to detect crop growth and pistons to harvest. Waterlogged blocks can replace water sources.","tags":"strategy farming redstone".split()},
    ]

if __name__ == "__main__":
    write("blocks.json", blocks())
    write("mobs.json", mobs())
    write("items.json", items())
    write("recipes.json", recipes())
    write("biomes.json", biomes())
    write("strategy.json", strategy())
