#!/usr/bin/env node
/* Generate expanded knowledge JSON files for SmithAI. */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', 'SmithAI', 'src', 'main', 'resources', 'knowledge');

function write(name, data) {
  const out = path.join(ROOT, name);
  fs.writeFileSync(out, JSON.stringify(data, null, 2), 'utf-8');
  console.log(`Wrote ${data.length} entries to ${out}`);
}

const entry = (id, category, name, description, tags) => ({ id, category, name, description, tags });

const blocks = () => [
  entry("minecraft:stone", "block", "Stone", "A common solid block found underground. Mined fastest with a pickaxe. Drops cobblestone unless mined with Silk Touch.", ["block", "mining", "building"]),
  entry("minecraft:cobblestone", "block", "Cobblestone", "Dropped when mining stone without Silk Touch. Used for tools, furnaces, and building.", ["block", "mining", "building"]),
  entry("minecraft:granite", "block", "Granite", "An igneous rock variant of stone. Can be polished for decorative building.", ["block", "mining", "building", "decorative"]),
  entry("minecraft:diorite", "block", "Diorite", "A white stone variant. Can be polished for decorative use.", ["block", "mining", "building", "decorative"]),
  entry("minecraft:andesite", "block", "Andesite", "A gray stone variant. Can be polished for decorative building.", ["block", "mining", "building", "decorative"]),
  entry("minecraft:deepslate", "block", "Deepslate", "A dark stone variant found deep underground. Harder than stone and used for building.", ["block", "mining", "building", "deep"]),
  entry("minecraft:cobbled_deepslate", "block", "Cobbled Deepslate", "Drops from mining deepslate. Used for tools and building.", ["block", "mining", "building"]),
  entry("minecraft:iron_ore", "block", "Iron Ore", "Iron ore is found underground, usually between Y=-64 and Y=72. Requires a stone pickaxe or better. Smelt it to get iron ingots.", ["block", "mining", "ore", "iron"]),
  entry("minecraft:deepslate_iron_ore", "block", "Deepslate Iron Ore", "Iron ore embedded in deepslate. Requires a stone pickaxe or better. Drops iron ore.", ["block", "mining", "ore", "iron"]),
  entry("minecraft:gold_ore", "block", "Gold Ore", "Gold ore is found underground around Y=-16 and abundantly in Badlands. Requires an iron pickaxe or better. Smelt to get gold ingots.", ["block", "mining", "ore", "gold"]),
  entry("minecraft:deepslate_gold_ore", "block", "Deepslate Gold Ore", "Gold ore embedded in deepslate. Requires an iron pickaxe or better.", ["block", "mining", "ore", "gold"]),
  entry("minecraft:diamond_ore", "block", "Diamond Ore", "Diamond ore is found deep underground, most commonly around Y=-59. Requires an iron pickaxe or better. Drops diamonds.", ["block", "mining", "ore", "diamond"]),
  entry("minecraft:deepslate_diamond_ore", "block", "Deepslate Diamond Ore", "Diamond ore embedded in deepslate. Requires an iron pickaxe or better.", ["block", "mining", "ore", "diamond"]),
  entry("minecraft:coal_ore", "block", "Coal Ore", "Coal ore is common underground and in mountains. Mined with any pickaxe. Drops coal for torches and fuel.", ["block", "mining", "ore", "coal", "fuel"]),
  entry("minecraft:deepslate_coal_ore", "block", "Deepslate Coal Ore", "Coal ore embedded in deepslate. Mined with any pickaxe. Drops coal.", ["block", "mining", "ore", "coal", "fuel"]),
  entry("minecraft:redstone_ore", "block", "Redstone Ore", "Redstone ore is found deep underground. Requires an iron pickaxe or better. Drops redstone dust.", ["block", "mining", "ore", "redstone"]),
  entry("minecraft:lapis_ore", "block", "Lapis Lazuli Ore", "Lapis ore is found underground. Requires a stone pickaxe or better. Drops lapis lazuli.", ["block", "mining", "ore", "lapis"]),
  entry("minecraft:copper_ore", "block", "Copper Ore", "Copper ore generates in larger ore blobs underground. Requires a stone pickaxe or better. Smelt into copper ingots.", ["block", "mining", "ore", "copper"]),
  entry("minecraft:emerald_ore", "block", "Emerald Ore", "Emerald ore is found in mountain biomes. Requires an iron pickaxe or better. Drops emeralds.", ["block", "mining", "ore", "emerald"]),
  entry("minecraft:obsidian", "block", "Obsidian", "Created when water touches a lava source. Requires a diamond or netherite pickaxe. Used for nether portals and enchanting tables.", ["block", "mining", "portal", "enchanting"]),
  entry("minecraft:crafting_table", "block", "Crafting Table", "Expands the crafting grid to 3x3. Crafted from 4 wooden planks.", ["block", "crafting"]),
  entry("minecraft:furnace", "block", "Furnace", "Smelts ores, food, and other items using fuel. Crafted from 8 cobblestone.", ["block", "smelting", "fuel"]),
  entry("minecraft:blast_furnace", "block", "Blast Furnace", "Smelts ores and metal items twice as fast as a furnace. Crafted from a furnace, iron ingots, and smooth stone.", ["block", "smelting", "ore"]),
  entry("minecraft:smoker", "block", "Smoker", "Cooks food twice as fast as a furnace. Crafted from a furnace and logs.", ["block", "smelting", "food"]),
  entry("minecraft:chest", "block", "Chest", "Stores up to 27 stacks of items. Crafted from 8 wooden planks.", ["block", "storage"]),
  entry("minecraft:barrel", "block", "Barrel", "A storage block that can be opened even when blocks are placed on top. Crafted from wood slabs and planks.", ["block", "storage"]),
  entry("minecraft:ender_chest", "block", "Ender Chest", "A chest whose contents are shared across all ender chests. Crafted from obsidian and an eye of ender.", ["block", "storage", "end"]),
  entry("minecraft:bedrock", "block", "Bedrock", "An indestructible block found at the bottom of the world and in the End and Nether roofs.", ["block", "indestructible"]),
  entry("minecraft:dirt", "block", "Dirt", "A common surface block. Can be tilled into farmland with a hoe.", ["block", "dirt", "farming"]),
  entry("minecraft:grass_block", "block", "Grass Block", "Dirt covered in grass. Common in the Overworld surface. Can be silk-touched.", ["block", "dirt", "grass"]),
  entry("minecraft:farmland", "block", "Farmland", "Dirt tilled with a hoe. Required for growing crops. Turns back to dirt if jumped on.", ["block", "farming"]),
  entry("minecraft:sand", "block", "Sand", "A gravity-affected block found in deserts and beaches. Smelt into glass.", ["block", "sand", "glass"]),
  entry("minecraft:red_sand", "block", "Red Sand", "A red variant of sand found in Badlands biomes. Can be smelted into glass.", ["block", "sand", "badlands"]),
  entry("minecraft:gravel", "block", "Gravel", "A gravity-affected block found underground and on beaches. Drops flint occasionally.", ["block", "gravel", "flint"]),
  entry("minecraft:clay", "block", "Clay", "Found underwater in rivers and lakes. Smelt into bricks or terracotta.", ["block", "clay", "water"]),
  entry("minecraft:terracotta", "block", "Terracotta", "A hardened clay block found in Badlands. Can be dyed into colored variants.", ["block", "building", "decorative"]),
  entry("minecraft:white_wool", "block", "Wool", "Dropped from sheep or crafted from string. Used for beds and decorative blocks.", ["block", "wool", "bed"]),
  entry("minecraft:oak_log", "block", "Oak Log", "Wood from oak trees. Can be crafted into planks and sticks.", ["block", "wood", "building"]),
  entry("minecraft:spruce_log", "block", "Spruce Log", "Wood from spruce trees. Crafted into dark-colored planks.", ["block", "wood", "building"]),
  entry("minecraft:birch_log", "block", "Birch Log", "Light-colored wood from birch trees. Crafted into planks.", ["block", "wood", "building"]),
  entry("minecraft:jungle_log", "block", "Jungle Log", "Wood from jungle trees. Crafted into planks.", ["block", "wood", "building"]),
  entry("minecraft:acacia_log", "block", "Acacia Log", "Wood from acacia trees. Crafted into reddish planks.", ["block", "wood", "building"]),
  entry("minecraft:dark_oak_log", "block", "Dark Oak Log", "Wood from dark oak trees. Crafted into dark planks.", ["block", "wood", "building"]),
  entry("minecraft:mangrove_log", "block", "Mangrove Log", "Wood from mangrove trees found in mangrove swamps.", ["block", "wood", "building"]),
  entry("minecraft:cherry_log", "block", "Cherry Log", "Pink-tinted wood from cherry trees. Crafted into pink planks.", ["block", "wood", "building", "decorative"]),
  entry("minecraft:oak_planks", "block", "Oak Planks", "Basic wooden planks. Used for crafting, sticks, and building.", ["block", "wood", "building"]),
  entry("minecraft:glass", "block", "Glass", "Transparent block made by smelting sand. Used for windows and bottles.", ["block", "glass", "building"]),
  entry("minecraft:torch", "block", "Torch", "Provides light and melts snow nearby. Crafted from coal and a stick.", ["block", "light", "torch"]),
  entry("minecraft:lantern", "block", "Lantern", "A brighter light source than a torch. Crafted from iron nuggets and a torch.", ["block", "light"]),
  entry("minecraft:glowstone", "block", "Glowstone", "A bright light source found in the Nether. Drops glowstone dust.", ["block", "light", "nether"]),
  entry("minecraft:sea_lantern", "block", "Sea Lantern", "A bright underwater light source found in ocean monuments.", ["block", "light", "water"]),
  entry("minecraft:enchanting_table", "block", "Enchanting Table", "Used to enchant tools, weapons, and armor. Requires obsidian, diamonds, and a book.", ["block", "enchanting"]),
  entry("minecraft:anvil", "block", "Anvil", "Used to repair, rename, and combine enchanted items. Crafted from iron blocks and ingots.", ["block", "repair", "enchanting"]),
  entry("minecraft:netherrack", "block", "Netherrack", "The main stone of the Nether. Burns indefinitely when lit.", ["block", "nether", "building"]),
  entry("minecraft:soul_sand", "block", "Soul Sand", "Slows movement and is used for nether wart farms and soul fire. Found in the Nether.", ["block", "nether", "soul_fire"]),
  entry("minecraft:soul_soil", "block", "Soul Soil", "Found in soul sand valleys. Used to create soul fire and soul torches.", ["block", "nether"]),
  entry("minecraft:blackstone", "block", "Blackstone", "A dark stone found in Bastion Remnants. Can be used as a substitute for stone recipes.", ["block", "nether", "building"]),
  entry("minecraft:basalt", "block", "Basalt", "A dark pillar-like block found in the Nether. Can be polished.", ["block", "nether", "building"]),
  entry("minecraft:end_stone", "block", "End Stone", "The main block of the End islands. Requires a pickaxe to mine.", ["block", "end", "building"]),
  entry("minecraft:purpur_block", "block", "Purpur Block", "A decorative block found in End cities. Crafted from popped chorus fruit.", ["block", "end", "decorative"]),
  entry("minecraft:prismarine", "block", "Prismarine", "A sea-themed block found in ocean monuments. Crafted from prismarine shards.", ["block", "water", "ocean"]),
  entry("minecraft:sponge", "block", "Sponge", "Absorbs water in a 7-block radius. Wet sponge can be dried in a furnace.", ["block", "water", "sponge"]),
];

const mobs = () => [
  entry("minecraft:zombie", "mob", "Zombie", "A hostile mob that spawns in dark areas. Burns in sunlight and drops rotten flesh.", ["mob", "hostile", "overworld"]),
  entry("minecraft:skeleton", "mob", "Skeleton", "Shoots arrows and burns in sunlight. Drops bones and arrows.", ["mob", "hostile", "overworld", "ranged"]),
  entry("minecraft:creeper", "mob", "Creeper", "Silently approaches and explodes. Drops gunpowder. Killed by a charged Creeper to drop a music disc.", ["mob", "hostile", "overworld", "explosive"]),
  entry("minecraft:spider", "mob", "Spider", "Hostile at night, neutral in daylight. Climbs walls and drops string and spider eyes.", ["mob", "hostile", "overworld"]),
  entry("minecraft:cave_spider", "mob", "Cave Spider", "A smaller, venomous spider found in mineshafts and strongholds.", ["mob", "hostile", "overworld", "poison"]),
  entry("minecraft:enderman", "mob", "Enderman", "A tall mob that teleports and picks up blocks. Aggressive if looked at. Drops ender pearls.", ["mob", "hostile", "overworld", "end"]),
  entry("minecraft:witch", "mob", "Witch", "Throws splash potions. Spawns in swamps and raids. Drops potion ingredients.", ["mob", "hostile", "overworld", "ranged"]),
  entry("minecraft:slime", "mob", "Slime", "Spawns in swamps and slime chunks. Splits when killed. Drops slime balls.", ["mob", "hostile", "overworld"]),
  entry("minecraft:phantom", "mob", "Phantom", "Flying mob that attacks players who haven't slept. Drops phantom membrane.", ["mob", "hostile", "overworld", "flying"]),
  entry("minecraft:drowned", "mob", "Drowned", "Underwater zombies that can spawn with tridents. Drops copper and rotten flesh.", ["mob", "hostile", "water"]),
  entry("minecraft:husk", "mob", "Husk", "A desert variant of zombie that does not burn in sunlight. Drops rotten flesh.", ["mob", "hostile", "desert"]),
  entry("minecraft:stray", "mob", "Stray", "A skeleton variant found in cold biomes. Shoots arrows of Slowness.", ["mob", "hostile", "cold", "ranged"]),
  entry("minecraft:blaze", "mob", "Blaze", "Found in Nether fortresses. Shoots fireballs. Drops blaze rods.", ["mob", "hostile", "nether", "blaze"]),
  entry("minecraft:ghast", "mob", "Ghast", "Flying Nether mob that shoots explosive fireballs. Drops ghast tears and gunpowder.", ["mob", "hostile", "nether", "ranged"]),
  entry("minecraft:magma_cube", "mob", "Magma Cube", "Nether variant of slime. Splits when killed. Drops magma cream.", ["mob", "hostile", "nether"]),
  entry("minecraft:wither_skeleton", "mob", "Wither Skeleton", "Spawns in Nether fortresses. Inflicts Wither. Drops coal, bones, and rarely skulls.", ["mob", "hostile", "nether"]),
  entry("minecraft:piglin", "mob", "Piglin", "Neutral if wearing gold armor. Hostile if attacked. Barters gold ingots.", ["mob", "neutral", "nether"]),
  entry("minecraft:piglin_brute", "mob", "Piglin Brute", "A stronger hostile Piglin variant found in Bastion Remnants. Always hostile.", ["mob", "hostile", "nether"]),
  entry("minecraft:hoglin", "mob", "Hoglin", "A hostile boar-like mob in the Nether. Drops porkchops and leather.", ["mob", "hostile", "nether"]),
  entry("minecraft:zoglin", "mob", "Zoglin", "A zombified Hoglin. Hostile to most mobs and players.", ["mob", "hostile", "nether"]),
  entry("minecraft:ender_dragon", "mob", "Ender Dragon", "The final boss of Minecraft. Lives in the End. Defeat by destroying crystals then attacking.", ["mob", "boss", "end", "dragon"]),
  entry("minecraft:wither", "mob", "Wither", "A boss spawned with soul sand and skulls. Drops a nether star.", ["mob", "boss", "nether"]),
  entry("minecraft:warden", "mob", "Warden", "A powerful mob spawned by sculk shriekers. Blind but senses vibrations. Avoid if possible.", ["mob", "boss", "deep_dark"]),
  entry("minecraft:iron_golem", "mob", "Iron Golem", "A neutral mob that protects villages. Can be built from iron blocks and a carved pumpkin.", ["mob", "neutral", "village", "golem"]),
  entry("minecraft:snow_golem", "mob", "Snow Golem", "A passive mob built from snow blocks and a carved pumpkin. Throws snowballs at hostile mobs.", ["mob", "passive", "golem"]),
  entry("minecraft:villager", "mob", "Villager", "Passive mob that trades items. Lives in villages. Profession changes with job blocks.", ["mob", "passive", "village", "trading"]),
  entry("minecraft:wandering_trader", "mob", "Wandering Trader", "A villager that spawns randomly and offers rare trades. Leashed to llamas.", ["mob", "passive", "trading"]),
  entry("minecraft:cow", "mob", "Cow", "Passive mob that drops beef and leather. Can be milked with a bucket.", ["mob", "passive", "food", "farm"]),
  entry("minecraft:pig", "mob", "Pig", "Passive mob that drops porkchops. Can be ridden with a saddle and carrot on a stick.", ["mob", "passive", "food", "farm"]),
  entry("minecraft:sheep", "mob", "Sheep", "Passive mob that drops wool and mutton. Can be sheared for wool.", ["mob", "passive", "wool", "farm"]),
  entry("minecraft:chicken", "mob", "Chicken", "Passive mob that drops feathers and raw chicken. Lays eggs.", ["mob", "passive", "food", "farm"]),
  entry("minecraft:rabbit", "mob", "Rabbit", "Small passive mob that drops rabbit hide, meat, and feet. Can be bred with carrots.", ["mob", "passive", "food"]),
  entry("minecraft:mooshroom", "mob", "Mooshroom", "Cow variant found on mushroom islands. Can be milked for mushroom stew or milk.", ["mob", "passive", "food", "mushroom"]),
  entry("minecraft:horse", "mob", "Horse", "Passive mob that can be tamed and ridden. Varies in speed and health.", ["mob", "passive", "transport"]),
  entry("minecraft:donkey", "mob", "Donkey", "Can be tamed, ridden, and equipped with a chest for storage.", ["mob", "passive", "transport", "storage"]),
  entry("minecraft:mule", "mob", "Mule", "Born from a horse and donkey. Can carry a chest and be ridden.", ["mob", "passive", "transport", "storage"]),
  entry("minecraft:llama", "mob", "Llama", "Passive mob that can carry chests and forms caravans. Spits at hostile mobs.", ["mob", "passive", "transport", "storage"]),
  entry("minecraft:wolf", "mob", "Wolf", "Neutral mob that can be tamed with bones. Tamed wolves attack threats to the owner.", ["mob", "neutral", "pet", "combat"]),
  entry("minecraft:cat", "mob", "Cat", "Passive mob that can be tamed with raw fish. Scares creepers and phantoms.", ["mob", "passive", "pet"]),
  entry("minecraft:parrot", "mob", "Parrot", "Passive flying mob that can be tamed and mimics mob sounds.", ["mob", "passive", "pet", "flying"]),
  entry("minecraft:fox", "mob", "Fox", "Nocturnal passive mob that picks up items. Can be bred with sweet berries.", ["mob", "passive"]),
  entry("minecraft:bee", "mob", "Bee", "Flying passive mob that pollinates crops and produces honey. Becomes aggressive if hive is broken.", ["mob", "passive", "flying", "farm"]),
  entry("minecraft:bat", "mob", "Bat", "Flying passive mob that spawns in caves. No useful drops.", ["mob", "passive", "flying", "cave"]),
  entry("minecraft:squid", "mob", "Squid", "Passive water mob that drops ink sacs. Found in oceans and rivers.", ["mob", "passive", "water"]),
  entry("minecraft:glow_squid", "mob", "Glow Squid", "Passive glowing water mob that drops glow ink sacs.", ["mob", "passive", "water"]),
  entry("minecraft:dolphin", "mob", "Dolphin", "Neutral water mob that gives swimmers a speed boost and leads to treasure.", ["mob", "neutral", "water"]),
  entry("minecraft:turtle", "mob", "Turtle", "Passive beach mob that lays eggs on sand. Drops scutes when growing.", ["mob", "passive", "water", "beach"]),
  entry("minecraft:polar_bear", "mob", "Polar Bear", "Neutral mob found in snowy biomes. Protective of cubs.", ["mob", "neutral", "cold"]),
  entry("minecraft:panda", "mob", "Panda", "Neutral mob found in bamboo jungles. Eats bamboo.", ["mob", "neutral", "jungle"]),
  entry("minecraft:ocelot", "mob", "Ocelot", "Passive jungle mob that can be tamed into a cat. Creepers avoid them.", ["mob", "passive", "jungle"]),
  entry("minecraft:trader_llama", "mob", "Trader Llama", "Llamas that follow wandering traders. Can be tamed.", ["mob", "passive", "transport"]),
  entry("minecraft:ravager", "mob", "Ravager", "Large hostile mob that appears in raids. Breaks blocks and deals heavy damage.", ["mob", "hostile", "raid"]),
  entry("minecraft:evoker", "mob", "Evoker", "Hostile illager that summons vexes and fangs. Found in woodland mansions and raids.", ["mob", "hostile", "illager", "raid"]),
  entry("minecraft:vindicator", "mob", "Vindicator", "Hostile illager armed with an axe. Found in mansions and raids.", ["mob", "hostile", "illager", "raid"]),
  entry("minecraft:pillager", "mob", "Pillager", "Hostile illager that shoots crossbows. Found in outposts and raids.", ["mob", "hostile", "illager", "raid"]),
  entry("minecraft:vex", "mob", "Vex", "Small hostile flying mob summoned by evokers. Passes through blocks.", ["mob", "hostile", "illager", "flying"]),
];

const items = () => [
  entry("minecraft:wooden_pickaxe", "item", "Wooden Pickaxe", "Can mine stone and coal ore. Crafted from 3 planks and 2 sticks.", ["item", "tool", "pickaxe", "wood"]),
  entry("minecraft:stone_pickaxe", "item", "Stone Pickaxe", "Can mine iron ore and lapis. Crafted from 3 cobblestone and 2 sticks.", ["item", "tool", "pickaxe", "stone"]),
  entry("minecraft:iron_pickaxe", "item", "Iron Pickaxe", "Can mine diamond ore, redstone, and gold. Crafted from 3 iron ingots and 2 sticks.", ["item", "tool", "pickaxe", "iron"]),
  entry("minecraft:diamond_pickaxe", "item", "Diamond Pickaxe", "Fast, durable pickaxe. Can mine obsidian. Crafted from 3 diamonds and 2 sticks.", ["item", "tool", "pickaxe", "diamond"]),
  entry("minecraft:netherite_pickaxe", "item", "Netherite Pickaxe", "The strongest pickaxe. Crafted by upgrading a diamond pickaxe with a netherite ingot.", ["item", "tool", "pickaxe", "netherite"]),
  entry("minecraft:wooden_axe", "item", "Wooden Axe", "Chops wood faster. Crafted from 3 planks and 2 sticks.", ["item", "tool", "axe", "wood"]),
  entry("minecraft:stone_axe", "item", "Stone Axe", "Basic axe. Crafted from 3 cobblestone and 2 sticks.", ["item", "tool", "axe", "stone"]),
  entry("minecraft:iron_axe", "item", "Iron Axe", "Durable iron axe. Crafted from 3 iron ingots and 2 sticks.", ["item", "tool", "axe", "iron"]),
  entry("minecraft:diamond_axe", "item", "Diamond Axe", "Very fast axe. Crafted from 3 diamonds and 2 sticks.", ["item", "tool", "axe", "diamond"]),
  entry("minecraft:wooden_sword", "item", "Wooden Sword", "Lowest tier sword. Crafted from 2 planks and 1 stick.", ["item", "weapon", "sword", "wood"]),
  entry("minecraft:stone_sword", "item", "Stone Sword", "Basic sword. Crafted from 2 cobblestone and 1 stick.", ["item", "weapon", "sword", "stone"]),
  entry("minecraft:iron_sword", "item", "Iron Sword", "Durable sword. Crafted from 2 iron ingots and 1 stick.", ["item", "weapon", "sword", "iron"]),
  entry("minecraft:diamond_sword", "item", "Diamond Sword", "Fast, durable sword. Crafted from 2 diamonds and 1 stick.", ["item", "weapon", "sword", "diamond"]),
  entry("minecraft:netherite_sword", "item", "Netherite Sword", "The strongest sword. Upgrade a diamond sword with a netherite ingot.", ["item", "weapon", "sword", "netherite"]),
  entry("minecraft:wooden_shovel", "item", "Wooden Shovel", "Basic shovel for dirt and sand. Crafted from 1 plank and 2 sticks.", ["item", "tool", "shovel", "wood"]),
  entry("minecraft:stone_shovel", "item", "Stone Shovel", "Better shovel. Crafted from 1 cobblestone and 2 sticks.", ["item", "tool", "shovel", "stone"]),
  entry("minecraft:iron_shovel", "item", "Iron Shovel", "Durable shovel. Crafted from 1 iron ingot and 2 sticks.", ["item", "tool", "shovel", "iron"]),
  entry("minecraft:diamond_shovel", "item", "Diamond Shovel", "Very fast shovel. Crafted from 1 diamond and 2 sticks.", ["item", "tool", "shovel", "diamond"]),
  entry("minecraft:bow", "item", "Bow", "Ranged weapon that shoots arrows. Crafted from sticks and string.", ["item", "weapon", "ranged"]),
  entry("minecraft:arrow", "item", "Arrow", "Ammo for bows and crossbows. Crafted from flint, stick, and feather.", ["item", "weapon", "ranged", "ammo"]),
  entry("minecraft:crossbow", "item", "Crossbow", "Ranged weapon that can be loaded with arrows. Crafted from sticks, iron, string, and tripwire.", ["item", "weapon", "ranged"]),
  entry("minecraft:shield", "item", "Shield", "Blocks incoming attacks. Crafted from wood planks and an iron ingot.", ["item", "weapon", "defense"]),
  entry("minecraft:leather_helmet", "item", "Leather Helmet", "Basic armor with low protection. Crafted from leather.", ["item", "armor", "leather"]),
  entry("minecraft:iron_helmet", "item", "Iron Helmet", "Mid-tier armor. Crafted from iron ingots.", ["item", "armor", "iron"]),
  entry("minecraft:diamond_helmet", "item", "Diamond Helmet", "High-tier armor. Crafted from diamonds.", ["item", "armor", "diamond"]),
  entry("minecraft:netherite_helmet", "item", "Netherite Helmet", "Best armor. Upgrade diamond helmet with netherite ingot.", ["item", "armor", "netherite"]),
  entry("minecraft:stick", "item", "Stick", "Basic crafting material. Crafted from two planks.", ["item", "material"]),
  entry("minecraft:iron_ingot", "item", "Iron Ingot", "Metal used for tools, armor, and many recipes. Smelted from iron ore.", ["item", "material", "iron"]),
  entry("minecraft:gold_ingot", "item", "Gold Ingot", "Metal used for powered rails, golden apples, and armor. Smelted from gold ore.", ["item", "material", "gold"]),
  entry("minecraft:copper_ingot", "item", "Copper Ingot", "Metal used for lightning rods, telescopes, and building blocks. Smelted from copper ore.", ["item", "material", "copper"]),
  entry("minecraft:diamond", "item", "Diamond", "Rare gem used for the best tools and armor. Found deep underground.", ["item", "material", "diamond"]),
  entry("minecraft:emerald", "item", "Emerald", "Currency used for trading with villagers. Found in mountain biomes and trading.", ["item", "material", "currency"]),
  entry("minecraft:redstone", "item", "Redstone Dust", "Used for circuits, automation, and powered mechanisms.", ["item", "material", "redstone", "circuit"]),
  entry("minecraft:lapis_lazuli", "item", "Lapis Lazuli", "Used for enchanting and blue dye. Mined from lapis ore.", ["item", "material", "dye", "enchanting"]),
  entry("minecraft:coal", "item", "Coal", "Fuel and light source. Mined from coal ore or dropped from Wither skeletons.", ["item", "fuel", "material"]),
  entry("minecraft:charcoal", "item", "Charcoal", "Fuel made by smelting wood. Can be used like coal.", ["item", "fuel", "material"]),
  entry("minecraft:flint", "item", "Flint", "Used for flint and steel and arrows. Dropped from gravel.", ["item", "material"]),
  entry("minecraft:flint_and_steel", "item", "Flint and Steel", "Used to ignite fire, TNT, and nether portals. Crafted from flint and iron ingot.", ["item", "tool", "fire"]),
  entry("minecraft:torch", "item", "Torch", "Provides light. Crafted from coal and a stick.", ["item", "light"]),
  entry("minecraft:bed", "item", "Bed", "Sets spawn point and skips the night. Crafted from wool and planks.", ["item", "bed", "spawn"]),
  entry("minecraft:bucket", "item", "Bucket", "Holds water, lava, milk, or powder snow. Crafted from iron ingots.", ["item", "tool", "container"]),
  entry("minecraft:water_bucket", "item", "Water Bucket", "A bucket filled with water. Used to transport water and make obsidian.", ["item", "tool", "water"]),
  entry("minecraft:lava_bucket", "item", "Lava Bucket", "A bucket filled with lava. Used as furnace fuel and to make obsidian.", ["item", "tool", "lava", "fuel"]),
  entry("minecraft:compass", "item", "Compass", "Points to the world spawn. Crafted from iron ingots and redstone.", ["item", "tool", "navigation"]),
  entry("minecraft:clock", "item", "Clock", "Shows the time of day. Crafted from gold ingots and redstone.", ["item", "tool"]),
  entry("minecraft:map", "item", "Map", "Shows the explored area. Crafted from paper and a compass.", ["item", "tool", "navigation"]),
  entry("minecraft:book", "item", "Book", "Used for bookshelves, enchanted books, and book and quill. Crafted from paper and leather.", ["item", "material"]),
  entry("minecraft:paper", "item", "Paper", "Made from sugar cane. Used for maps and books.", ["item", "material"]),
  entry("minecraft:leather", "item", "Leather", "Dropped from cows and horses. Used for armor and books.", ["item", "material"]),
  entry("minecraft:feather", "item", "Feather", "Dropped from chickens and parrots. Used for arrows and books.", ["item", "material"]),
  entry("minecraft:string", "item", "String", "Dropped from spiders and cave spiders. Used for bows, wool, and tripwire.", ["item", "material"]),
  entry("minecraft:gunpowder", "item", "Gunpowder", "Dropped from creepers, ghasts, and witches. Used for TNT and firework rockets.", ["item", "material", "explosive"]),
  entry("minecraft:bone", "item", "Bone", "Dropped from skeletons. Used for bonemeal and taming wolves.", ["item", "material"]),
  entry("minecraft:bone_meal", "item", "Bone Meal", "Used to speed up crop growth and create white dye. Crafted from bones.", ["item", "material", "farming", "dye"]),
  entry("minecraft:ender_pearl", "item", "Ender Pearl", "Dropped from Endermen. Used to teleport or craft Eyes of Ender.", ["item", "material", "end", "teleport"]),
  entry("minecraft:blaze_rod", "item", "Blaze Rod", "Dropped from Blazes. Used for brewing, blaze powder, and eyes of ender.", ["item", "material", "nether", "brewing"]),
  entry("minecraft:ghast_tear", "item", "Ghast Tear", "Dropped from Ghasts. Used for regeneration potions.", ["item", "material", "nether", "brewing"]),
  entry("minecraft:nether_wart", "item", "Nether Wart", "Grown on soul sand. Base ingredient for most potions.", ["item", "material", "nether", "brewing"]),
  entry("minecraft:sugar_cane", "item", "Sugar Cane", "Grows near water. Used for sugar and paper.", ["item", "material", "farming"]),
  entry("minecraft:wheat", "item", "Wheat", "Grown on farmland. Used for bread and breeding cows.", ["item", "food", "farming"]),
  entry("minecraft:bread", "item", "Bread", "Food item crafted from wheat. Restores hunger.", ["item", "food"]),
  entry("minecraft:carrot", "item", "Carrot", "Grown on farmland. Used for food, breeding pigs, and rabbits.", ["item", "food", "farming"]),
  entry("minecraft:potato", "item", "Potato", "Grown on farmland. Can be baked into a baked potato.", ["item", "food", "farming"]),
  entry("minecraft:beetroot", "item", "Beetroot", "Grown on farmland. Used for beetroot soup and breeding pigs.", ["item", "food", "farming"]),
  entry("minecraft:melon_slice", "item", "Melon Slice", "Food from melons. Can be crafted into glistering melons.", ["item", "food"]),
  entry("minecraft:pumpkin", "item", "Pumpkin", "Grown on farmland. Used for jack o'lanterns, pumpkin pie, and golems.", ["item", "food", "farming"]),
  entry("minecraft:apple", "item", "Apple", "Dropped from oak leaves. Used for golden apples.", ["item", "food"]),
  entry("minecraft:golden_apple", "item", "Golden Apple", "Powerful food that grants absorption and regeneration. Crafted from gold and an apple.", ["item", "food", "combat"]),
  entry("minecraft:enchanted_golden_apple", "item", "Enchanted Golden Apple", "Rare golden apple with strong effects. Found in chests.", ["item", "food", "combat"]),
  entry("minecraft:raw_beef", "item", "Raw Beef", "Dropped from cows. Cook into steak for better hunger restoration.", ["item", "food"]),
  entry("minecraft:cooked_beef", "item", "Steak", "Cooked beef. One of the best food sources.", ["item", "food"]),
  entry("minecraft:raw_porkchop", "item", "Raw Porkchop", "Dropped from pigs and hoglins. Cook into cooked porkchop.", ["item", "food"]),
  entry("minecraft:cooked_porkchop", "item", "Cooked Porkchop", "Cooked pork. Good food source.", ["item", "food"]),
  entry("minecraft:chicken", "item", "Raw Chicken", "Dropped from chickens. May cause hunger. Cook for better results.", ["item", "food"]),
  entry("minecraft:cooked_chicken", "item", "Cooked Chicken", "Cooked chicken. Good food source.", ["item", "food"]),
  entry("minecraft:rotten_flesh", "item", "Rotten Flesh", "Low hunger restoration, may cause hunger. Dropped from zombies.", ["item", "food"]),
  entry("minecraft:spider_eye", "item", "Spider Eye", "Dropped from spiders and witches. Used for brewing poison potions.", ["item", "material", "brewing"]),
  entry("minecraft:poisonous_potato", "item", "Poisonous Potato", "Rare potato drop. Poisons when eaten.", ["item", "food"]),
  entry("minecraft:cod", "item", "Raw Cod", "Fish caught in water. Cook for better food.", ["item", "food", "water"]),
  entry("minecraft:salmon", "item", "Raw Salmon", "Fish caught in cold water. Cook for better food.", ["item", "food", "water"]),
  entry("minecraft:tropical_fish", "item", "Tropical Fish", "Colorful fish caught in warm oceans. No use in crafting.", ["item", "food", "water"]),
  entry("minecraft:pufferfish", "item", "Pufferfish", "Inflating fish. Used for water breathing potions. Poisonous to eat.", ["item", "food", "water", "brewing"]),
];

const recipes = () => [
  { id: "recipe:crafting_table", category: "recipe", name: "Crafting Table", description: "Place 4 wooden planks in a 2x2 square in the inventory crafting grid. Expands the grid to 3x3.", tags: ["recipe", "crafting", "wood"] },
  { id: "recipe:stick", category: "recipe", name: "Stick", description: "Place 2 wooden planks vertically in the crafting grid. Used for tools and torches.", tags: ["recipe", "crafting"] },
  { id: "recipe:torch", category: "recipe", name: "Torch", description: "Place coal above a stick in the crafting grid. Provides light.", tags: ["recipe", "crafting", "light"] },
  { id: "recipe:wooden_pickaxe", category: "recipe", name: "Wooden Pickaxe", description: "3 planks across the top row and 2 sticks vertically in the middle column of a crafting table.", tags: ["recipe", "crafting", "tool"] },
  { id: "recipe:stone_pickaxe", category: "recipe", name: "Stone Pickaxe", description: "3 cobblestone across the top row and 2 sticks vertically in the middle column.", tags: ["recipe", "crafting", "tool"] },
  { id: "recipe:iron_pickaxe", category: "recipe", name: "Iron Pickaxe", description: "3 iron ingots across the top row and 2 sticks vertically in the middle column.", tags: ["recipe", "crafting", "tool"] },
  { id: "recipe:diamond_pickaxe", category: "recipe", name: "Diamond Pickaxe", description: "3 diamonds across the top row and 2 sticks vertically in the middle column.", tags: ["recipe", "crafting", "tool"] },
  { id: "recipe:wooden_axe", category: "recipe", name: "Wooden Axe", description: "3 planks in top-left, top-middle, and middle-left, plus 2 sticks vertically in middle-right.", tags: ["recipe", "crafting", "tool"] },
  { id: "recipe:stone_axe", category: "recipe", name: "Stone Axe", description: "3 cobblestone in top-left, top-middle, and middle-left, plus 2 sticks vertically in middle-right.", tags: ["recipe", "crafting", "tool"] },
  { id: "recipe:iron_axe", category: "recipe", name: "Iron Axe", description: "3 iron ingots in top-left, top-middle, and middle-left, plus 2 sticks vertically in middle-right.", tags: ["recipe", "crafting", "tool"] },
  { id: "recipe:wooden_sword", category: "recipe", name: "Wooden Sword", description: "2 planks in the top-middle and middle-middle, plus 1 stick in the bottom-middle.", tags: ["recipe", "crafting", "weapon"] },
  { id: "recipe:stone_sword", category: "recipe", name: "Stone Sword", description: "2 cobblestone in the top-middle and middle-middle, plus 1 stick in the bottom-middle.", tags: ["recipe", "crafting", "weapon"] },
  { id: "recipe:iron_sword", category: "recipe", name: "Iron Sword", description: "2 iron ingots in the top-middle and middle-middle, plus 1 stick in the bottom-middle.", tags: ["recipe", "crafting", "weapon"] },
  { id: "recipe:diamond_sword", category: "recipe", name: "Diamond Sword", description: "2 diamonds in the top-middle and middle-middle, plus 1 stick in the bottom-middle.", tags: ["recipe", "crafting", "weapon"] },
  { id: "recipe:bucket", category: "recipe", name: "Bucket", description: "3 iron ingots in a V shape in the crafting grid.", tags: ["recipe", "crafting"] },
  { id: "recipe:furnace", category: "recipe", name: "Furnace", description: "8 cobblestone around the edge of the crafting grid, leaving the center empty.", tags: ["recipe", "crafting", "smelting"] },
  { id: "recipe:chest", category: "recipe", name: "Chest", description: "8 wooden planks around the edge of the crafting grid, leaving the center empty.", tags: ["recipe", "crafting", "storage"] },
  { id: "recipe:bed", category: "recipe", name: "Bed", description: "3 wool across the top row and 3 wooden planks across the middle row.", tags: ["recipe", "crafting", "bed"] },
  { id: "recipe:shield", category: "recipe", name: "Shield", description: "6 wood planks in a Y shape plus an iron ingot in the top-middle.", tags: ["recipe", "crafting", "defense"] },
  { id: "recipe:bow", category: "recipe", name: "Bow", description: "3 sticks and 3 string arranged in a U shape with string on the right.", tags: ["recipe", "crafting", "weapon"] },
  { id: "recipe:arrow", category: "recipe", name: "Arrow", description: "Flint on top, stick in middle, feather on bottom.", tags: ["recipe", "crafting", "ammo"] },
  { id: "recipe:paper", category: "recipe", name: "Paper", description: "3 sugar canes horizontally in the crafting grid.", tags: ["recipe", "crafting"] },
  { id: "recipe:book", category: "recipe", name: "Book", description: "3 paper and 1 leather.", tags: ["recipe", "crafting"] },
  { id: "recipe:bookshelf", category: "recipe", name: "Bookshelf", description: "3 books in the middle row and 6 wood planks around them.", tags: ["recipe", "crafting", "enchanting"] },
  { id: "recipe:enchanting_table", category: "recipe", name: "Enchanting Table", description: "4 obsidian on the bottom, 2 diamonds on the sides, 1 book on top.", tags: ["recipe", "crafting", "enchanting"] },
  { id: "recipe:anvil", category: "recipe", name: "Anvil", description: "3 iron blocks across the top row, 1 iron ingot in the center, 3 iron ingots in a line at the bottom.", tags: ["recipe", "crafting", "repair"] },
  { id: "recipe:iron_helmet", category: "recipe", name: "Iron Helmet", description: "5 iron ingots in an upside-down U shape in the crafting grid.", tags: ["recipe", "crafting", "armor"] },
  { id: "recipe:iron_chestplate", category: "recipe", name: "Iron Chestplate", description: "8 iron ingots filling all slots except the top-middle.", tags: ["recipe", "crafting", "armor"] },
  { id: "recipe:iron_leggings", category: "recipe", name: "Iron Leggings", description: "7 iron ingots in a U shape leaving the center and top-middle empty.", tags: ["recipe", "crafting", "armor"] },
  { id: "recipe:iron_boots", category: "recipe", name: "Iron Boots", description: "4 iron ingots in a U shape leaving the top and middle empty.", tags: ["recipe", "crafting", "armor"] },
  { id: "recipe:compass", category: "recipe", name: "Compass", description: "4 iron ingots around redstone in the center.", tags: ["recipe", "crafting"] },
  { id: "recipe:clock", category: "recipe", name: "Clock", description: "4 gold ingots around redstone in the center.", tags: ["recipe", "crafting"] },
  { id: "recipe:flint_and_steel", category: "recipe", name: "Flint and Steel", description: "Flint and iron ingot diagonally in the crafting grid.", tags: ["recipe", "crafting"] },
  { id: "recipe:glass_bottle", category: "recipe", name: "Glass Bottle", description: "3 glass blocks in a V shape.", tags: ["recipe", "crafting", "brewing"] },
  { id: "recipe:brewing_stand", category: "recipe", name: "Brewing Stand", description: "3 cobblestone across the bottom and 1 blaze rod in the center.", tags: ["recipe", "crafting", "brewing"] },
  { id: "recipe:cauldron", category: "recipe", name: "Cauldron", description: "7 iron ingots in a U shape.", tags: ["recipe", "crafting"] },
  { id: "recipe:iron_door", category: "recipe", name: "Iron Door", description: "6 iron ingots in two vertical columns.", tags: ["recipe", "crafting"] },
  { id: "recipe:wooden_door", category: "recipe", name: "Wooden Door", description: "6 wood planks in two vertical columns.", tags: ["recipe", "crafting"] },
  { id: "recipe:trapdoor", category: "recipe", name: "Trapdoor", description: "6 wood planks in two rows of three.", tags: ["recipe", "crafting"] },
  { id: "recipe:fence", category: "recipe", name: "Fence", description: "4 wood planks and 2 sticks in alternating columns.", tags: ["recipe", "crafting"] },
  { id: "recipe:gate", category: "recipe", name: "Fence Gate", description: "2 sticks and 4 wood planks in a gate shape.", tags: ["recipe", "crafting"] },
  { id: "recipe:ladder", category: "recipe", name: "Ladder", description: "7 sticks in a H shape.", tags: ["recipe", "crafting"] },
  { id: "recipe:sign", category: "recipe", name: "Sign", description: "6 wood planks in the top two rows and 1 stick in the bottom-middle.", tags: ["recipe", "crafting"] },
  { id: "recipe:boat", category: "recipe", name: "Boat", description: "5 wood planks in a U shape.", tags: ["recipe", "crafting"] },
  { id: "recipe:minecart", category: "recipe", name: "Minecart", description: "5 iron ingots in a U shape.", tags: ["recipe", "crafting"] },
  { id: "recipe:rail", category: "recipe", name: "Rail", description: "6 iron ingots and 1 stick in a zigzag pattern.", tags: ["recipe", "crafting"] },
  { id: "recipe:powered_rail", category: "recipe", name: "Powered Rail", description: "6 gold ingots, 1 stick, and 1 redstone.", tags: ["recipe", "crafting"] },
  { id: "recipe:detector_rail", category: "recipe", name: "Detector Rail", description: "6 iron ingots, 1 stone pressure plate, and 1 redstone.", tags: ["recipe", "crafting"] },
  { id: "recipe:hopper", category: "recipe", name: "Hopper", description: "5 iron ingots and 1 chest in a V shape.", tags: ["recipe", "crafting"] },
  { id: "recipe:dispenser", category: "recipe", name: "Dispenser", description: "7 cobblestone, 1 bow, and 1 redstone in a U shape with bow in center.", tags: ["recipe", "crafting"] },
  { id: "recipe:dropper", category: "recipe", name: "Dropper", description: "7 cobblestone and 1 redstone in a U shape.", tags: ["recipe", "crafting"] },
  { id: "recipe:piston", category: "recipe", name: "Piston", description: "3 wood planks, 4 cobblestone, 1 iron ingot, and 1 redstone.", tags: ["recipe", "crafting"] },
  { id: "recipe:sticky_piston", category: "recipe", name: "Sticky Piston", description: "1 piston and 1 slime ball.", tags: ["recipe", "crafting"] },
  { id: "recipe:redstone_torch", category: "recipe", name: "Redstone Torch", description: "1 redstone above 1 stick.", tags: ["recipe", "crafting"] },
  { id: "recipe:repeater", category: "recipe", name: "Redstone Repeater", description: "3 stone blocks, 2 redstone torches, and 1 redstone.", tags: ["recipe", "crafting"] },
  { id: "recipe:comparator", category: "recipe", name: "Redstone Comparator", description: "3 stone blocks, 3 redstone torches, and 1 nether quartz.", tags: ["recipe", "crafting"] },
  { id: "recipe:daylight_detector", category: "recipe", name: "Daylight Detector", description: "3 glass, 3 nether quartz, and 3 wood slabs.", tags: ["recipe", "crafting"] },
  { id: "recipe:observer", category: "recipe", name: "Observer", description: "6 cobblestone, 2 redstone, and 1 nether quartz.", tags: ["recipe", "crafting"] },
  { id: "recipe:note_block", category: "recipe", name: "Note Block", description: "8 wood planks around 1 redstone.", tags: ["recipe", "crafting"] },
  { id: "recipe:jukebox", category: "recipe", name: "Jukebox", description: "8 wood planks around 1 diamond.", tags: ["recipe", "crafting"] },
  { id: "recipe:tnt", category: "recipe", name: "TNT", description: "5 gunpowder in an X and 4 sand around them.", tags: ["recipe", "crafting"] },
  { id: "recipe:fire_charge", category: "recipe", name: "Fire Charge", description: "1 coal, 1 gunpowder, and 1 blaze powder.", tags: ["recipe", "crafting"] },
  { id: "recipe:firework_rocket", category: "recipe", name: "Firework Rocket", description: "1 paper and 1 gunpowder. Add firework stars for effects.", tags: ["recipe", "crafting"] },
  { id: "recipe:lead", category: "recipe", name: "Lead", description: "4 string and 1 slime ball.", tags: ["recipe", "crafting"] },
  { id: "recipe:nametag", category: "recipe", name: "Name Tag", description: "Cannot be crafted. Found in chests, fishing, or trading with villagers.", tags: ["recipe", "crafting", "unavailable"] },
  { id: "recipe:saddle", category: "recipe", name: "Saddle", description: "Cannot be crafted. Found in chests, fishing, or trading with villagers.", tags: ["recipe", "crafting", "unavailable"] },
];

const biomes = () => [
  { id: "minecraft:plains", category: "biome", name: "Plains", description: "Flat grasslands with scattered trees and villages. Good for building and farming.", tags: ["biome"] },
  { id: "minecraft:forest", category: "biome", name: "Forest", description: "Overworld biome with many oak and birch trees.", tags: ["biome"] },
  { id: "minecraft:dark_forest", category: "biome", name: "Dark Forest", description: "Dense forest with dark oak trees. Woodland mansions can spawn here.", tags: ["biome"] },
  { id: "minecraft:birch_forest", category: "biome", name: "Birch Forest", description: "Forest dominated by birch trees.", tags: ["biome"] },
  { id: "minecraft:flower_forest", category: "biome", name: "Flower Forest", description: "Forest with many flowers and fewer trees.", tags: ["biome"] },
  { id: "minecraft:taiga", category: "biome", name: "Taiga", description: "Cold forest with spruce trees, foxes, and wolves.", tags: ["biome"] },
  { id: "minecraft:snowy_taiga", category: "biome", name: "Snowy Taiga", description: "Cold taiga covered in snow.", tags: ["biome"] },
  { id: "minecraft:old_growth_pine_taiga", category: "biome", name: "Old Growth Pine Taiga", description: "Taiga with giant spruce trees and podzol ground.", tags: ["biome"] },
  { id: "minecraft:jungle", category: "biome", name: "Jungle", description: "Dense tropical biome with tall trees, vines, and temples.", tags: ["biome"] },
  { id: "minecraft:bamboo_jungle", category: "biome", name: "Bamboo Jungle", description: "Jungle variant filled with bamboo and pandas.", tags: ["biome"] },
  { id: "minecraft:swamp", category: "biome", name: "Swamp", description: "Wet biome with shallow water, oak trees, and witch huts.", tags: ["biome"] },
  { id: "minecraft:mangrove_swamp", category: "biome", name: "Mangrove Swamp", description: "Swamp with mangrove trees, mud, and frogs.", tags: ["biome"] },
  { id: "minecraft:desert", category: "biome", name: "Desert", description: "Dry biome with sand, cacti, and desert pyramids.", tags: ["biome"] },
  { id: "minecraft:savanna", category: "biome", name: "Savanna", description: "Warm grassland with acacia trees and villages.", tags: ["biome"] },
  { id: "minecraft:windswept_savanna", category: "biome", name: "Windswept Savanna", description: "Savanna with extreme terrain and floating islands.", tags: ["biome"] },
  { id: "minecraft:badlands", category: "biome", name: "Badlands", description: "Dry biome with terracotta and gold ore. Mineshafts spawn on the surface.", tags: ["biome"] },
  { id: "minecraft:wooded_badlands", category: "biome", name: "Wooded Badlands", description: "Badlands with patches of oak trees.", tags: ["biome"] },
  { id: "minecraft:meadow", category: "biome", name: "Meadow", description: "High-altitude grassy plain with flowers and rabbits.", tags: ["biome"] },
  { id: "minecraft:grove", category: "biome", name: "Grove", description: "Snowy forest found on mountain slopes.", tags: ["biome"] },
  { id: "minecraft:snowy_slopes", category: "biome", name: "Snowy Slopes", description: "Cold mountain slopes with rabbits and goats.", tags: ["biome"] },
  { id: "minecraft:jagged_peaks", category: "biome", name: "Jagged Peaks", description: "High mountain peaks of stone and snow.", tags: ["biome"] },
  { id: "minecraft:frozen_peaks", category: "biome", name: "Frozen Peaks", description: "High mountain peaks covered in ice and snow.", tags: ["biome"] },
  { id: "minecraft:stony_peaks", category: "biome", name: "Stony Peaks", description: "High mountain peaks made of stone and calcite.", tags: ["biome"] },
  { id: "minecraft:beach", category: "biome", name: "Beach", description: "Sandy area between oceans and land.", tags: ["biome"] },
  { id: "minecraft:snowy_beach", category: "biome", name: "Snowy Beach", description: "Cold beach covered in snow.", tags: ["biome"] },
  { id: "minecraft:river", category: "biome", name: "River", description: "Long stretches of water through the Overworld.", tags: ["biome"] },
  { id: "minecraft:frozen_river", category: "biome", name: "Frozen River", description: "River covered in ice.", tags: ["biome"] },
  { id: "minecraft:ocean", category: "biome", name: "Ocean", description: "Large saltwater biome with fish, kelp, and shipwrecks.", tags: ["biome"] },
  { id: "minecraft:deep_ocean", category: "biome", name: "Deep Ocean", description: "Deeper ocean variant with ocean monuments.", tags: ["biome"] },
  { id: "minecraft:warm_ocean", category: "biome", name: "Warm Ocean", description: "Ocean with coral reefs and tropical fish.", tags: ["biome"] },
  { id: "minecraft:lukewarm_ocean", category: "biome", name: "Lukewarm Ocean", description: "Ocean between warm and cold.", tags: ["biome"] },
  { id: "minecraft:cold_ocean", category: "biome", name: "Cold Ocean", description: "Cold ocean with cod and less life.", tags: ["biome"] },
  { id: "minecraft:frozen_ocean", category: "biome", name: "Frozen Ocean", description: "Ocean with icebergs and polar bears.", tags: ["biome"] },
  { id: "minecraft:mushroom_fields", category: "biome", name: "Mushroom Fields", description: "Rare biome with mooshrooms and giant mushrooms. No hostile mobs spawn.", tags: ["biome"] },
  { id: "minecraft:nether_wastes", category: "biome", name: "Nether Wastes", description: "The main Nether biome with netherrack, lava, and ghasts.", tags: ["biome"] },
  { id: "minecraft:soul_sand_valley", category: "biome", name: "Soul Sand Valley", description: "Nether biome with soul sand, soul soil, and skeletons/ghasts.", tags: ["biome"] },
  { id: "minecraft:crimson_forest", category: "biome", name: "Crimson Forest", description: "Nether forest with crimson trees, hoglins, and piglins.", tags: ["biome"] },
  { id: "minecraft:warped_forest", category: "biome", name: "Warped Forest", description: "Nether forest with warped trees and endermen.", tags: ["biome"] },
  { id: "minecraft:basalt_deltas", category: "biome", name: "Basalt Deltas", description: "Nether biome with basalt pillars, magma cubes, and ghasts.", tags: ["biome"] },
  { id: "minecraft:the_end", category: "biome", name: "The End", description: "Dimension of floating islands and the Ender Dragon.", tags: ["biome"] },
  { id: "minecraft:end_highlands", category: "biome", name: "End Highlands", description: "Outer End islands with chorus plants and end cities.", tags: ["biome"] },
  { id: "minecraft:end_midlands", category: "biome", name: "End Midlands", description: "Transition area between central End and outer islands.", tags: ["biome"] },
  { id: "minecraft:end_barrens", category: "biome", name: "End Barrens", description: "Empty outer End areas with few features.", tags: ["biome"] },
];

const strategy = () => [
  { id: "strategy:mining", category: "strategy", name: "Mining", description: "Dig down carefully with torches, tools, and food. Avoid digging straight down. Use strip mining at diamond levels.", tags: ["strategy"] },
  { id: "strategy:strip_mining", category: "strategy", name: "Strip Mining", description: "Mine long tunnels at Y=-59 to find diamonds. Place torches every 10 blocks and watch for lava.", tags: ["strategy"] },
  { id: "strategy:caving", category: "strategy", name: "Caving", description: "Explore natural caves for exposed ores. Bring plenty of torches, food, and armor.", tags: ["strategy"] },
  { id: "strategy:nether_exploration", category: "strategy", name: "Nether Exploration", description: "Wear gold armor around piglins. Bring fire resistance potions. Build safe paths over lava.", tags: ["strategy"] },
  { id: "strategy:end_fight", category: "strategy", name: "Ender Dragon Fight", description: "Destroy end crystals with arrows or blocks. Attack the dragon when it perches. Bring slow falling potions.", tags: ["strategy"] },
  { id: "strategy:wither_fight", category: "strategy", name: "Wither Fight", description: "Fight underground or in a confined space to limit movement. Use smite enchanted sword and healing potions.", tags: ["strategy"] },
  { id: "strategy:warden_avoid", category: "strategy", name: "Warden Avoidance", description: "Move slowly in the deep dark. Wool blocks reduce vibrations. Use snowballs to distract.", tags: ["strategy"] },
  { id: "strategy:villager_trading", category: "strategy", name: "Villager Trading", description: "Protect villagers with walls and beds. Provide job blocks for trades. Cures zombie villagers for discounts.", tags: ["strategy"] },
  { id: "strategy:farming", category: "strategy", name: "Farming", description: "Plant crops on hydrated farmland. Use bonemeal to speed growth. Keep light level high.", tags: ["strategy"] },
  { id: "strategy:animal_farming", category: "strategy", name: "Animal Farming", description: "Breed animals with their preferred food. Keep them in enclosed pens with water.", tags: ["strategy"] },
  { id: "strategy:defense", category: "strategy", name: "Base Defense", description: "Light the area, build walls, use iron golems, and place traps for hostile mobs.", tags: ["strategy"] },
  { id: "strategy:raids", category: "strategy", name: "Raid Defense", description: "Ring a bell to reveal raiders. Use walls and ranged attacks. Heal between waves.", tags: ["strategy"] },
  { id: "strategy:exploration", category: "strategy", name: "Exploration", description: "Bring food, torches, a bed, and a compass. Mark your path to avoid getting lost.", tags: ["strategy"] },
  { id: "strategy:combat", category: "strategy", name: "Combat Basics", description: "Equip the right weapon and armor. Strafe to avoid attacks. Retreat when low on health.", tags: ["strategy"] },
  { id: "strategy:enchanting", category: "strategy", name: "Enchanting", description: "Build bookshelves around the enchanting table. Use an anvil to combine enchanted books.", tags: ["strategy"] },
  { id: "strategy:brewing", category: "strategy", name: "Brewing", description: "Build a brewing stand with blaze rods. Nether wart is the base for most potions.", tags: ["strategy"] },
  { id: "strategy:smelting", category: "strategy", name: "Smelting", description: "Use furnaces, blast furnaces for ores, and smokers for food. Choose fuel based on availability.", tags: ["strategy"] },
  { id: "strategy:redstone", category: "strategy", name: "Redstone Basics", description: "Power components with redstone dust, torches, and repeaters. Use observers for block detection.", tags: ["strategy"] },
  { id: "strategy:building", category: "strategy", name: "Building", description: "Plan foundations and storage first. Use scaffolding for tall builds. Light interiors.", tags: ["strategy"] },
  { id: "strategy:automation", category: "strategy", name: "Automation", description: "Use hoppers, droppers, dispensers, and observers to create farms, sorters, and mob grinders.", tags: ["strategy"] },
  { id: "strategy:speedrun", category: "strategy", name: "Speedrun", description: "Focus on wood, tools, iron, flint and steel, beds, and eyes of ender. Minimize detours.", tags: ["strategy"] },
  { id: "strategy:resource_management", category: "strategy", name: "Resource Management", description: "Store items in labeled chests. Keep backups of important tools. Use shulker boxes for travel.", tags: ["strategy"] },
  { id: "strategy:preparation", category: "strategy", name: "Preparation", description: "Before a big task, gather food, tools, armor, blocks, potions, and set a spawn point.", tags: ["strategy"] },
  { id: "strategy:recovery", category: "strategy", name: "Recovery", description: "After death, prioritize retrieving items before re-engaging threats. Use a backup set of gear.", tags: ["strategy"] },
  { id: "strategy:multiplayer", category: "strategy", name: "Multiplayer", description: "Coordinate roles, share resources, and establish safe zones. Communicate before risky actions.", tags: ["strategy"] },
];

write("blocks.json", blocks());
write("mobs.json", mobs());
write("items.json", items());
write("recipes.json", recipes());
write("biomes.json", biomes());
write("strategy.json", strategy());
