#!/usr/bin/env python3
"""Generate expanded knowledge JSON files for SmithAI."""
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "SmithAI" / "src" / "main" / "resources" / "knowledge"


def write(name, data):
    path = ROOT / name
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"Wrote {len(data)} entries to {path}")


def blocks():
    entries = [
        ("minecraft:stone", "Stone", "A common solid block found underground. Mined fastest with a pickaxe. Drops cobblestone unless mined with Silk Touch.", ["block", "mining", "building"]),
        ("minecraft:cobblestone", "Cobblestone", "Dropped when mining stone without Silk Touch. Used for tools, furnaces, and building.", ["block", "mining", "building"]),
        ("minecraft:granite", "Granite", "An igneous rock variant of stone. Can be polished for decorative building.", ["block", "mining", "building", "decorative"]),
        ("minecraft:diorite", "Diorite", "A white stone variant. Can be polished for decorative use.", ["block", "mining", "building", "decorative"]),
        ("minecraft:andesite", "Andesite", "A gray stone variant. Can be polished for decorative building.", ["block", "mining", "building", "decorative"]),
        ("minecraft:deepslate", "Deepslate", "A dark stone variant found deep underground. Harder than stone and used for building.", ["block", "mining", "building", "deep"]),
        ("minecraft:cobbled_deepslate", "Cobbled Deepslate", "Drops from mining deepslate. Used for tools and building.", ["block", "mining", "building"]),
        ("minecraft:iron_ore", "Iron Ore", "Iron ore is found underground, usually between Y=-64 and Y=72. Requires a stone pickaxe or better. Smelt it to get iron ingots.", ["block", "mining", "ore", "iron"]),
        ("minecraft:deepslate_iron_ore", "Deepslate Iron Ore", "Iron ore embedded in deepslate. Requires a stone pickaxe or better. Drops iron ore.", ["block", "mining", "ore", "iron"]),
        ("minecraft:gold_ore", "Gold Ore", "Gold ore is found underground around Y=-16 and abundantly in Badlands. Requires an iron pickaxe or better. Smelt to get gold ingots.", ["block", "mining", "ore", "gold"]),
        ("minecraft:deepslate_gold_ore", "Deepslate Gold Ore", "Gold ore embedded in deepslate. Requires an iron pickaxe or better.", ["block", "mining", "ore", "gold"]),
        ("minecraft:diamond_ore", "Diamond Ore", "Diamond ore is found deep underground, most commonly around Y=-59. Requires an iron pickaxe or better. Drops diamonds.", ["block", "mining", "ore", "diamond"]),
        ("minecraft:deepslate_diamond_ore", "Deepslate Diamond Ore", "Diamond ore embedded in deepslate. Requires an iron pickaxe or better.", ["block", "mining", "ore", "diamond"]),
        ("minecraft:coal_ore", "Coal Ore", "Coal ore is common underground and in mountains. Mined with any pickaxe. Drops coal for torches and fuel.", ["block", "mining", "ore", "coal", "fuel"]),
        ("minecraft:deepslate_coal_ore", "Deepslate Coal Ore", "Coal ore embedded in deepslate. Mined with any pickaxe. Drops coal.", ["block", "mining", "ore", "coal", "fuel"]),
        ("minecraft:redstone_ore", "Redstone Ore", "Redstone ore is found deep underground. Requires an iron pickaxe or better. Drops redstone dust.", ["block", "mining", "ore", "redstone"]),
        ("minecraft:lapis_ore", "Lapis Lazuli Ore", "Lapis ore is found underground. Requires a stone pickaxe or better. Drops lapis lazuli.", ["block", "mining", "ore", "lapis"]),
        ("minecraft:copper_ore", "Copper Ore", "Copper ore generates in larger ore blobs underground. Requires a stone pickaxe or better. Smelt into copper ingots.", ["block", "mining", "ore", "copper"]),
        ("minecraft:emerald_ore", "Emerald Ore", "Emerald ore is found in mountain biomes. Requires an iron pickaxe or better. Drops emeralds.", ["block", "mining", "ore", "emerald"]),
        ("minecraft:obsidian", "Obsidian", "Created when water touches a lava source. Requires a diamond or netherite pickaxe. Used for nether portals and enchanting tables.", ["block", "mining", "portal", "enchanting"]),
        ("minecraft:crafting_table", "Crafting Table", "Expands the crafting grid to 3x3. Crafted from 4 wooden planks.", ["block", "crafting"]),
        ("minecraft:furnace", "Furnace", "Smelts ores, food, and other items using fuel. Crafted from 8 cobblestone.", ["block", "smelting", "fuel"]),
        ("minecraft:blast_furnace", "Blast Furnace", "Smelts ores and metal items twice as fast as a furnace. Crafted from a furnace, iron ingots, and smooth stone.", ["block", "smelting", "ore"]),
        ("minecraft:smoker", "Smoker", "Cooks food twice as fast as a furnace. Crafted from a furnace and logs.", ["block", "smelting", "food"]),
        ("minecraft:chest", "Chest", "Stores up to 27 stacks of items. Crafted from 8 wooden planks.", ["block", "storage"]),
        ("minecraft:double_chest", "Double Chest", "Two chests placed side by side share 54 slots of storage.", ["block", "storage"]),
        ("minecraft:barrel", "Barrel", "A storage block that can be opened even when blocks are placed on top. Crafted from wood slabs and planks.", ["block", "storage"]),
        ("minecraft:ender_chest", "Ender Chest", "A chest whose contents are shared across all ender chests. Crafted from obsidian and an eye of ender.", ["block", "storage", "end"]),
        ("minecraft:bedrock", "Bedrock", "An indestructible block found at the bottom of the world and in the End and Nether roofs.", ["block", "indestructible"]),
        ("minecraft:dirt", "Dirt", "A common surface block. Can be tilled into farmland with a hoe.", ["block", "dirt", "farming"]),
        ("minecraft:grass_block", "Grass Block", "Dirt covered in grass. Common in the Overworld surface. Can be silk-touched.", ["block", "dirt", "grass"]),
        ("minecraft:farmland", "Farmland", "Dirt tilled with a hoe. Required for growing crops. Turns back to dirt if jumped on.", ["block", "farming"]),
        ("minecraft:sand", "Sand", "A gravity-affected block found in deserts and beaches. Smelt into glass.", ["block", "sand", "glass"]),
        ("minecraft:red_sand", "Red Sand", "A red variant of sand found in Badlands biomes. Can be smelted into glass.", ["block", "sand", "badlands"]),
        ("minecraft:gravel", "Gravel", "A gravity-affected block found underground and on beaches. Drops flint occasionally.", ["block", "gravel", "flint"]),
        ("minecraft:clay", "Clay", "Found underwater in rivers and lakes. Smelt into bricks or terracotta.", ["block", "clay", "water"]),
        ("minecraft:terracotta", "Terracotta", "A hardened clay block found in Badlands. Can be dyed into colored variants.", ["block", "building", "decorative"]),
        ("minecraft:white_wool", "Wool", "Dropped from sheep or crafted from string. Used for beds and decorative blocks.", ["block", "wool", "bed"]),
        ("minecraft:oak_log", "Oak Log", "Wood from oak trees. Can be crafted into planks and sticks.", ["block", "wood", "building"]),
        ("minecraft:spruce_log", "Spruce Log", "Wood from spruce trees. Crafted into dark-colored planks.", ["block", "wood", "building"]),
        ("minecraft:birch_log", "Birch Log", "Light-colored wood from birch trees. Crafted into planks.", ["block", "wood", "building"]),
        ("minecraft:jungle_log", "Jungle Log", "Wood from jungle trees. Crafted into planks.", ["block", "wood", "building"]),
        ("minecraft:acacia_log", "Acacia Log", "Wood from acacia trees. Crafted into reddish planks.", ["block", "wood", "building"]),
        ("minecraft:dark_oak_log", "Dark Oak Log", "Wood from dark oak trees. Crafted into dark planks.", ["block", "wood", "building"]),
        ("minecraft:mangrove_log", "Mangrove Log", "Wood from mangrove trees found in mangrove swamps.", ["block", "wood", "building"]),
        ("minecraft:cherry_log", "Cherry Log", "Pink-tinted wood from cherry trees. Crafted into pink planks.", ["block", "wood", "building", "decorative"]),
        ("minecraft:oak_planks", "Oak Planks", "Basic wooden planks. Used for crafting, sticks, and building.", ["block", "wood", "building"]),
        ("minecraft:glass", "Glass", "Transparent block made by smelting sand. Used for windows and bottles.", ["block", "glass", "building"]),
        ("minecraft:torch", "Torch", "Provides light and melts snow nearby. Crafted from coal and a stick.", ["block", "light", "torch"]),
        ("minecraft:lantern", "Lantern", "A brighter light source than a torch. Crafted from iron nuggets and a torch.", ["block", "light"]),
        ("minecraft:glowstone", "Glowstone", "A bright light source found in the Nether. Drops glowstone dust.", ["block", "light", "nether"]),
        ("minecraft:sea_lantern", "Sea Lantern", "A bright underwater light source found in ocean monuments.", ["block", "light", "water"]),
        ("minecraft:enchanting_table", "Enchanting Table", "Used to enchant tools, weapons, and armor. Requires obsidian, diamonds, and a book.", ["block", "enchanting"]),
        ("minecraft:anvil", "Anvil", "Used to repair, rename, and combine enchanted items. Crafted from iron blocks and ingots.", ["block", "repair", "enchanting"]),
        ("minecraft:gravel", "Gravel", "A gravity-affected block. Drops flint occasionally when mined.", ["block", "gravel"]),
        ("minecraft:netherrack", "Netherrack", "The main stone of the Nether. Burns indefinitely when lit.", ["block", "nether", "building"]),
        ("minecraft:soul_sand", "Soul Sand", "Slows movement and is used for nether wart farms and soul fire. Found in the Nether.", ["block", "nether", "soul_fire"]),
        ("minecraft:soul_soil", "Soul Soil", "Found in soul sand valleys. Used to create soul fire and soul torches.", ["block", "nether"]),
        ("minecraft:blackstone", "Blackstone", "A dark stone found in Bastion Remnants. Can be used as a substitute for stone recipes.", ["block", "nether", "building"]),
        ("minecraft:basalt", "Basalt", "A dark pillar-like block found in the Nether. Can be polished.", ["block", "nether", "building"]),
        ("minecraft:end_stone", "End Stone", "The main block of the End islands. Requires a pickaxe to mine.", ["block", "end", "building"]),
        ("minecraft:purpur_block", "Purpur Block", "A decorative block found in End cities. Crafted from popped chorus fruit.", ["block", "end", "decorative"]),
        ("minecraft:prismarine", "Prismarine", "A sea-themed block found in ocean monuments. Crafted from prismarine shards.", ["block", "water", "ocean"]),
        ("minecraft:sponge", "Sponge", "Absorbs water in a 7-block radius. Wet sponge can be dried in a furnace.", ["block", "water", "sponge"]),
    ]
    return [{"id": e[0], "category": "block", "name": e[1], "description": e[2], "tags": e[3]} for e in entries]


def mobs():
    entries = [
        ("minecraft:zombie", "Zombie", "A hostile mob that spawns in dark areas. Burns in sunlight and drops rotten flesh.", ["mob", "hostile", "overworld"]),
        ("minecraft:skeleton", "Skeleton", "Shoots arrows and burns in sunlight. Drops bones and arrows.", ["mob", "hostile", "overworld", "ranged"]),
        ("minecraft:creeper", "Creeper", "Silently approaches and explodes. Drops gunpowder. Killed by a charged Creeper to drop a music disc.", ["mob", "hostile", "overworld", "explosive"]),
        ("minecraft:spider", "Spider", "Hostile at night, neutral in daylight. Climbs walls and drops string and spider eyes.", ["mob", "hostile", "overworld"]),
        ("minecraft:cave_spider", "Cave Spider", "A smaller, venomous spider found in mineshafts and strongholds.", ["mob", "hostile", "overworld", "poison"]),
        ("minecraft:enderman", "Enderman", "A tall mob that teleports and picks up blocks. Aggressive if looked at. Drops ender pearls.", ["mob", "hostile", "overworld", "end"]),
        ("minecraft:witch", "Witch", "Throws splash potions. Spawns in swamps and raids. Drops potion ingredients.", ["mob", "hostile", "overworld", "ranged"]),
        ("minecraft:slime", "Slime", "Spawns in swamps and slime chunks. Splits when killed. Drops slime balls.", ["mob", "hostile", "overworld"]),
        ("minecraft:phantom", "Phantom", "Flying mob that attacks players who haven't slept. Drops phantom membrane.", ["mob", "hostile", "overworld", "flying"]),
        ("minecraft:drowned", "Drowned", "Underwater zombies that can spawn with tridents. Drops copper and rotten flesh.", ["mob", "hostile", "water"]),
        ("minecraft:husk", "Husk", "A desert variant of zombie that does not burn in sunlight. Drops rotten flesh.", ["mob", "hostile", "desert"]),
        ("minecraft:stray", "Stray", "A skeleton variant found in cold biomes. Shoots arrows of Slowness.", ["mob", "hostile", "cold", "ranged"]),
        ("minecraft:blaze", "Blaze", "Found in Nether fortresses. Shoots fireballs. Drops blaze rods.", ["mob", "hostile", "nether", "blaze"]),
        ("minecraft:ghast", "Ghast", "Flying Nether mob that shoots explosive fireballs. Drops ghast tears and gunpowder.", ["mob", "hostile", "nether", "ranged"]),
        ("minecraft:magma_cube", "Magma Cube", "Nether variant of slime. Splits when killed. Drops magma cream.", ["mob", "hostile", "nether"]),
        ("minecraft:wither_skeleton", "Wither Skeleton", "Spawns in Nether fortresses. Inflicts Wither. Drops coal, bones, and rarely skulls.", ["mob", "hostile", "nether"]),
        ("minecraft:piglin", "Piglin", "Neutral if wearing gold armor. Hostile if attacked. Barters gold ingots.", ["mob", "neutral", "nether"]),
        ("minecraft:piglin_brute", "Piglin Brute", "A stronger hostile Piglin variant found in Bastion Remnants. Always hostile.", ["mob", "hostile", "nether"]),
        ("minecraft:hoglin", "Hoglin", "A hostile boar-like mob in the Nether. Drops porkchops and leather.", ["mob", "hostile", "nether"]),
        ("minecraft:zoglin", "Zoglin", "A zombified Hoglin. Hostile to most mobs and players.", ["mob", "hostile", "nether"]),
        ("minecraft:ender_dragon", "Ender Dragon", "The final boss of Minecraft. Lives in the End. Defeat by destroying crystals then attacking.", ["mob", "boss", "end", "dragon"]),
        ("minecraft:wither", "Wither", "A boss spawned with soul sand and skulls. Drops a nether star.", ["mob", "boss", "nether"]),
        ("minecraft:warden", "Warden", "A powerful mob spawned by sculk shriekers. Blind but senses vibrations. Avoid if possible.", ["mob", "boss", "deep_dark"]),
        ("minecraft:iron_golem", "Iron Golem", "A neutral mob that protects villages. Can be built from iron blocks and a carved pumpkin.", ["mob", "neutral", "village", "golem"]),
        ("minecraft:snow_golem", "Snow Golem", "A passive mob built from snow blocks and a carved pumpkin. Throws snowballs at hostile mobs.", ["mob", "passive", "golem"]),
        ("minecraft:villager", "Villager", "Passive mob that trades items. Lives in villages. Profession changes with job blocks.", ["mob", "passive", "village", "trading"]),
        ("minecraft:wandering_trader", "Wandering Trader", "A villager that spawns randomly and offers rare trades. Leashed to llamas.", ["mob", "passive", "trading"]),
        ("minecraft:cow", "Cow", "Passive mob that drops beef and leather. Can be milked with a bucket.", ["mob", "passive", "food", "farm"]),
        ("minecraft:pig", "Pig", "Passive mob that drops porkchops. Can be ridden with a saddle and carrot on a stick.", ["mob", "passive", "food", "farm"]),
        ("minecraft:sheep", "Sheep", "Passive mob that drops wool and mutton. Can be sheared for wool.", ["mob", "passive", "wool", "farm"]),
        ("minecraft:chicken", "Chicken", "Passive mob that drops feathers and raw chicken. Lays eggs.", ["mob", "passive", "food", "farm"]),
        ("minecraft:rabbit", "Rabbit", "Small passive mob that drops rabbit hide, meat, and feet. Can be bred with carrots.", ["mob", "passive", "food"]),
        ("minecraft:mooshroom", "Mooshroom", "Cow variant found on mushroom islands. Can be milked for mushroom stew or milk.", ["mob", "passive", "food", "mushroom"]),
        ("minecraft:horse", "Horse", "Passive mob that can be tamed and ridden. Varies in speed and health.", ["mob", "passive", "transport"]),
        ("minecraft:donkey", "Donkey", "Can be tamed, ridden, and equipped with a chest for storage.", ["mob", "passive", "transport", "storage"]),
        ("minecraft:mule", "Mule", "Born from a horse and donkey. Can carry a chest and be ridden.", ["mob", "passive", "transport", "storage"]),
        ("minecraft:llama", "Llama", "Passive mob that can carry chests and forms caravans. Spits at hostile mobs.", ["mob", "passive", "transport", "storage"]),
        ("minecraft:wolf", "Wolf", "Neutral mob that can be tamed with bones. Tamed wolves attack threats to the owner.", ["mob", "neutral", "pet", "combat"]),
        ("minecraft:cat", "Cat", "Passive mob that can be tamed with raw fish. Scares creepers and phantoms.", ["mob", "passive", "pet"]),
        ("minecraft:parrot", "Parrot", "Passive flying mob that can be tamed and mimics mob sounds.", ["mob", "passive", "pet", "flying"]),
        ("minecraft:fox", "Fox", "Nocturnal passive mob that picks up items. Can be bred with sweet berries.", ["mob", "passive"]),
        ("minecraft:bee", "Bee", "Flying passive mob that pollinates crops and produces honey. Becomes aggressive if hive is broken.", ["mob", "passive", "flying", "farm"]),
        ("minecraft:bat", "Bat", "Flying passive mob that spawns in caves. No useful drops.", ["mob", "passive", "flying", "cave"]),
        ("minecraft:squid", "Squid", "Passive water mob that drops ink sacs. Found in oceans and rivers.", ["mob", "passive", "water"]),
        ("minecraft:glow_squid", "Glow Squid", "Passive glowing water mob that drops glow ink sacs.", ["mob", "passive", "water"]),
        ("minecraft:dolphin", "Dolphin", "Neutral water mob that gives swimmers a speed boost and leads to treasure.", ["mob", "neutral", "water"]),
        ("minecraft:turtle", "Turtle", "Passive beach mob that lays eggs on sand. Drops scutes when growing.", ["mob", "passive", "water", "beach"]),
        ("minecraft:polar_bear", "Polar Bear", "Neutral mob found in snowy biomes. Protective of cubs.", ["mob", "neutral", "cold"]),
        ("minecraft:panda", "Panda", "Neutral mob found in bamboo jungles. Eats bamboo.", ["mob", "neutral", "jungle"]),
        ("minecraft:ocelot", "Ocelot", "Passive jungle mob that can be tamed into a cat. Creepers avoid them.", ["mob", "passive", "jungle"]),
        ("minecraft:trader_llama", "Trader Llama", "Llamas that follow wandering traders. Can be tamed.", ["mob", "passive", "transport"]),
        ("minecraft:ravager", "Ravager", "Large hostile mob that appears in raids. Breaks blocks and deals heavy damage.", ["mob", "hostile", "raid"]),
        ("minecraft:evoker", "Evoker", "Hostile illager that summons vexes and fangs. Found in woodland mansions and raids.", ["mob", "hostile", "illager", "raid"]),
        ("minecraft:vindicator", "Vindicator", "Hostile illager armed with an axe. Found in mansions and raids.", ["mob", "hostile", "illager", "raid"]),
        ("minecraft:pillager", "Pillager", "Hostile illager that shoots crossbows. Found in outposts and raids.", ["mob", "hostile", "illager", "raid"]),
        ("minecraft:vex", "Vex", "Small hostile flying mob summoned by evokers. Passes through blocks.", ["mob", "hostile", "illager", "flying"]),
    ]
    return [{"id": e[0], "category": "mob", "name": e[1], "description": e[2], "tags": e[3]} for e in entries]


def items():
    entries = [
        ("minecraft:wooden_pickaxe", "Wooden Pickaxe", "Can mine stone and coal ore. Crafted from 3 planks and 2 sticks.", ["item", "tool", "pickaxe", "wood"]),
        ("minecraft:stone_pickaxe", "Stone Pickaxe", "Can mine iron ore and lapis. Crafted from 3 cobblestone and 2 sticks.", ["item", "tool", "pickaxe", "stone"]),
        ("minecraft:iron_pickaxe", "Iron Pickaxe", "Can mine diamond ore, redstone, and gold. Crafted from 3 iron ingots and 2 sticks.", ["item", "tool", "pickaxe", "iron"]),
        ("minecraft:diamond_pickaxe", "Diamond Pickaxe", "Fast, durable pickaxe. Can mine obsidian. Crafted from 3 diamonds and 2 sticks.", ["item", "tool", "pickaxe", "diamond"]),
        ("minecraft:netherite_pickaxe", "Netherite Pickaxe", "The strongest pickaxe. Crafted by upgrading a diamond pickaxe with a netherite ingot.", ["item", "tool", "pickaxe", "netherite"]),
        ("minecraft:wooden_axe", "Wooden Axe", "Chops wood faster. Crafted from 3 planks and 2 sticks.", ["item", "tool", "axe", "wood"]),
        ("minecraft:stone_axe", "Stone Axe", "Basic axe. Crafted from 3 cobblestone and 2 sticks.", ["item", "tool", "axe", "stone"]),
        ("minecraft:iron_axe", "Iron Axe", "Durable iron axe. Crafted from 3 iron ingots and 2 sticks.", ["item", "tool", "axe", "iron"]),
        ("minecraft:diamond_axe", "Diamond Axe", "Very fast axe. Crafted from 3 diamonds and 2 sticks.", ["item", "tool", "axe", "diamond"]),
        ("minecraft:wooden_sword", "Wooden Sword", "Lowest tier sword. Crafted from 2 planks and 1 stick.", ["item", "weapon", "sword", "wood"]),
        ("minecraft:stone_sword", "Stone Sword", "Basic sword. Crafted from 2 cobblestone and 1 stick.", ["item", "weapon", "sword", "stone"]),
        ("minecraft:iron_sword", "Iron Sword", "Durable sword. Crafted from 2 iron ingots and 1 stick.", ["item", "weapon", "sword", "iron"]),
        ("minecraft:diamond_sword", "Diamond Sword", "Fast, durable sword. Crafted from 2 diamonds and 1 stick.", ["item", "weapon", "sword", "diamond"]),
        ("minecraft:netherite_sword", "Netherite Sword", "The strongest sword. Upgrade a diamond sword with a netherite ingot.", ["item", "weapon", "sword", "netherite"]),
        ("minecraft:wooden_shovel", "Wooden Shovel", "Basic shovel for dirt and sand. Crafted from 1 plank and 2 sticks.", ["item", "tool", "shovel", "wood"]),
        ("minecraft:stone_shovel", "Stone Shovel", "Better shovel. Crafted from 1 cobblestone and 2 sticks.", ["item", "tool", "shovel", "stone"]),
        ("minecraft:iron_shovel", "Iron Shovel", "Durable shovel. Crafted from 1 iron ingot and 2 sticks.", ["item", "tool", "shovel", "iron"]),
        ("minecraft:diamond_shovel", "Diamond Shovel", "Very fast shovel. Crafted from 1 diamond and 2 sticks.", ["item", "tool", "shovel", "diamond"]),
        ("minecraft:bow", "Bow", "Ranged weapon that shoots arrows. Crafted from sticks and string.", ["item", "weapon", "ranged"]),
        ("minecraft:arrow", "Arrow", "Ammo for bows and crossbows. Crafted from flint, stick, and feather.", ["item", "weapon", "ranged", "ammo"]),
        ("minecraft:crossbow", "Crossbow", "Ranged weapon that can be loaded with arrows. Crafted from sticks, iron, string, and tripwire.", ["item", "weapon", "ranged"]),
        ("minecraft:shield", "Shield", "Blocks incoming attacks. Crafted from wood planks and an iron ingot.", ["item", "weapon", "defense"]),
        ("minecraft:leather_helmet", "Leather Helmet", "Basic armor with low protection. Crafted from leather.", ["item", "armor", "leather"]),
        ("minecraft:iron_helmet", "Iron Helmet", "Mid-tier armor. Crafted from iron ingots.", ["item", "armor", "iron"]),
        ("minecraft:diamond_helmet", "Diamond Helmet", "High-tier armor. Crafted from diamonds.", ["item", "armor", "diamond"]),
        ("minecraft:netherite_helmet", "Netherite Helmet", "Best armor. Upgrade diamond helmet with netherite ingot.", ["item", "armor", "netherite"]),
        ("minecraft:stick", "Stick", "Basic crafting material. Crafted from two planks.", ["item", "material"]),
        ("minecraft:iron_ingot", "Iron Ingot", "Metal used for tools, armor, and many recipes. Smelted from iron ore.", ["item", "material", "iron"]),
        ("minecraft:gold_ingot", "Gold Ingot", "Metal used for powered rails, golden apples, and armor. Smelted from gold ore.", ["item", "material", "gold"]),
        ("minecraft:copper_ingot", "Copper Ingot", "Metal used for lightning rods, telescopes, and building blocks. Smelted from copper ore.", ["item", "material", "copper"]),
        ("minecraft:diamond", "Diamond", "Rare gem used for the best tools and armor. Found deep underground.", ["item", "material", "diamond"]),
        ("minecraft:emerald", "Emerald", "Currency used for trading with villagers. Found in mountain biomes and trading.", ["item", "material", "currency"]),
        ("minecraft:redstone", "Redstone Dust", "Used for circuits, automation, and powered mechanisms.", ["item", "material", "redstone", "circuit"]),
        ("minecraft:lapis_lazuli", "Lapis Lazuli", "Used for enchanting and blue dye. Mined from lapis ore.", ["item", "material", "dye", "enchanting"]),
        ("minecraft:coal", "Coal", "Fuel and light source. Mined from coal ore or dropped from Wither skeletons.", ["item", "fuel", "material"]),
        ("minecraft:charcoal", "Charcoal", "Fuel made by smelting wood. Can be used like coal.", ["item", "fuel", "material"]),
        ("minecraft:flint", "Flint", "Used for flint and steel and arrows. Dropped from gravel.", ["item", "material"]),
        ("minecraft:flint_and_steel", "Flint and Steel", "Used to ignite fire, TNT, and nether portals. Crafted from flint and iron ingot.", ["item", "tool", "fire"]),
        ("minecraft:torch", "Torch", "Provides light. Crafted from coal and a stick.", ["item", "light"]),
        ("minecraft:bed", "Bed", "Sets spawn point and skips the night. Crafted from wool and planks.", ["item", "bed", "spawn"]),
        ("minecraft:bucket", "Bucket", "Holds water, lava, milk, or powder snow. Crafted from iron ingots.", ["item", "tool", "container"]),
        ("minecraft:water_bucket", "Water Bucket", "A bucket filled with water. Used to transport water and make obsidian.", ["item", "tool", "water"]),
        ("minecraft:lava_bucket", "Lava Bucket", "A bucket filled with lava. Used as furnace fuel and to make obsidian.", ["item", "tool", "lava", "fuel"]),
        ("minecraft:compass", "Compass", "Points to the world spawn. Crafted from iron ingots and redstone.", ["item", "tool", "navigation"]),
        ("minecraft:clock", "Clock", "Shows the time of day. Crafted from gold ingots and redstone.", ["item", "tool"]),
        ("minecraft:map", "Map", "Shows the explored area. Crafted from paper and a compass.", ["item", "tool", "navigation"]),
        ("minecraft:book", "Book", "Used for bookshelves, enchanted books, and book and quill. Crafted from paper and leather.", ["item", "material"]),
        ("minecraft:paper", "Paper", "Made from sugar cane. Used for maps and books.", ["item", "material"]),
        ("minecraft:leather", "Leather", "Dropped from cows and horses. Used for armor and books.", ["item", "material"]),
        ("minecraft:feather", "Feather", "Dropped from chickens and parrots. Used for arrows and books.", ["item", "material"]),
        ("minecraft:string", "String", "Dropped from spiders and cave spiders. Used for bows, wool, and tripwire.", ["item", "material"]),
        ("minecraft:gunpowder", "Gunpowder", "Dropped from creepers, ghasts, and witches. Used for TNT and firework rockets.", ["item", "material", "explosive"]),
        ("minecraft:bone", "Bone", "Dropped from skeletons. Used for bonemeal and taming wolves.", ["item", "material"]),
        ("minecraft:bone_meal", "Bone Meal", "Used to speed up crop growth and create white dye. Crafted from bones.", ["item", "material", "farming", "dye"]),
        ("minecraft:ender_pearl", "Ender Pearl", "Dropped from Endermen. Used to teleport or craft Eyes of Ender.", ["item", "material", "end", "teleport"]),
        ("minecraft:blaze_rod", "Blaze Rod", "Dropped from Blazes. Used for brewing, blaze powder, and eyes of ender.", ["item", "material", "nether", "brewing"]),
        ("minecraft:ghast_tear", "Ghast Tear", "Dropped from Ghasts. Used for regeneration potions.", ["item", "material", "nether", "brewing"]),
        ("minecraft:nether_wart", "Nether Wart", "Grown on soul sand. Base ingredient for most potions.", ["item", "material", "nether", "brewing"]),
        ("minecraft:sugar_cane", "Sugar Cane", "Grows near water. Used for sugar and paper.", ["item", "material", "farming"]),
        ("minecraft:wheat", "Wheat", "Grown on farmland. Used for bread and breeding cows.", ["item", "food", "farming"]),
        ("minecraft:bread", "Bread", "Food item crafted from wheat. Restores hunger.", ["item", "food"]),
        ("minecraft:carrot", "Carrot", "Grown on farmland. Used for food, breeding pigs, and rabbits.", ["item", "food", "farming"]),
        ("minecraft:potato", "Potato", "Grown on farmland. Can be baked into a baked potato.", ["item", "food", "farming"]),
        ("minecraft:beetroot", "Beetroot", "Grown on farmland. Used for beetroot soup and breeding pigs.", ["item", "food", "farming"]),
        ("minecraft:melon_slice", "Melon Slice", "Food from melons. Can be crafted into glistering melons.", ["item", "food"]),
        ("minecraft:pumpkin", "Pumpkin", "Grown on farmland. Used for jack o'lanterns, pumpkin pie, and golems.", ["item", "food", "farming"]),
        ("minecraft:apple", "Apple", "Dropped from oak leaves. Used for golden apples.", ["item", "food"]),
        ("minecraft:golden_apple", "Golden Apple", "Powerful food that grants absorption and regeneration. Crafted from gold and an apple.", ["item", "food", "combat"]),
        ("minecraft:enchanted_golden_apple", "Enchanted Golden Apple", "Rare golden apple with strong effects. Found in chests.", ["item", "food", "combat"]),
        ("minecraft:raw_beef", "Raw Beef", "Dropped from cows. Cook into steak for better hunger restoration.", ["item", "food"]),
        ("minecraft:cooked_beef", "Steak", "Cooked beef. One of the best food sources.", ["item", "food"]),
        ("minecraft:raw_porkchop", "Raw Porkchop", "Dropped from pigs and hoglins. Cook into cooked porkchop.", ["item", "food"]),
        ("minecraft:cooked_porkchop", "Cooked Porkchop", "Cooked pork. Good food source.", ["item", "food"]),
        ("minecraft:chicken", "Raw Chicken", "Dropped from chickens. May cause hunger. Cook for better results.", ["item", "food"]),
        ("minecraft:cooked_chicken", "Cooked Chicken", "Cooked chicken. Good food source.", ["item", "food"]),
        ("minecraft:rotten_flesh", "Rotten Flesh", "Dropped from zombies. Low hunger restoration, may cause hunger.", ["item", "food"]),
        ("minecraft:spider_eye", "Spider Eye", "Dropped from spiders and witches. Used for brewing poison potions.", ["item", "material", "brewing"]),
        ("minecraft:poisonous_potato", "Poisonous Potato", "Rare potato drop. Poisons when eaten.", ["item", "food"]),
        ("minecraft:cod", "Raw Cod", "Fish caught in water. Cook for better food.", ["item", "food", "water"]),
        ("minecraft:salmon", "Raw Salmon", "Fish caught in cold water. Cook for better food.", ["item", "food", "water"]),
        ("minecraft:tropical_fish", "Tropical Fish", "Colorful fish caught in warm oceans. No use in crafting.", ["item", "food", "water"]),
        ("minecraft:pufferfish", "Pufferfish", "Inflating fish. Used for water breathing potions. Poisonous to eat.", ["item", "food", "water", "brewing"]),
    ]
    return [{"id": e[0], "category": "item", "name": e[1], "description": e[2], "tags": e[3]} for e in entries]


def recipes():
    entries = [
        ("recipe:crafting_table", "Crafting Table", "Place 4 wooden planks in a 2x2 square in the inventory crafting grid. Expands the grid to 3x3."),
        ("recipe:stick", "Stick", "Place 2 wooden planks vertically in the crafting grid. Used for tools and torches."),
        ("recipe:torch", "Torch", "Place coal above a stick in the crafting grid. Provides light."),
        ("recipe:wooden_pickaxe", "Wooden Pickaxe", "3 planks across the top row and 2 sticks vertically in the middle column of a crafting table."),
        ("recipe:stone_pickaxe", "Stone Pickaxe", "3 cobblestone across the top row and 2 sticks vertically in the middle column."),
        ("recipe:iron_pickaxe", "Iron Pickaxe", "3 iron ingots across the top row and 2 sticks vertically in the middle column."),
        ("recipe:diamond_pickaxe", "Diamond Pickaxe", "3 diamonds across the top row and 2 sticks vertically in the middle column."),
        ("recipe:wooden_axe", "Wooden Axe", "3 planks in top-left, top-middle, and middle-left, plus 2 sticks vertically in middle-right."),
        ("recipe:stone_axe", "Stone Axe", "3 cobblestone in top-left, top-middle, and middle-left, plus 2 sticks vertically in middle-right."),
        ("recipe:iron_axe", "Iron Axe", "3 iron ingots in top-left, top-middle, and middle-left, plus 2 sticks vertically in middle-right."),
        ("recipe:wooden_sword", "Wooden Sword", "2 planks in the top-middle and middle-middle, plus 1 stick in the bottom-middle."),
        ("recipe:stone_sword", "Stone Sword", "2 cobblestone in the top-middle and middle-middle, plus 1 stick in the bottom-middle."),
        ("recipe:iron_sword", "Iron Sword", "2 iron ingots in the top-middle and middle-middle, plus 1 stick in the bottom-middle."),
        ("recipe:diamond_sword", "Diamond Sword", "2 diamonds in the top-middle and middle-middle, plus 1 stick in the bottom-middle."),
        ("recipe:bucket", "Bucket", "3 iron ingots in a V shape in the crafting grid."),
        ("recipe:furnace", "Furnace", "8 cobblestone around the edge of the crafting grid, leaving the center empty."),
        ("recipe:chest", "Chest", "8 wooden planks around the edge of the crafting grid, leaving the center empty."),
        ("recipe:bed", "Bed", "3 wool across the top row and 3 wooden planks across the middle row."),
        ("recipe:shield", "Shield", "6 wood planks in a Y shape plus an iron ingot in the top-middle."),
        ("recipe:bow", "Bow", "3 sticks and 3 string arranged in a U shape with string on the right."),
        ("recipe:arrow", "Arrow", "Flint on top, stick in middle, feather on bottom."),
        ("recipe:paper", "Paper", "3 sugar canes horizontally in the crafting grid."),
        ("recipe:book", "Book", "3 paper and 1 leather."),
        ("recipe:bookshelf", "Bookshelf", "3 books in the middle row and 6 wood planks around them."),
        ("recipe:enchanting_table", "Enchanting Table", "4 obsidian on the bottom, 2 diamonds on the sides, 1 book on top."),
        ("recipe:anvil", "Anvil", "3 iron blocks across the top row, 1 iron ingot in the center, 3 iron ingots in a line at the bottom."),
        ("recipe:iron_helmet", "Iron Helmet", "5 iron ingots in an upside-down U shape in the crafting grid."),
        ("recipe:iron_chestplate", "Iron Chestplate", "8 iron ingots filling all slots except the top-middle."),
        ("recipe:iron_leggings", "Iron Leggings", "7 iron ingots in a U shape leaving the center and top-middle empty."),
        ("recipe:iron_boots", "Iron Boots", "4 iron ingots in a U shape leaving the top and middle empty."),
        ("recipe:compass", "Compass", "4 iron ingots around redstone in the center."),
        ("recipe:clock", "Clock", "4 gold ingots around redstone in the center."),
        ("recipe:flint_and_steel", "Flint and Steel", "Flint and iron ingot diagonally in the crafting grid."),
        ("recipe:glass_bottle", "Glass Bottle", "3 glass blocks in a V shape."),
        ("recipe:brewing_stand", "Brewing Stand", "3 cobblestone across the bottom and 1 blaze rod in the center."),
        ("recipe:cauldron", "Cauldron", "7 iron ingots in a U shape."),
        ("recipe:iron_door", "Iron Door", "6 iron ingots in two vertical columns."),
        ("recipe:wooden_door", "Wooden Door", "6 wood planks in two vertical columns."),
        ("recipe:trapdoor", "Trapdoor", "6 wood planks in two rows of three."),
        ("recipe:fence", "Fence", "4 wood planks and 2 sticks in alternating columns."),
        ("recipe:gate", "Fence Gate", "2 sticks and 4 wood planks in a gate shape."),
        ("recipe:ladder", "Ladder", "7 sticks in a H shape."),
        ("recipe:sign", "Sign", "6 wood planks in the top two rows and 1 stick in the bottom-middle."),
        ("recipe:boat", "Boat", "5 wood planks in a U shape."),
        ("recipe:minecart", "Minecart", "5 iron ingots in a U shape."),
        ("recipe:rail", "Rail", "6 iron ingots and 1 stick in a zigzag pattern."),
        ("recipe:powered_rail", "Powered Rail", "6 gold ingots, 1 stick, and 1 redstone."),
        ("recipe:detector_rail", "Detector Rail", "6 iron ingots, 1 stone pressure plate, and 1 redstone."),
        ("recipe:hopper", "Hopper", "5 iron ingots and 1 chest in a V shape."),
        ("recipe:dispenser", "Dispenser", "7 cobblestone, 1 bow, and 1 redstone in a U shape with bow in center."),
        ("recipe:dropper", "Dropper", "7 cobblestone and 1 redstone in a U shape."),
        ("recipe:piston", "Piston", "3 wood planks, 4 cobblestone, 1 iron ingot, and 1 redstone."),
        ("recipe:sticky_piston", "Sticky Piston", "1 piston and 1 slime ball."),
        ("recipe:redstone_torch", "Redstone Torch", "1 redstone above 1 stick."),
        ("recipe:repeater", "Redstone Repeater", "3 stone blocks, 2 redstone torches, and 1 redstone."),
        ("recipe:comparator", "Redstone Comparator", "3 stone blocks, 3 redstone torches, and 1 nether quartz."),
        ("recipe:daylight_detector", "Daylight Detector", "3 glass, 3 nether quartz, and 3 wood slabs."),
        ("recipe:observer", "Observer", "6 cobblestone, 2 redstone, and 1 nether quartz."),
        ("recipe:note_block", "Note Block", "8 wood planks around 1 redstone."),
        ("recipe:jukebox", "Jukebox", "8 wood planks around 1 diamond."),
        ("recipe:tnt", "TNT", "5 gunpowder in an X and 4 sand around them."),
        ("recipe:fire_charge", "Fire Charge", "1 coal, 1 gunpowder, and 1 blaze powder."),
        ("recipe:firework_rocket", "Firework Rocket", "1 paper and 1 gunpowder. Add firework stars for effects."),
        ("recipe:lead", "Lead", "4 string and 1 slime ball."),
        ("recipe:nametag", "Name Tag", "Cannot be crafted. Found in chests, fishing, or trading with villagers."),
        ("recipe:saddle", "Saddle", "Cannot be crafted. Found in chests, fishing, or trading with villagers."),
    ]
    return [{"id": e[0], "category": "recipe", "name": e[1], "description": e[2], "tags": ["recipe", "crafting"]} for e in entries]


def biomes():
    entries = [
        ("minecraft:plains", "Plains", "Flat grasslands with scattered trees and villages. Good for building and farming."),
        ("minecraft:forest", "Forest", "Overworld biome with many oak and birch trees."),
        ("minecraft:dark_forest", "Dark Forest", "Dense forest with dark oak trees. Woodland mansions can spawn here."),
        ("minecraft:birch_forest", "Birch Forest", "Forest dominated by birch trees."),
        ("minecraft:flower_forest", "Flower Forest", "Forest with many flowers and fewer trees."),
        ("minecraft:taiga", "Taiga", "Cold forest with spruce trees, foxes, and wolves."),
        ("minecraft:snowy_taiga", "Snowy Taiga", "Cold taiga covered in snow."),
        ("minecraft:old_growth_pine_taiga", "Old Growth Pine Taiga", "Taiga with giant spruce trees and podzol ground."),
        ("minecraft:jungle", "Jungle", "Dense tropical biome with tall trees, vines, and temples."),
        ("minecraft:bamboo_jungle", "Bamboo Jungle", "Jungle variant filled with bamboo and pandas."),
        ("minecraft:swamp", "Swamp", "Wet biome with shallow water, oak trees, and witch huts."),
        ("minecraft:mangrove_swamp", "Mangrove Swamp", "Swamp with mangrove trees, mud, and frogs."),
        ("minecraft:desert", "Desert", "Dry biome with sand, cacti, and desert pyramids."),
        ("minecraft:savanna", "Savanna", "Warm grassland with acacia trees and villages."),
        ("minecraft:windswept_savanna", "Windswept Savanna", "Savanna with extreme terrain and floating islands."),
        ("minecraft:badlands", "Badlands", "Dry biome with terracotta and gold ore. Mineshafts spawn on the surface."),
        ("minecraft:wooded_badlands", "Wooded Badlands", "Badlands with patches of oak trees."),
        ("minecraft:meadow", "Meadow", "High-altitude grassy plain with flowers and rabbits."),
        ("minecraft:grove", "Grove", "Snowy forest found on mountain slopes."),
        ("minecraft:snowy_slopes", "Snowy Slopes", "Cold mountain slopes with rabbits and goats."),
        ("minecraft:jagged_peaks", "Jagged Peaks", "High mountain peaks of stone and snow."),
        ("minecraft:frozen_peaks", "Frozen Peaks", "High mountain peaks covered in ice and snow."),
        ("minecraft:stony_peaks", "Stony Peaks", "High mountain peaks made of stone and calcite."),
        ("minecraft:beach", "Beach", "Sandy area between oceans and land."),
        ("minecraft:snowy_beach", "Snowy Beach", "Cold beach covered in snow."),
        ("minecraft:river", "River", "Long stretches of water through the Overworld."),
        ("minecraft:frozen_river", "Frozen River", "River covered in ice."),
        ("minecraft:ocean", "Ocean", "Large saltwater biome with fish, kelp, and shipwrecks."),
        ("minecraft:deep_ocean", "Deep Ocean", "Deeper ocean variant with ocean monuments."),
        ("minecraft:warm_ocean", "Warm Ocean", "Ocean with coral reefs and tropical fish."),
        ("minecraft:lukewarm_ocean", "Lukewarm Ocean", "Ocean between warm and cold."),
        ("minecraft:cold_ocean", "Cold Ocean", "Cold ocean with cod and less life."),
        ("minecraft:frozen_ocean", "Frozen Ocean", "Ocean with icebergs and polar bears."),
        ("minecraft:mushroom_fields", "Mushroom Fields", "Rare biome with mooshrooms and giant mushrooms. No hostile mobs spawn."),
        ("minecraft:nether_wastes", "Nether Wastes", "The main Nether biome with netherrack, lava, and ghasts."),
        ("minecraft:soul_sand_valley", "Soul Sand Valley", "Nether biome with soul sand, soul soil, and skeletons/ghasts."),
        ("minecraft:crimson_forest", "Crimson Forest", "Nether forest with crimson trees, hoglins, and piglins."),
        ("minecraft:warped_forest", "Warped Forest", "Nether forest with warped trees and endermen."),
        ("minecraft:basalt_deltas", "Basalt Deltas", "Nether biome with basalt pillars, magma cubes, and ghasts."),
        ("minecraft:the_end", "The End", "Dimension of floating islands and the Ender Dragon."),
        ("minecraft:end_highlands", "End Highlands", "Outer End islands with chorus plants and end cities."),
        ("minecraft:end_midlands", "End Midlands", "Transition area between central End and outer islands."),
        ("minecraft:end_barrens", "End Barrens", "Empty outer End areas with few features."),
    ]
    return [{"id": e[0], "category": "biome", "name": e[1], "description": e[2], "tags": ["biome"]} for e in entries]


def strategy():
    entries = [
        ("strategy:mining", "Mining", "Dig down carefully with torches, tools, and food. Avoid digging straight down. Use strip mining at diamond levels."),
        ("strategy:strip_mining", "Strip Mining", "Mine long tunnels at Y=-59 to find diamonds. Place torches every 10 blocks and watch for lava."),
        ("strategy:caving", "Caving", "Explore natural caves for exposed ores. Bring plenty of torches, food, and armor."),
        ("strategy:nether_exploration", "Nether Exploration", "Wear gold armor around piglins. Bring fire resistance potions. Build safe paths over lava."),
        ("strategy:end_fight", "Ender Dragon Fight", "Destroy end crystals with arrows or blocks. Attack the dragon when it perches. Bring slow falling potions."),
        ("strategy:wither_fight", "Wither Fight", "Fight underground or in a confined space to limit movement. Use smite enchanted sword and healing potions."),
        ("strategy:warden_avoid", "Warden Avoidance", "Move slowly in the deep dark. Wool blocks reduce vibrations. Use snowballs to distract."),
        ("strategy:villager_trading", "Villager Trading", "Protect villagers with walls and beds. Provide job blocks for trades. Cures zombie villagers for discounts."),
        ("strategy:farming", "Farming", "Plant crops on hydrated farmland. Use bonemeal to speed growth. Keep light level high."),
        ("strategy:animal_farming", "Animal Farming", "Breed animals with their preferred food. Keep them in enclosed pens with water."),
        ("strategy:defense", "Base Defense", "Light the area, build walls, use iron golems, and place traps for hostile mobs."),
        ("strategy:raids", "Raid Defense", "Ring a bell to reveal raiders. Use walls and ranged attacks. Heal between waves."),
        ("strategy:exploration", "Exploration", "Bring food, torches, a bed, and a compass. Mark your path to avoid getting lost."),
        ("strategy:combat", "Combat Basics", "Equip the right weapon and armor. Strafe to avoid attacks. Retreat when low on health."),
        ("strategy:enchanting", "Enchanting", "Build bookshelves around the enchanting table. Use an anvil to combine enchanted books."),
        ("strategy:brewing", "Brewing", "Build a brewing stand with blaze rods. Nether wart is the base for most potions."),
        ("strategy:smelting", "Smelting", "Use furnaces, blast furnaces for ores, and smokers for food. Choose fuel based on availability."),
        ("strategy:redstone", "Redstone Basics", "Power components with redstone dust, torches, and repeaters. Use observers for block detection."),
        ("strategy:building", "Building", "Plan foundations and storage first. Use scaffolding for tall builds. Light interiors."),
        ("strategy:automation", "Automation", "Use hoppers, droppers, dispensers, and observers to create farms, sorters, and mob grinders."),
        ("strategy:speedrun", "Speedrun", "Focus on wood, tools, iron, flint and steel, beds, and eyes of ender. Minimize detours."),
        ("strategy:resource_management", "Resource Management", "Store items in labeled chests. Keep backups of important tools. Use shulker boxes for travel."),
        ("strategy:preparation", "Preparation", "Before a big task, gather food, tools, armor, blocks, potions, and set a spawn point."),
        ("strategy:recovery", "Recovery", "After death, prioritize retrieving items before re-engaging threats. Use a backup set of gear."),
        ("strategy:multiplayer", "Multiplayer", "Coordinate roles, share resources, and establish safe zones. Communicate before risky actions."),
    ]
    return [{"id": e[0], "category": "strategy", "name": e[1], "description": e[2], "tags": ["strategy"]} for e in entries]


if __name__ == "__main__":
    write("blocks.json", blocks())
    write("mobs.json", mobs())
    write("items.json", items())
    write("recipes.json", recipes())
    write("biomes.json", biomes())
    write("strategy.json", strategy())
